// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attributes.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createAttributeDefinition = `-- name: CreateAttributeDefinition :one
INSERT INTO attribute_definitions (id, shop_id, code, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, shop_id, code, sort_order, created_at, updated_at
`

type CreateAttributeDefinitionParams struct {
	ID        uuid.UUID `json:"id"`
	ShopID    uuid.UUID `json:"shop_id"`
	Code      string    `json:"code"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) CreateAttributeDefinition(ctx context.Context, arg CreateAttributeDefinitionParams) (AttributeDefinition, error) {
	row := q.db.QueryRow(ctx, createAttributeDefinition,
		arg.ID,
		arg.ShopID,
		arg.Code,
		arg.SortOrder,
	)
	var i AttributeDefinition
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Code,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttributeDefinition = `-- name: GetAttributeDefinition :one
SELECT id, shop_id, code, sort_order, created_at, updated_at FROM attribute_definitions
WHERE shop_id = $1 AND id = $2
`

type GetAttributeDefinitionParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetAttributeDefinition(ctx context.Context, arg GetAttributeDefinitionParams) (AttributeDefinition, error) {
	row := q.db.QueryRow(ctx, getAttributeDefinition, arg.ShopID, arg.ID)
	var i AttributeDefinition
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Code,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttributeDefinitions = `-- name: ListAttributeDefinitions :many
SELECT
    ad.id, ad.shop_id, ad.code, ad.sort_order, ad.created_at, ad.updated_at,
    -- COALESCE to '': an attribute definition with zero translations must
    -- still list, not fail to scan (LEFT JOIN LATERAL leaves these NULL and
    -- sqlc does not infer that as nullable).
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name,
    COALESCE(agg.translations, '{}'::jsonb) AS translations
FROM attribute_definitions ad
LEFT JOIN LATERAL (
    SELECT adt.locale, adt.name
    FROM attribute_definition_translations adt
    WHERE adt.attribute_definition_id = ad.id
    ORDER BY
        CASE
            WHEN adt.locale = $1 THEN 0
            WHEN adt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
LEFT JOIN LATERAL (
    SELECT jsonb_object_agg(adt2.locale, adt2.name) AS translations
    FROM attribute_definition_translations adt2
    WHERE adt2.attribute_definition_id = ad.id
) agg ON true
WHERE ad.shop_id = $2
ORDER BY ad.sort_order, ad.code
`

type ListAttributeDefinitionsParams struct {
	Locale string    `json:"locale"`
	ShopID uuid.UUID `json:"shop_id"`
}

type ListAttributeDefinitionsRow struct {
	ID           uuid.UUID       `json:"id"`
	ShopID       uuid.UUID       `json:"shop_id"`
	Code         string          `json:"code"`
	SortOrder    int32           `json:"sort_order"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	LocaleUsed   string          `json:"locale_used"`
	Name         string          `json:"name"`
	Translations json.RawMessage `json:"translations"`
}

// Resolved name by locale fallback (requested -> 'uz' -> any), plus every
// translation as a JSON object {locale: name} so the admin edit form can
// show all locales without a second round trip.
func (q *Queries) ListAttributeDefinitions(ctx context.Context, arg ListAttributeDefinitionsParams) ([]ListAttributeDefinitionsRow, error) {
	rows, err := q.db.Query(ctx, listAttributeDefinitions, arg.Locale, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttributeDefinitionsRow
	for rows.Next() {
		var i ListAttributeDefinitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Code,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocaleUsed,
			&i.Name,
			&i.Translations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttributeDefinition = `-- name: UpdateAttributeDefinition :one
UPDATE attribute_definitions
SET
    code = COALESCE($1, code),
    sort_order = COALESCE($2, sort_order),
    updated_at = now()
WHERE shop_id = $3 AND id = $4
RETURNING id, shop_id, code, sort_order, created_at, updated_at
`

type UpdateAttributeDefinitionParams struct {
	Code      *string   `json:"code"`
	SortOrder *int32    `json:"sort_order"`
	ShopID    uuid.UUID `json:"shop_id"`
	ID        uuid.UUID `json:"id"`
}

// Patch: code and sort_order are optional.
func (q *Queries) UpdateAttributeDefinition(ctx context.Context, arg UpdateAttributeDefinitionParams) (AttributeDefinition, error) {
	row := q.db.QueryRow(ctx, updateAttributeDefinition,
		arg.Code,
		arg.SortOrder,
		arg.ShopID,
		arg.ID,
	)
	var i AttributeDefinition
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Code,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAttributeDefinitionTranslation = `-- name: UpsertAttributeDefinitionTranslation :exec
INSERT INTO attribute_definition_translations (attribute_definition_id, locale, name)
VALUES ($1, $2, $3)
ON CONFLICT (attribute_definition_id, locale) DO UPDATE
SET name = EXCLUDED.name
`

type UpsertAttributeDefinitionTranslationParams struct {
	AttributeDefinitionID uuid.UUID `json:"attribute_definition_id"`
	Locale                string    `json:"locale"`
	Name                  string    `json:"name"`
}

func (q *Queries) UpsertAttributeDefinitionTranslation(ctx context.Context, arg UpsertAttributeDefinitionTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertAttributeDefinitionTranslation, arg.AttributeDefinitionID, arg.Locale, arg.Name)
	return err
}
