// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (id, shop_id, actor_id, action, entity_type, entity_id, before, after)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, shop_id, actor_id, action, entity_type, entity_id, before, after, created_at
`

type InsertAuditLogParams struct {
	ID         uuid.UUID `json:"id"`
	ShopID     uuid.UUID `json:"shop_id"`
	ActorID    uuid.UUID `json:"actor_id"`
	Action     string    `json:"action"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Before     []byte    `json:"before"`
	After      []byte    `json:"after"`
}

// Writer-only (§ 03-ARCHITECTURE.md module map: audit has no handler).
// before/after are optional (e.g. a create has no before).
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ID,
		arg.ShopID,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ActorID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.CreatedAt,
	)
	return i, err
}
