// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_telegram.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTelegramAccountByTelegramUserID = `-- name: GetTelegramAccountByTelegramUserID :one
SELECT user_id, shop_id, telegram_user_id, telegram_username, linked_at FROM telegram_accounts
WHERE telegram_user_id = $1
`

// The only lookup that runs before a shop_id is known: an incoming
// Telegram update carries only the Telegram user's id, and this is how
// the bot/auth flow resolves which savdo user (and shop) it belongs to —
// same reasoning as GetSessionByTokenHash (sessions.sql). Every query
// after this one in the same flow takes shop_id from the resolved
// account.
func (q *Queries) GetTelegramAccountByTelegramUserID(ctx context.Context, telegramUserID int64) (TelegramAccount, error) {
	row := q.db.QueryRow(ctx, getTelegramAccountByTelegramUserID, telegramUserID)
	var i TelegramAccount
	err := row.Scan(
		&i.UserID,
		&i.ShopID,
		&i.TelegramUserID,
		&i.TelegramUsername,
		&i.LinkedAt,
	)
	return i, err
}

const getTelegramAccountByUserID = `-- name: GetTelegramAccountByUserID :one
SELECT user_id, shop_id, telegram_user_id, telegram_username, linked_at FROM telegram_accounts
WHERE shop_id = $1 AND user_id = $2
`

type GetTelegramAccountByUserIDParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTelegramAccountByUserID(ctx context.Context, arg GetTelegramAccountByUserIDParams) (TelegramAccount, error) {
	row := q.db.QueryRow(ctx, getTelegramAccountByUserID, arg.ShopID, arg.UserID)
	var i TelegramAccount
	err := row.Scan(
		&i.UserID,
		&i.ShopID,
		&i.TelegramUserID,
		&i.TelegramUsername,
		&i.LinkedAt,
	)
	return i, err
}

const linkTelegramAccount = `-- name: LinkTelegramAccount :one
INSERT INTO telegram_accounts (user_id, shop_id, telegram_user_id, telegram_username, linked_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id) DO UPDATE
SET telegram_user_id = EXCLUDED.telegram_user_id,
    telegram_username = EXCLUDED.telegram_username,
    linked_at = now()
RETURNING user_id, shop_id, telegram_user_id, telegram_username, linked_at
`

type LinkTelegramAccountParams struct {
	UserID           uuid.UUID `json:"user_id"`
	ShopID           uuid.UUID `json:"shop_id"`
	TelegramUserID   int64     `json:"telegram_user_id"`
	TelegramUsername *string   `json:"telegram_username"`
}

// Upsert on user_id (the primary key, 0019_telegram_accounts.sql): a user
// re-linking a different Telegram account replaces the row in place
// rather than erroring. If telegram_user_id already belongs to another
// user, the UNIQUE(telegram_user_id) constraint rejects the insert with a
// distinct error — one Telegram account must never link to two users;
// the service surfaces that as its own error code, not handled here.
func (q *Queries) LinkTelegramAccount(ctx context.Context, arg LinkTelegramAccountParams) (TelegramAccount, error) {
	row := q.db.QueryRow(ctx, linkTelegramAccount,
		arg.UserID,
		arg.ShopID,
		arg.TelegramUserID,
		arg.TelegramUsername,
	)
	var i TelegramAccount
	err := row.Scan(
		&i.UserID,
		&i.ShopID,
		&i.TelegramUserID,
		&i.TelegramUsername,
		&i.LinkedAt,
	)
	return i, err
}

const unlinkTelegramAccount = `-- name: UnlinkTelegramAccount :execrows
DELETE FROM telegram_accounts
WHERE shop_id = $1 AND user_id = $2
`

type UnlinkTelegramAccountParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnlinkTelegramAccount(ctx context.Context, arg UnlinkTelegramAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkTelegramAccount, arg.ShopID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
