// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countProductsInCategory = `-- name: CountProductsInCategory :one
SELECT count(*) FROM products
WHERE shop_id = $1 AND category_id = $2 AND deleted_at IS NULL
`

type CountProductsInCategoryParams struct {
	ShopID     uuid.UUID  `json:"shop_id"`
	CategoryID *uuid.UUID `json:"category_id"`
}

// Used by the service to refuse deleting a category that still has products
// assigned to it (a conflict, not a cascading delete).
func (q *Queries) CountProductsInCategory(ctx context.Context, arg CountProductsInCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsInCategory, arg.ShopID, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, shop_id, parent_id, slug, sort_order, is_active, image_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, shop_id, parent_id, slug, sort_order, is_active, image_id, deleted_at, created_at, updated_at
`

type CreateCategoryParams struct {
	ID        uuid.UUID  `json:"id"`
	ShopID    uuid.UUID  `json:"shop_id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	Slug      string     `json:"slug"`
	SortOrder int32      `json:"sort_order"`
	IsActive  bool       `json:"is_active"`
	ImageID   *uuid.UUID `json:"image_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.ShopID,
		arg.ParentID,
		arg.Slug,
		arg.SortOrder,
		arg.IsActive,
		arg.ImageID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.ImageID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT
    c.id, c.shop_id, c.parent_id, c.slug, c.sort_order, c.is_active, c.image_id, c.deleted_at, c.created_at, c.updated_at,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name,
    t.description
FROM categories c
LEFT JOIN LATERAL (
    SELECT ct.locale, ct.name, ct.description
    FROM category_translations ct
    WHERE ct.category_id = c.id
    ORDER BY
        CASE
            WHEN ct.locale = $1 THEN 0
            WHEN ct.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE c.shop_id = $2 AND c.id = $3 AND c.deleted_at IS NULL
`

type GetCategoryParams struct {
	Locale string    `json:"locale"`
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

type GetCategoryRow struct {
	ID          uuid.UUID  `json:"id"`
	ShopID      uuid.UUID  `json:"shop_id"`
	ParentID    *uuid.UUID `json:"parent_id"`
	Slug        string     `json:"slug"`
	SortOrder   int32      `json:"sort_order"`
	IsActive    bool       `json:"is_active"`
	ImageID     *uuid.UUID `json:"image_id"`
	DeletedAt   *time.Time `json:"deleted_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	LocaleUsed  string     `json:"locale_used"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
}

// Same locale-fallback + COALESCE pattern as ListCategories.
func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (GetCategoryRow, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.Locale, arg.ShopID, arg.ID)
	var i GetCategoryRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.ImageID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocaleUsed,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getCategoryDepth = `-- name: GetCategoryDepth :one
WITH RECURSIVE ancestors AS (
    SELECT cat.id, cat.parent_id, 1 AS depth
    FROM categories cat
    WHERE cat.id = $1 AND cat.shop_id = $2 AND cat.deleted_at IS NULL

    UNION ALL

    SELECT c.id, c.parent_id, a.depth + 1
    FROM categories c
    JOIN ancestors a ON c.id = a.parent_id
    WHERE c.shop_id = $2 AND c.deleted_at IS NULL
)
SELECT COALESCE(max(a.depth), 0)::int AS depth FROM ancestors a
`

type GetCategoryDepthParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	ShopID     uuid.UUID `json:"shop_id"`
}

// Depth of category_id counting from 1 at a root (no parent), by walking
// parent_id up to the root. The service calls this before creating or
// re-parenting a category to enforce depth <= 3 (§ 04-DATA-MODEL.md).
// Both arms filter deleted_at IS NULL and shop_id: a soft-deleted category
// (or one that somehow belongs to another shop) must not be usable as a
// parent, and must not silently participate in a live category's own
// ancestor chain either.
// COALESCE: category_id not found (wrong shop, or soft-deleted) makes
// ancestors empty, and max() over zero rows is NULL — 0 reads better than
// NULL for "does not exist / has no ancestors" here.
func (q *Queries) GetCategoryDepth(ctx context.Context, arg GetCategoryDepthParams) (int32, error) {
	row := q.db.QueryRow(ctx, getCategoryDepth, arg.CategoryID, arg.ShopID)
	var depth int32
	err := row.Scan(&depth)
	return depth, err
}

const getCategorySubtreeHeight = `-- name: GetCategorySubtreeHeight :one
WITH RECURSIVE descendants AS (
    SELECT cat.id, 1 AS height
    FROM categories cat
    WHERE cat.id = $1 AND cat.shop_id = $2 AND cat.deleted_at IS NULL

    UNION ALL

    SELECT c.id, d.height + 1
    FROM categories c
    JOIN descendants d ON c.parent_id = d.id
    WHERE c.shop_id = $2 AND c.deleted_at IS NULL
)
SELECT COALESCE(max(d.height), 0)::int AS height FROM descendants d
`

type GetCategorySubtreeHeightParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	ShopID     uuid.UUID `json:"shop_id"`
}

// Height of category_id's own subtree counting from 1 at itself (a leaf
// has height 1), by walking parent_id -> children down from it. The
// service calls this before re-parenting a category to make sure the
// category's own descendants would not end up past depth 3: if placed
// under a parent at depth(parent), the deepest descendant would land at
// depth(parent) + height(self), which must stay <= 3. Both arms filter
// deleted_at IS NULL and shop_id, same reasoning as GetCategoryDepth.
func (q *Queries) GetCategorySubtreeHeight(ctx context.Context, arg GetCategorySubtreeHeightParams) (int32, error) {
	row := q.db.QueryRow(ctx, getCategorySubtreeHeight, arg.CategoryID, arg.ShopID)
	var height int32
	err := row.Scan(&height)
	return height, err
}

const listCategories = `-- name: ListCategories :many
SELECT
    c.id, c.shop_id, c.parent_id, c.slug, c.sort_order, c.is_active, c.image_id, c.deleted_at, c.created_at, c.updated_at,
    -- COALESCE to '': a category with zero translations (e.g. mid-creation,
    -- before its first UpsertCategoryTranslation) must still list, not fail
    -- to scan — LEFT JOIN LATERAL leaves t.locale/t.name NULL when no
    -- translation matches, and sqlc does not infer that as nullable. An
    -- empty string, not a real locale, signals "no translation yet".
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name,
    -- No COALESCE here, unlike name/locale_used above: description is
    -- nullable at the column level (category_translations.description has
    -- no NOT NULL), so sqlc already infers *string for it straight from the
    -- schema — the LATERAL-join NULL-when-no-match case lands on the same
    -- nullable type instead of needing a '' sentinel.
    t.description
FROM categories c
LEFT JOIN LATERAL (
    SELECT ct.locale, ct.name, ct.description
    FROM category_translations ct
    WHERE ct.category_id = c.id
    ORDER BY
        CASE
            WHEN ct.locale = $1 THEN 0
            WHEN ct.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE c.shop_id = $2
    AND c.deleted_at IS NULL
    AND ($3::bool OR c.is_active)
ORDER BY c.sort_order, c.slug
`

type ListCategoriesParams struct {
	Locale          string    `json:"locale"`
	ShopID          uuid.UUID `json:"shop_id"`
	IncludeInactive bool      `json:"include_inactive"`
}

type ListCategoriesRow struct {
	ID          uuid.UUID  `json:"id"`
	ShopID      uuid.UUID  `json:"shop_id"`
	ParentID    *uuid.UUID `json:"parent_id"`
	Slug        string     `json:"slug"`
	SortOrder   int32      `json:"sort_order"`
	IsActive    bool       `json:"is_active"`
	ImageID     *uuid.UUID `json:"image_id"`
	DeletedAt   *time.Time `json:"deleted_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	LocaleUsed  string     `json:"locale_used"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
}

// Flat list (the service builds the tree from parent_id); resolved name by
// locale fallback (requested -> 'uz' -> any); include_inactive toggles
// whether inactive categories are returned (the admin category picker wants
// them, the public/cashier catalog does not).
func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Locale, arg.ShopID, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ParentID,
			&i.Slug,
			&i.SortOrder,
			&i.IsActive,
			&i.ImageID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocaleUsed,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryTranslations = `-- name: ListCategoryTranslations :many
SELECT t.locale, t.name, t.description
FROM category_translations t
JOIN categories c ON c.id = t.category_id AND c.shop_id = $2
WHERE t.category_id = $1
ORDER BY t.locale
`

type ListCategoryTranslationsParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	ShopID     uuid.UUID `json:"shop_id"`
}

type ListCategoryTranslationsRow struct {
	Locale      string  `json:"locale"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

// shop_id is joined through the parent category, same reasoning as
// ListProductTranslations: a translation row must not be readable through
// the wrong shop_id (hard rule 1), even though the bare category_id FK
// would otherwise let it scan.
func (q *Queries) ListCategoryTranslations(ctx context.Context, arg ListCategoryTranslationsParams) ([]ListCategoryTranslationsRow, error) {
	rows, err := q.db.Query(ctx, listCategoryTranslations, arg.CategoryID, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryTranslationsRow
	for rows.Next() {
		var i ListCategoryTranslationsRow
		if err := rows.Scan(&i.Locale, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCategories = `-- name: ListPublicCategories :many
WITH RECURSIVE active_cats AS (
    SELECT c.id, c.parent_id, c.slug, c.sort_order
    FROM categories c
    WHERE c.shop_id = $2 AND c.deleted_at IS NULL AND c.is_active
),
descendants AS (
    -- Every active category is its own descendant at distance 0 (depth
    -- 1), so a leaf with no children still gets a product_counts row
    -- below, matching the pre-T7 per-category-only count exactly in that
    -- case.
    SELECT id AS ancestor_id, id AS descendant_id, 1 AS depth FROM active_cats

    UNION ALL

    SELECT d.ancestor_id, c.id, d.depth + 1
    FROM active_cats c
    JOIN descendants d ON c.parent_id = d.descendant_id
    WHERE d.depth < 4
),
product_counts AS (
    SELECT d.ancestor_id AS category_id, count(p.id) AS product_count
    FROM descendants d
    JOIN products p ON p.category_id = d.descendant_id
        AND p.shop_id = $2 AND p.deleted_at IS NULL AND p.is_active
    GROUP BY d.ancestor_id
),
paths AS (
    SELECT c.id, lpad(c.sort_order::text, 10, '0') || ':' || c.slug AS sort_path, 1 AS depth
    FROM active_cats c
    WHERE c.parent_id IS NULL OR c.parent_id NOT IN (SELECT id FROM active_cats)

    UNION ALL

    SELECT c.id, p.sort_path || '/' || lpad(c.sort_order::text, 10, '0') || ':' || c.slug, p.depth + 1
    FROM active_cats c
    JOIN paths p ON c.parent_id = p.id
    WHERE p.depth < 4
)
SELECT
    c.id, c.shop_id, c.parent_id, c.slug, c.sort_order, c.is_active, c.image_id, c.created_at, c.updated_at,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name,
    t.description,
    parent.slug AS parent_slug,
    -- Same '' sentinel as name/locale_used above (sqlc infers a plain
    -- non-nullable string here, not *string, the same LATERAL-join
    -- quirk); the handler only surfaces parentName when parent_slug is
    -- non-nil, so a root category's '' here is never observed as a real
    -- value — see handler.go.
    COALESCE(pt.name, '') AS parent_name,
    COALESCE(pc.product_count, 0)::bigint AS product_count
FROM categories c
JOIN active_cats a ON a.id = c.id
JOIN paths pa ON pa.id = c.id
LEFT JOIN categories parent ON parent.id = c.parent_id AND parent.shop_id = c.shop_id
    AND parent.deleted_at IS NULL AND parent.is_active
LEFT JOIN LATERAL (
    SELECT ct.locale, ct.name, ct.description
    FROM category_translations ct
    WHERE ct.category_id = c.id
    ORDER BY
        CASE
            WHEN ct.locale = $1 THEN 0
            WHEN ct.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
LEFT JOIN LATERAL (
    SELECT ct.name
    FROM category_translations ct
    WHERE ct.category_id = parent.id
    ORDER BY
        CASE
            WHEN ct.locale = $1 THEN 0
            WHEN ct.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) pt ON true
LEFT JOIN product_counts pc ON pc.category_id = c.id
WHERE c.shop_id = $2
ORDER BY pa.sort_path
`

type ListPublicCategoriesParams struct {
	Locale string    `json:"locale"`
	ShopID uuid.UUID `json:"shop_id"`
}

type ListPublicCategoriesRow struct {
	ID           uuid.UUID  `json:"id"`
	ShopID       uuid.UUID  `json:"shop_id"`
	ParentID     *uuid.UUID `json:"parent_id"`
	Slug         string     `json:"slug"`
	SortOrder    int32      `json:"sort_order"`
	IsActive     bool       `json:"is_active"`
	ImageID      *uuid.UUID `json:"image_id"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	LocaleUsed   string     `json:"locale_used"`
	Name         string     `json:"name"`
	Description  *string    `json:"description"`
	ParentSlug   *string    `json:"parent_slug"`
	ParentName   string     `json:"parent_name"`
	ProductCount int64      `json:"product_count"`
}

// Phase 6 public catalogue (D-99), extended by T7 for the landing's
// parent/child grouping: active, non-deleted categories, each with its
// resolved name (same locale-fallback + COALESCE ” pattern as
// ListCategories, active-only like ListPublicProducts, no
// include_inactive parameter at all), its immediate parent's slug/name
// (parent_slug/parent_name), and a product_count that now sums active,
// non-deleted products across the category AND every one of its active,
// non-deleted descendants (descendants CTE) — a pure grouping parent
// like "Erkaklar" (no products of its own) reports the total of its
// children instead of 0.
//
// parent_slug/parent_name are NULL for a root category (parent_id IS
// NULL) and, deliberately, also for a category whose parent exists but
// is inactive or soft-deleted: the same "inactive hides everything about
// it, not just itself" rule O-22 already applies to a product's own
// category — a child must not surface an ancestor's slug/name that this
// same endpoint would never itself list as a row, since the landing
// could never link to it. Such a child sorts as a top-level entry too
// (paths CTE's own base case), consistent with having no visible parent.
//
// Rows are ordered by a materialized (sort_order, slug) path built at
// each level by the recursive paths CTE, so a parent always sorts
// immediately before its own children, at any depth up to the schema's
// depth <= 3 rule (04-DATA-MODEL.md) — not just the two levels the
// current catalogue actually uses.
//
// T7 review round 1, MAJOR 1: both descendants and paths carry a depth
// column and stop recursing once depth reaches 4 (one past the schema's
// own depth <= 3 rule, 04-DATA-MODEL.md) — depth is normally enforced by
// catalog.Service before a category is created or re-parented
// (GetCategoryDepth/GetCategorySubtreeHeight), but this endpoint has no
// auth and must not trust that guard alone: a parent_id cycle from a
// manual DB edit (or a bug elsewhere) would otherwise recurse forever and
// hang the request instead of erroring or returning a bounded, if
// incomplete, result.
func (q *Queries) ListPublicCategories(ctx context.Context, arg ListPublicCategoriesParams) ([]ListPublicCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listPublicCategories, arg.Locale, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicCategoriesRow
	for rows.Next() {
		var i ListPublicCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ParentID,
			&i.Slug,
			&i.SortOrder,
			&i.IsActive,
			&i.ImageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocaleUsed,
			&i.Name,
			&i.Description,
			&i.ParentSlug,
			&i.ParentName,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicCategoryExists = `-- name: PublicCategoryExists :one
SELECT EXISTS (
    SELECT 1 FROM categories
    WHERE shop_id = $1
        AND slug = $2
        AND deleted_at IS NULL
        AND is_active
) AS exists
`

type PublicCategoryExistsParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	Slug   string    `json:"slug"`
}

// T3 review round 3, MAJOR (c): public.CacheMiddleware's admission
// control for GET /public/products?category= — a slug that names no
// active, non-deleted category in this shop must never be cached (an
// attacker sweeping many nonexistent slugs would otherwise mint one
// cache entry per slug, all empty 200s). "Exists" here means the exact
// same active/non-deleted visibility ListPublicCategories/
// ListPublicProducts already apply — a real but inactive category counts
// as not existing, the same as it already does everywhere else on this
// surface (O-22).
func (q *Queries) PublicCategoryExists(ctx context.Context, arg PublicCategoryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, publicCategoryExists, arg.ShopID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories
SET deleted_at = now(), updated_at = now()
WHERE shop_id = $1 AND id = $2
`

type SoftDeleteCategoryParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, softDeleteCategory, arg.ShopID, arg.ID)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    parent_id = CASE WHEN $1::bool THEN NULL ELSE COALESCE($2, parent_id) END,
    slug = COALESCE($3, slug),
    sort_order = COALESCE($4, sort_order),
    is_active = COALESCE($5, is_active),
    image_id = CASE WHEN $6::bool THEN NULL ELSE COALESCE($7, image_id) END,
    updated_at = now()
WHERE shop_id = $8 AND id = $9 AND deleted_at IS NULL
RETURNING id, shop_id, parent_id, slug, sort_order, is_active, image_id, deleted_at, created_at, updated_at
`

type UpdateCategoryParams struct {
	ClearParent bool       `json:"clear_parent"`
	ParentID    *uuid.UUID `json:"parent_id"`
	Slug        *string    `json:"slug"`
	SortOrder   *int32     `json:"sort_order"`
	IsActive    *bool      `json:"is_active"`
	ClearImage  bool       `json:"clear_image"`
	ImageID     *uuid.UUID `json:"image_id"`
	ShopID      uuid.UUID  `json:"shop_id"`
	ID          uuid.UUID  `json:"id"`
}

// Patch with explicit clear flags for parent_id/image_id (COALESCE cannot
// express "set to NULL"), same pattern as UpdateProduct/UpdateVariant.
// slug/sort_order/is_active are plain optional fields.
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ClearParent,
		arg.ParentID,
		arg.Slug,
		arg.SortOrder,
		arg.IsActive,
		arg.ClearImage,
		arg.ImageID,
		arg.ShopID,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.ImageID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCategoryTranslation = `-- name: UpsertCategoryTranslation :exec
INSERT INTO category_translations (category_id, locale, name, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (category_id, locale) DO UPDATE
SET name = EXCLUDED.name, description = EXCLUDED.description
`

type UpsertCategoryTranslationParams struct {
	CategoryID  uuid.UUID `json:"category_id"`
	Locale      string    `json:"locale"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) UpsertCategoryTranslation(ctx context.Context, arg UpsertCategoryTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertCategoryTranslation,
		arg.CategoryID,
		arg.Locale,
		arg.Name,
		arg.Description,
	)
	return err
}
