// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countProductsInCategory = `-- name: CountProductsInCategory :one
SELECT count(*) FROM products
WHERE shop_id = $1 AND category_id = $2 AND deleted_at IS NULL
`

type CountProductsInCategoryParams struct {
	ShopID     uuid.UUID  `json:"shop_id"`
	CategoryID *uuid.UUID `json:"category_id"`
}

// Used by the service to refuse deleting a category that still has products
// assigned to it (a conflict, not a cascading delete).
func (q *Queries) CountProductsInCategory(ctx context.Context, arg CountProductsInCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsInCategory, arg.ShopID, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, shop_id, parent_id, slug, sort_order, is_active, image_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, shop_id, parent_id, slug, sort_order, is_active, image_id, deleted_at, created_at, updated_at
`

type CreateCategoryParams struct {
	ID        uuid.UUID  `json:"id"`
	ShopID    uuid.UUID  `json:"shop_id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	Slug      string     `json:"slug"`
	SortOrder int32      `json:"sort_order"`
	IsActive  bool       `json:"is_active"`
	ImageID   *uuid.UUID `json:"image_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.ShopID,
		arg.ParentID,
		arg.Slug,
		arg.SortOrder,
		arg.IsActive,
		arg.ImageID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.ImageID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT
    c.id, c.shop_id, c.parent_id, c.slug, c.sort_order, c.is_active, c.image_id, c.deleted_at, c.created_at, c.updated_at,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name,
    t.description
FROM categories c
LEFT JOIN LATERAL (
    SELECT ct.locale, ct.name, ct.description
    FROM category_translations ct
    WHERE ct.category_id = c.id
    ORDER BY
        CASE
            WHEN ct.locale = $1 THEN 0
            WHEN ct.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE c.shop_id = $2 AND c.id = $3 AND c.deleted_at IS NULL
`

type GetCategoryParams struct {
	Locale string    `json:"locale"`
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

type GetCategoryRow struct {
	ID          uuid.UUID  `json:"id"`
	ShopID      uuid.UUID  `json:"shop_id"`
	ParentID    *uuid.UUID `json:"parent_id"`
	Slug        string     `json:"slug"`
	SortOrder   int32      `json:"sort_order"`
	IsActive    bool       `json:"is_active"`
	ImageID     *uuid.UUID `json:"image_id"`
	DeletedAt   *time.Time `json:"deleted_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	LocaleUsed  string     `json:"locale_used"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
}

// Same locale-fallback + COALESCE pattern as ListCategories.
func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (GetCategoryRow, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.Locale, arg.ShopID, arg.ID)
	var i GetCategoryRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.ImageID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocaleUsed,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getCategoryDepth = `-- name: GetCategoryDepth :one
WITH RECURSIVE ancestors AS (
    SELECT cat.id, cat.parent_id, 1 AS depth
    FROM categories cat
    WHERE cat.id = $1 AND cat.shop_id = $2 AND cat.deleted_at IS NULL

    UNION ALL

    SELECT c.id, c.parent_id, a.depth + 1
    FROM categories c
    JOIN ancestors a ON c.id = a.parent_id
    WHERE c.shop_id = $2 AND c.deleted_at IS NULL
)
SELECT COALESCE(max(a.depth), 0)::int AS depth FROM ancestors a
`

type GetCategoryDepthParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	ShopID     uuid.UUID `json:"shop_id"`
}

// Depth of category_id counting from 1 at a root (no parent), by walking
// parent_id up to the root. The service calls this before creating or
// re-parenting a category to enforce depth <= 3 (§ 04-DATA-MODEL.md).
// Both arms filter deleted_at IS NULL and shop_id: a soft-deleted category
// (or one that somehow belongs to another shop) must not be usable as a
// parent, and must not silently participate in a live category's own
// ancestor chain either.
// COALESCE: category_id not found (wrong shop, or soft-deleted) makes
// ancestors empty, and max() over zero rows is NULL — 0 reads better than
// NULL for "does not exist / has no ancestors" here.
func (q *Queries) GetCategoryDepth(ctx context.Context, arg GetCategoryDepthParams) (int32, error) {
	row := q.db.QueryRow(ctx, getCategoryDepth, arg.CategoryID, arg.ShopID)
	var depth int32
	err := row.Scan(&depth)
	return depth, err
}

const getCategorySubtreeHeight = `-- name: GetCategorySubtreeHeight :one
WITH RECURSIVE descendants AS (
    SELECT cat.id, 1 AS height
    FROM categories cat
    WHERE cat.id = $1 AND cat.shop_id = $2 AND cat.deleted_at IS NULL

    UNION ALL

    SELECT c.id, d.height + 1
    FROM categories c
    JOIN descendants d ON c.parent_id = d.id
    WHERE c.shop_id = $2 AND c.deleted_at IS NULL
)
SELECT COALESCE(max(d.height), 0)::int AS height FROM descendants d
`

type GetCategorySubtreeHeightParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	ShopID     uuid.UUID `json:"shop_id"`
}

// Height of category_id's own subtree counting from 1 at itself (a leaf
// has height 1), by walking parent_id -> children down from it. The
// service calls this before re-parenting a category to make sure the
// category's own descendants would not end up past depth 3: if placed
// under a parent at depth(parent), the deepest descendant would land at
// depth(parent) + height(self), which must stay <= 3. Both arms filter
// deleted_at IS NULL and shop_id, same reasoning as GetCategoryDepth.
func (q *Queries) GetCategorySubtreeHeight(ctx context.Context, arg GetCategorySubtreeHeightParams) (int32, error) {
	row := q.db.QueryRow(ctx, getCategorySubtreeHeight, arg.CategoryID, arg.ShopID)
	var height int32
	err := row.Scan(&height)
	return height, err
}

const listCategories = `-- name: ListCategories :many
SELECT
    c.id, c.shop_id, c.parent_id, c.slug, c.sort_order, c.is_active, c.image_id, c.deleted_at, c.created_at, c.updated_at,
    -- COALESCE to '': a category with zero translations (e.g. mid-creation,
    -- before its first UpsertCategoryTranslation) must still list, not fail
    -- to scan — LEFT JOIN LATERAL leaves t.locale/t.name NULL when no
    -- translation matches, and sqlc does not infer that as nullable. An
    -- empty string, not a real locale, signals "no translation yet".
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name,
    -- No COALESCE here, unlike name/locale_used above: description is
    -- nullable at the column level (category_translations.description has
    -- no NOT NULL), so sqlc already infers *string for it straight from the
    -- schema — the LATERAL-join NULL-when-no-match case lands on the same
    -- nullable type instead of needing a '' sentinel.
    t.description
FROM categories c
LEFT JOIN LATERAL (
    SELECT ct.locale, ct.name, ct.description
    FROM category_translations ct
    WHERE ct.category_id = c.id
    ORDER BY
        CASE
            WHEN ct.locale = $1 THEN 0
            WHEN ct.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE c.shop_id = $2
    AND c.deleted_at IS NULL
    AND ($3::bool OR c.is_active)
ORDER BY c.sort_order, c.slug
`

type ListCategoriesParams struct {
	Locale          string    `json:"locale"`
	ShopID          uuid.UUID `json:"shop_id"`
	IncludeInactive bool      `json:"include_inactive"`
}

type ListCategoriesRow struct {
	ID          uuid.UUID  `json:"id"`
	ShopID      uuid.UUID  `json:"shop_id"`
	ParentID    *uuid.UUID `json:"parent_id"`
	Slug        string     `json:"slug"`
	SortOrder   int32      `json:"sort_order"`
	IsActive    bool       `json:"is_active"`
	ImageID     *uuid.UUID `json:"image_id"`
	DeletedAt   *time.Time `json:"deleted_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	LocaleUsed  string     `json:"locale_used"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
}

// Flat list (the service builds the tree from parent_id); resolved name by
// locale fallback (requested -> 'uz' -> any); include_inactive toggles
// whether inactive categories are returned (the admin category picker wants
// them, the public/cashier catalog does not).
func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Locale, arg.ShopID, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ParentID,
			&i.Slug,
			&i.SortOrder,
			&i.IsActive,
			&i.ImageID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocaleUsed,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryTranslations = `-- name: ListCategoryTranslations :many
SELECT locale, name, description FROM category_translations WHERE category_id = $1 ORDER BY locale
`

type ListCategoryTranslationsRow struct {
	Locale      string  `json:"locale"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) ListCategoryTranslations(ctx context.Context, categoryID uuid.UUID) ([]ListCategoryTranslationsRow, error) {
	rows, err := q.db.Query(ctx, listCategoryTranslations, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryTranslationsRow
	for rows.Next() {
		var i ListCategoryTranslationsRow
		if err := rows.Scan(&i.Locale, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories
SET deleted_at = now(), updated_at = now()
WHERE shop_id = $1 AND id = $2
`

type SoftDeleteCategoryParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, softDeleteCategory, arg.ShopID, arg.ID)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    parent_id = CASE WHEN $1::bool THEN NULL ELSE COALESCE($2, parent_id) END,
    slug = COALESCE($3, slug),
    sort_order = COALESCE($4, sort_order),
    is_active = COALESCE($5, is_active),
    image_id = CASE WHEN $6::bool THEN NULL ELSE COALESCE($7, image_id) END,
    updated_at = now()
WHERE shop_id = $8 AND id = $9 AND deleted_at IS NULL
RETURNING id, shop_id, parent_id, slug, sort_order, is_active, image_id, deleted_at, created_at, updated_at
`

type UpdateCategoryParams struct {
	ClearParent bool       `json:"clear_parent"`
	ParentID    *uuid.UUID `json:"parent_id"`
	Slug        *string    `json:"slug"`
	SortOrder   *int32     `json:"sort_order"`
	IsActive    *bool      `json:"is_active"`
	ClearImage  bool       `json:"clear_image"`
	ImageID     *uuid.UUID `json:"image_id"`
	ShopID      uuid.UUID  `json:"shop_id"`
	ID          uuid.UUID  `json:"id"`
}

// Patch with explicit clear flags for parent_id/image_id (COALESCE cannot
// express "set to NULL"), same pattern as UpdateProduct/UpdateVariant.
// slug/sort_order/is_active are plain optional fields.
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ClearParent,
		arg.ParentID,
		arg.Slug,
		arg.SortOrder,
		arg.IsActive,
		arg.ClearImage,
		arg.ImageID,
		arg.ShopID,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.ImageID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCategoryTranslation = `-- name: UpsertCategoryTranslation :exec
INSERT INTO category_translations (category_id, locale, name, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (category_id, locale) DO UPDATE
SET name = EXCLUDED.name, description = EXCLUDED.description
`

type UpsertCategoryTranslationParams struct {
	CategoryID  uuid.UUID `json:"category_id"`
	Locale      string    `json:"locale"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) UpsertCategoryTranslation(ctx context.Context, arg UpsertCategoryTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertCategoryTranslation,
		arg.CategoryID,
		arg.Locale,
		arg.Name,
		arg.Description,
	)
	return err
}
