// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getContentBlock = `-- name: GetContentBlock :one
SELECT shop_id, key, locale, data, updated_by, updated_at FROM content_blocks
WHERE shop_id = $1 AND key = $2 AND locale = $3
`

type GetContentBlockParams struct {
	ShopID uuid.UUID       `json:"shop_id"`
	Key    ContentBlockKey `json:"key"`
	Locale string          `json:"locale"`
}

// One (key, locale) pair, exact match only — no fallback here. The Phase 6
// content service resolves requested -> uz -> any (D-104) in Go from
// ListContentBlocksByKey's rows; this is the plain single-row read the
// manager+ editor uses (GET /content/{key} reads one locale at a time).
func (q *Queries) GetContentBlock(ctx context.Context, arg GetContentBlockParams) (ContentBlock, error) {
	row := q.db.QueryRow(ctx, getContentBlock, arg.ShopID, arg.Key, arg.Locale)
	var i ContentBlock
	err := row.Scan(
		&i.ShopID,
		&i.Key,
		&i.Locale,
		&i.Data,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listContentBlocksByKey = `-- name: ListContentBlocksByKey :many
SELECT shop_id, key, locale, data, updated_by, updated_at FROM content_blocks
WHERE shop_id = $1 AND key = $2
ORDER BY locale
`

type ListContentBlocksByKeyParams struct {
	ShopID uuid.UUID       `json:"shop_id"`
	Key    ContentBlockKey `json:"key"`
}

// Every locale saved for one key, for the admin editor (shows uz/ru/en side
// by side) and for the D-104 fallback resolution a single content read
// needs.
func (q *Queries) ListContentBlocksByKey(ctx context.Context, arg ListContentBlocksByKeyParams) ([]ContentBlock, error) {
	rows, err := q.db.Query(ctx, listContentBlocksByKey, arg.ShopID, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentBlock
	for rows.Next() {
		var i ContentBlock
		if err := rows.Scan(
			&i.ShopID,
			&i.Key,
			&i.Locale,
			&i.Data,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentBlocksForShop = `-- name: ListContentBlocksForShop :many
SELECT shop_id, key, locale, data, updated_by, updated_at FROM content_blocks
WHERE shop_id = $1
ORDER BY key, locale
`

// Every key, every locale, for the shop — feeds GET /public/shop, which
// resolves each key's fallback (requested -> uz -> any, D-104) in Go from
// this one query rather than one query per key.
func (q *Queries) ListContentBlocksForShop(ctx context.Context, shopID uuid.UUID) ([]ContentBlock, error) {
	rows, err := q.db.Query(ctx, listContentBlocksForShop, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentBlock
	for rows.Next() {
		var i ContentBlock
		if err := rows.Scan(
			&i.ShopID,
			&i.Key,
			&i.Locale,
			&i.Data,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContentBlock = `-- name: UpsertContentBlock :one
INSERT INTO content_blocks (shop_id, key, locale, data, updated_by, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (shop_id, key, locale) DO UPDATE
SET data = EXCLUDED.data, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING shop_id, key, locale, data, updated_by, updated_at
`

type UpsertContentBlockParams struct {
	ShopID    uuid.UUID       `json:"shop_id"`
	Key       ContentBlockKey `json:"key"`
	Locale    string          `json:"locale"`
	Data      json.RawMessage `json:"data"`
	UpdatedBy *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) UpsertContentBlock(ctx context.Context, arg UpsertContentBlockParams) (ContentBlock, error) {
	row := q.db.QueryRow(ctx, upsertContentBlock,
		arg.ShopID,
		arg.Key,
		arg.Locale,
		arg.Data,
		arg.UpdatedBy,
	)
	var i ContentBlock
	err := row.Scan(
		&i.ShopID,
		&i.Key,
		&i.Locale,
		&i.Data,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
