// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (id, shop_id, full_name, phone, telegram_username, note, tags)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    COALESCE($7::text[], '{}')
)
RETURNING id, shop_id, full_name, phone, telegram_username, note, tags, deleted_at, created_at, updated_at
`

type CreateCustomerParams struct {
	ID               uuid.UUID `json:"id"`
	ShopID           uuid.UUID `json:"shop_id"`
	FullName         string    `json:"full_name"`
	Phone            *string   `json:"phone"`
	TelegramUsername *string   `json:"telegram_username"`
	Note             *string   `json:"note"`
	Tags             []string  `json:"tags"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.ID,
		arg.ShopID,
		arg.FullName,
		arg.Phone,
		arg.TelegramUsername,
		arg.Note,
		arg.Tags,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.FullName,
		&i.Phone,
		&i.TelegramUsername,
		&i.Note,
		&i.Tags,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, shop_id, full_name, phone, telegram_username, note, tags, deleted_at, created_at, updated_at FROM customers
WHERE shop_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetCustomerParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetCustomer(ctx context.Context, arg GetCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, arg.ShopID, arg.ID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.FullName,
		&i.Phone,
		&i.TelegramUsername,
		&i.Note,
		&i.Tags,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, shop_id, full_name, phone, telegram_username, note, tags, deleted_at, created_at, updated_at FROM customers
WHERE shop_id = $1
    AND deleted_at IS NULL
    AND (
        $2::text IS NULL
        OR full_name ILIKE '%' || $2 || '%'
        OR phone ILIKE '%' || $2 || '%'
    )
    AND (
        $3::timestamptz IS NULL
        OR (created_at, id) < ($3::timestamptz, $4::uuid)
    )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListCustomersParams struct {
	ShopID          uuid.UUID  `json:"shop_id"`
	Q               *string    `json:"q"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	Limit           int32      `json:"limit"`
}

// Keyset pagination on (created_at, id), newest first — same convention as
// ListSuppliers. q matches full_name or phone by substring (ILIKE); the
// customer directory can grow larger than suppliers, but a leading-'%'
// ILIKE cannot use an index either way, so no trigram index is added here
// (same reasoning as ListSuppliers).
func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.ShopID,
		arg.Q,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.FullName,
			&i.Phone,
			&i.TelegramUsername,
			&i.Note,
			&i.Tags,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCustomer = `-- name: SoftDeleteCustomer :exec
UPDATE customers
SET deleted_at = now(), updated_at = now()
WHERE shop_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteCustomerParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteCustomer(ctx context.Context, arg SoftDeleteCustomerParams) error {
	_, err := q.db.Exec(ctx, softDeleteCustomer, arg.ShopID, arg.ID)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET
    full_name = COALESCE($1, full_name),
    phone = CASE WHEN $2::bool THEN NULL ELSE COALESCE($3, phone) END,
    telegram_username = CASE WHEN $4::bool THEN NULL ELSE COALESCE($5, telegram_username) END,
    note = CASE WHEN $6::bool THEN NULL ELSE COALESCE($7, note) END,
    tags = COALESCE($8::text[], tags),
    updated_at = now()
WHERE shop_id = $9 AND id = $10 AND deleted_at IS NULL
RETURNING id, shop_id, full_name, phone, telegram_username, note, tags, deleted_at, created_at, updated_at
`

type UpdateCustomerParams struct {
	FullName              *string   `json:"full_name"`
	ClearPhone            bool      `json:"clear_phone"`
	Phone                 *string   `json:"phone"`
	ClearTelegramUsername bool      `json:"clear_telegram_username"`
	TelegramUsername      *string   `json:"telegram_username"`
	ClearNote             bool      `json:"clear_note"`
	Note                  *string   `json:"note"`
	Tags                  []string  `json:"tags"`
	ShopID                uuid.UUID `json:"shop_id"`
	ID                    uuid.UUID `json:"id"`
}

// Patch with explicit clear flags for the nullable fields (COALESCE cannot
// express "set to NULL"), same shape as UpdateSupplier. tags is a full
// replace, not a merge — the service reads-modifies-writes the array if it
// needs to add/remove one tag.
func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.FullName,
		arg.ClearPhone,
		arg.Phone,
		arg.ClearTelegramUsername,
		arg.TelegramUsername,
		arg.ClearNote,
		arg.Note,
		arg.Tags,
		arg.ShopID,
		arg.ID,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.FullName,
		&i.Phone,
		&i.TelegramUsername,
		&i.Note,
		&i.Tags,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
