// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT shop_id, key, request_hash, response_status, response_body, created_at FROM idempotency_keys
WHERE shop_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	Key    string    `json:"key"`
}

// Looked up on every request carrying an `Idempotency-Key` header
// (docs/05-API.md § Conventions) before the operation runs; a hit returns
// the stored response instead of repeating the write.
func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.ShopID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ShopID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (shop_id, key, request_hash, response_status, response_body)
VALUES ($1, $2, $3, $4, $5)
RETURNING shop_id, key, request_hash, response_status, response_body, created_at
`

type InsertIdempotencyKeyParams struct {
	ShopID         uuid.UUID `json:"shop_id"`
	Key            string    `json:"key"`
	RequestHash    string    `json:"request_hash"`
	ResponseStatus int32     `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
}

// Written once, after the operation completes, with its result already
// known — there is no separate "in flight" state to update later.
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.ShopID,
		arg.Key,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ShopID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}
