// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearDefaultLocation = `-- name: ClearDefaultLocation :exec
UPDATE locations
SET is_default = false, updated_at = now()
WHERE shop_id = $1 AND is_default = true
`

// Run before UpdateLocation(..., is_default = true) in the same transaction
// so the partial unique index on (shop_id) WHERE is_default is never
// violated.
func (q *Queries) ClearDefaultLocation(ctx context.Context, shopID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultLocation, shopID)
	return err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (id, shop_id, name, kind, is_default, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, shop_id, name, kind, is_default, is_active, created_at, updated_at
`

type CreateLocationParams struct {
	ID        uuid.UUID    `json:"id"`
	ShopID    uuid.UUID    `json:"shop_id"`
	Name      string       `json:"name"`
	Kind      LocationKind `json:"kind"`
	IsDefault bool         `json:"is_default"`
	IsActive  bool         `json:"is_active"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.ID,
		arg.ShopID,
		arg.Name,
		arg.Kind,
		arg.IsDefault,
		arg.IsActive,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Kind,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocation = `-- name: GetLocation :one
SELECT id, shop_id, name, kind, is_default, is_active, created_at, updated_at FROM locations
WHERE shop_id = $1 AND id = $2
`

type GetLocationParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetLocation(ctx context.Context, arg GetLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, arg.ShopID, arg.ID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Kind,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationForUpdate = `-- name: GetLocationForUpdate :one
SELECT id, shop_id, name, kind, is_default, is_active, created_at, updated_at FROM locations
WHERE shop_id = $1 AND id = $2
FOR UPDATE
`

type GetLocationForUpdateParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetLocationForUpdate(ctx context.Context, arg GetLocationForUpdateParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationForUpdate, arg.ShopID, arg.ID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Kind,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, shop_id, name, kind, is_default, is_active, created_at, updated_at FROM locations
WHERE shop_id = $1
    AND (
        $2::timestamptz IS NULL
        OR (created_at, id) < ($2::timestamptz, $3::uuid)
    )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListLocationsParams struct {
	ShopID          uuid.UUID  `json:"shop_id"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	Limit           int32      `json:"limit"`
}

// Keyset pagination on (created_at, id), newest first — same convention as
// ListUsers.
func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations,
		arg.ShopID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Kind,
			&i.IsDefault,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shopHasLocations = `-- name: ShopHasLocations :one
SELECT EXISTS (SELECT 1 FROM locations WHERE shop_id = $1)
`

// Used inside the transaction after LockShop to decide whether a location
// about to be created is the shop's first (and therefore its default).
func (q *Queries) ShopHasLocations(ctx context.Context, shopID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, shopHasLocations, shopID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET
    name = COALESCE($1, name),
    kind = COALESCE($2, kind),
    is_default = COALESCE($3, is_default),
    is_active = COALESCE($4, is_active),
    updated_at = now()
WHERE shop_id = $5 AND id = $6
RETURNING id, shop_id, name, kind, is_default, is_active, created_at, updated_at
`

type UpdateLocationParams struct {
	Name      *string       `json:"name"`
	Kind      *LocationKind `json:"kind"`
	IsDefault *bool         `json:"is_default"`
	IsActive  *bool         `json:"is_active"`
	ShopID    uuid.UUID     `json:"shop_id"`
	ID        uuid.UUID     `json:"id"`
}

// Patch. Setting is_default = true here can violate the "one default per
// shop" partial unique index unless the caller has already run
// ClearDefaultLocation in the same transaction.
func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.Name,
		arg.Kind,
		arg.IsDefault,
		arg.IsActive,
		arg.ShopID,
		arg.ID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Kind,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
