// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMediaFile = `-- name: CreateMediaFile :one
INSERT INTO media_files (id, shop_id, storage_key, mime, size_bytes, width, height, sha256, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, shop_id, storage_key, mime, size_bytes, width, height, sha256, uploaded_by, created_at, updated_at
`

type CreateMediaFileParams struct {
	ID         uuid.UUID  `json:"id"`
	ShopID     uuid.UUID  `json:"shop_id"`
	StorageKey string     `json:"storage_key"`
	Mime       string     `json:"mime"`
	SizeBytes  int64      `json:"size_bytes"`
	Width      *int32     `json:"width"`
	Height     *int32     `json:"height"`
	Sha256     []byte     `json:"sha256"`
	UploadedBy *uuid.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateMediaFile(ctx context.Context, arg CreateMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, createMediaFile,
		arg.ID,
		arg.ShopID,
		arg.StorageKey,
		arg.Mime,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.Sha256,
		arg.UploadedBy,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.StorageKey,
		&i.Mime,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaFile = `-- name: DeleteMediaFile :exec
DELETE FROM media_files
WHERE shop_id = $1 AND id = $2
`

type DeleteMediaFileParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

// media_files is not in the soft-delete list (§ 04-DATA-MODEL.md rule 7) —
// only products, variants, customers, suppliers are. The FK from
// product_images prevents deleting a file still attached to a product.
func (q *Queries) DeleteMediaFile(ctx context.Context, arg DeleteMediaFileParams) error {
	_, err := q.db.Exec(ctx, deleteMediaFile, arg.ShopID, arg.ID)
	return err
}

const getMediaFile = `-- name: GetMediaFile :one
SELECT id, shop_id, storage_key, mime, size_bytes, width, height, sha256, uploaded_by, created_at, updated_at FROM media_files
WHERE shop_id = $1 AND id = $2
`

type GetMediaFileParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetMediaFile(ctx context.Context, arg GetMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getMediaFile, arg.ShopID, arg.ID)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.StorageKey,
		&i.Mime,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaFileBySHA256 = `-- name: GetMediaFileBySHA256 :one
SELECT id, shop_id, storage_key, mime, size_bytes, width, height, sha256, uploaded_by, created_at, updated_at FROM media_files
WHERE shop_id = $1 AND sha256 = $2
`

type GetMediaFileBySHA256Params struct {
	ShopID uuid.UUID `json:"shop_id"`
	Sha256 []byte    `json:"sha256"`
}

// Upload dedup: the service hashes the incoming file first and looks for an
// existing row before writing a new one to disk.
func (q *Queries) GetMediaFileBySHA256(ctx context.Context, arg GetMediaFileBySHA256Params) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getMediaFileBySHA256, arg.ShopID, arg.Sha256)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.StorageKey,
		&i.Mime,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
