// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdjustmentReason string

const (
	AdjustmentReasonCountCorrection AdjustmentReason = "count_correction"
	AdjustmentReasonDamaged         AdjustmentReason = "damaged"
	AdjustmentReasonLost            AdjustmentReason = "lost"
	AdjustmentReasonFound           AdjustmentReason = "found"
	AdjustmentReasonOther           AdjustmentReason = "other"
)

func (e *AdjustmentReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdjustmentReason(s)
	case string:
		*e = AdjustmentReason(s)
	default:
		return fmt.Errorf("unsupported scan type for AdjustmentReason: %T", src)
	}
	return nil
}

type NullAdjustmentReason struct {
	AdjustmentReason AdjustmentReason `json:"adjustment_reason"`
	Valid            bool             `json:"valid"` // Valid is true if AdjustmentReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdjustmentReason) Scan(value interface{}) error {
	if value == nil {
		ns.AdjustmentReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdjustmentReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdjustmentReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdjustmentReason), nil
}

type LocationKind string

const (
	LocationKindStore     LocationKind = "store"
	LocationKindWarehouse LocationKind = "warehouse"
)

func (e *LocationKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocationKind(s)
	case string:
		*e = LocationKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LocationKind: %T", src)
	}
	return nil
}

type NullLocationKind struct {
	LocationKind LocationKind `json:"location_kind"`
	Valid        bool         `json:"valid"` // Valid is true if LocationKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocationKind) Scan(value interface{}) error {
	if value == nil {
		ns.LocationKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocationKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocationKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocationKind), nil
}

type PurchaseStatus string

const (
	PurchaseStatusDraft     PurchaseStatus = "draft"
	PurchaseStatusReceived  PurchaseStatus = "received"
	PurchaseStatusCancelled PurchaseStatus = "cancelled"
)

func (e *PurchaseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PurchaseStatus(s)
	case string:
		*e = PurchaseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PurchaseStatus: %T", src)
	}
	return nil
}

type NullPurchaseStatus struct {
	PurchaseStatus PurchaseStatus `json:"purchase_status"`
	Valid          bool           `json:"valid"` // Valid is true if PurchaseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPurchaseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PurchaseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PurchaseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPurchaseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PurchaseStatus), nil
}

type SessionClient string

const (
	SessionClientWeb    SessionClient = "web"
	SessionClientMobile SessionClient = "mobile"
)

func (e *SessionClient) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionClient(s)
	case string:
		*e = SessionClient(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionClient: %T", src)
	}
	return nil
}

type NullSessionClient struct {
	SessionClient SessionClient `json:"session_client"`
	Valid         bool          `json:"valid"` // Valid is true if SessionClient is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionClient) Scan(value interface{}) error {
	if value == nil {
		ns.SessionClient, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionClient.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionClient) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionClient), nil
}

type StockMovementKind string

const (
	StockMovementKindPurchaseIn  StockMovementKind = "purchase_in"
	StockMovementKindSaleOut     StockMovementKind = "sale_out"
	StockMovementKindSaleVoidIn  StockMovementKind = "sale_void_in"
	StockMovementKindReturnIn    StockMovementKind = "return_in"
	StockMovementKindAdjustment  StockMovementKind = "adjustment"
	StockMovementKindTransferOut StockMovementKind = "transfer_out"
	StockMovementKindTransferIn  StockMovementKind = "transfer_in"
)

func (e *StockMovementKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockMovementKind(s)
	case string:
		*e = StockMovementKind(s)
	default:
		return fmt.Errorf("unsupported scan type for StockMovementKind: %T", src)
	}
	return nil
}

type NullStockMovementKind struct {
	StockMovementKind StockMovementKind `json:"stock_movement_kind"`
	Valid             bool              `json:"valid"` // Valid is true if StockMovementKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockMovementKind) Scan(value interface{}) error {
	if value == nil {
		ns.StockMovementKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockMovementKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockMovementKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockMovementKind), nil
}

type UserRole string

const (
	UserRoleOwner   UserRole = "owner"
	UserRoleManager UserRole = "manager"
	UserRoleCashier UserRole = "cashier"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AttributeDefinition struct {
	ID        uuid.UUID `json:"id"`
	ShopID    uuid.UUID `json:"shop_id"`
	Code      string    `json:"code"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type AttributeDefinitionTranslation struct {
	AttributeDefinitionID uuid.UUID `json:"attribute_definition_id"`
	Locale                string    `json:"locale"`
	Name                  string    `json:"name"`
}

type AuditLog struct {
	ID         uuid.UUID `json:"id"`
	ShopID     uuid.UUID `json:"shop_id"`
	ActorID    uuid.UUID `json:"actor_id"`
	Action     string    `json:"action"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Before     []byte    `json:"before"`
	After      []byte    `json:"after"`
	CreatedAt  time.Time `json:"created_at"`
}

type Category struct {
	ID        uuid.UUID  `json:"id"`
	ShopID    uuid.UUID  `json:"shop_id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	Slug      string     `json:"slug"`
	SortOrder int32      `json:"sort_order"`
	IsActive  bool       `json:"is_active"`
	ImageID   *uuid.UUID `json:"image_id"`
	DeletedAt *time.Time `json:"deleted_at"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type CategoryTranslation struct {
	CategoryID  uuid.UUID `json:"category_id"`
	Locale      string    `json:"locale"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

type IdempotencyKey struct {
	ShopID         uuid.UUID `json:"shop_id"`
	Key            string    `json:"key"`
	RequestHash    string    `json:"request_hash"`
	ResponseStatus int32     `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
	CreatedAt      time.Time `json:"created_at"`
}

type Location struct {
	ID        uuid.UUID    `json:"id"`
	ShopID    uuid.UUID    `json:"shop_id"`
	Name      string       `json:"name"`
	Kind      LocationKind `json:"kind"`
	IsDefault bool         `json:"is_default"`
	IsActive  bool         `json:"is_active"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type MediaFile struct {
	ID         uuid.UUID  `json:"id"`
	ShopID     uuid.UUID  `json:"shop_id"`
	StorageKey string     `json:"storage_key"`
	Mime       string     `json:"mime"`
	SizeBytes  int64      `json:"size_bytes"`
	Width      *int32     `json:"width"`
	Height     *int32     `json:"height"`
	Sha256     []byte     `json:"sha256"`
	UploadedBy *uuid.UUID `json:"uploaded_by"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type Product struct {
	ID                uuid.UUID      `json:"id"`
	ShopID            uuid.UUID      `json:"shop_id"`
	CategoryID        *uuid.UUID     `json:"category_id"`
	UnitID            uuid.UUID      `json:"unit_id"`
	Slug              string         `json:"slug"`
	Sku               *string        `json:"sku"`
	BasePrice         pgtype.Numeric `json:"base_price"`
	CostPrice         pgtype.Numeric `json:"cost_price"`
	PromoPrice        pgtype.Numeric `json:"promo_price"`
	PromoFrom         *time.Time     `json:"promo_from"`
	PromoTo           *time.Time     `json:"promo_to"`
	IsActive          bool           `json:"is_active"`
	IsFeatured        bool           `json:"is_featured"`
	HasVariants       bool           `json:"has_variants"`
	DeletedAt         *time.Time     `json:"deleted_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	LowStockThreshold *int32         `json:"low_stock_threshold"`
}

type ProductImage struct {
	ID        uuid.UUID  `json:"id"`
	ShopID    uuid.UUID  `json:"shop_id"`
	ProductID uuid.UUID  `json:"product_id"`
	VariantID *uuid.UUID `json:"variant_id"`
	MediaID   uuid.UUID  `json:"media_id"`
	SortOrder int32      `json:"sort_order"`
	IsCover   bool       `json:"is_cover"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type ProductTranslation struct {
	ProductID   uuid.UUID `json:"product_id"`
	Locale      string    `json:"locale"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

type ProductVariant struct {
	ID            uuid.UUID       `json:"id"`
	ShopID        uuid.UUID       `json:"shop_id"`
	ProductID     uuid.UUID       `json:"product_id"`
	Sku           *string         `json:"sku"`
	Barcode       *string         `json:"barcode"`
	Attributes    json.RawMessage `json:"attributes"`
	PriceOverride pgtype.Numeric  `json:"price_override"`
	CostOverride  pgtype.Numeric  `json:"cost_override"`
	IsActive      bool            `json:"is_active"`
	DeletedAt     *time.Time      `json:"deleted_at"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Purchase struct {
	ID                uuid.UUID      `json:"id"`
	ShopID            uuid.UUID      `json:"shop_id"`
	SupplierID        uuid.UUID      `json:"supplier_id"`
	LocationID        uuid.UUID      `json:"location_id"`
	Number            string         `json:"number"`
	SupplierInvoiceNo *string        `json:"supplier_invoice_no"`
	Status            PurchaseStatus `json:"status"`
	ReceivedAt        *time.Time     `json:"received_at"`
	Note              *string        `json:"note"`
	TotalCost         pgtype.Numeric `json:"total_cost"`
	CreatedBy         *uuid.UUID     `json:"created_by"`
	CancelledAt       *time.Time     `json:"cancelled_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type PurchaseItem struct {
	ID         uuid.UUID      `json:"id"`
	ShopID     uuid.UUID      `json:"shop_id"`
	PurchaseID uuid.UUID      `json:"purchase_id"`
	VariantID  uuid.UUID      `json:"variant_id"`
	Qty        pgtype.Numeric `json:"qty"`
	UnitCost   pgtype.Numeric `json:"unit_cost"`
	LineTotal  pgtype.Numeric `json:"line_total"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Session struct {
	ID         uuid.UUID     `json:"id"`
	ShopID     uuid.UUID     `json:"shop_id"`
	UserID     uuid.UUID     `json:"user_id"`
	TokenHash  []byte        `json:"token_hash"`
	Client     SessionClient `json:"client"`
	UserAgent  *string       `json:"user_agent"`
	Ip         *netip.Addr   `json:"ip"`
	ExpiresAt  time.Time     `json:"expires_at"`
	LastSeenAt time.Time     `json:"last_seen_at"`
	RevokedAt  *time.Time    `json:"revoked_at"`
	CreatedAt  time.Time     `json:"created_at"`
}

type Shop struct {
	ID                   uuid.UUID `json:"id"`
	Slug                 string    `json:"slug"`
	Name                 string    `json:"name"`
	Currency             string    `json:"currency"`
	Timezone             string    `json:"timezone"`
	DefaultLocale        string    `json:"default_locale"`
	AllowNegativeStock   bool      `json:"allow_negative_stock"`
	UpdateCostOnPurchase bool      `json:"update_cost_on_purchase"`
	NextSaleNumber       int64     `json:"next_sale_number"`
	AiDailyTokenBudget   *int32    `json:"ai_daily_token_budget"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
	LowStockThreshold    int32     `json:"low_stock_threshold"`
	NextPurchaseNumber   int64     `json:"next_purchase_number"`
}

type StockLevel struct {
	ShopID     uuid.UUID      `json:"shop_id"`
	VariantID  uuid.UUID      `json:"variant_id"`
	LocationID uuid.UUID      `json:"location_id"`
	Qty        pgtype.Numeric `json:"qty"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type StockMovement struct {
	ID               uuid.UUID         `json:"id"`
	ShopID           uuid.UUID         `json:"shop_id"`
	VariantID        uuid.UUID         `json:"variant_id"`
	LocationID       uuid.UUID         `json:"location_id"`
	Kind             StockMovementKind `json:"kind"`
	Qty              pgtype.Numeric    `json:"qty"`
	UnitCost         pgtype.Numeric    `json:"unit_cost"`
	RefType          *string           `json:"ref_type"`
	RefID            *uuid.UUID        `json:"ref_id"`
	AdjustmentReason *AdjustmentReason `json:"adjustment_reason"`
	Reason           *string           `json:"reason"`
	CreatedBy        *uuid.UUID        `json:"created_by"`
	CreatedAt        time.Time         `json:"created_at"`
}

type Supplier struct {
	ID               uuid.UUID  `json:"id"`
	ShopID           uuid.UUID  `json:"shop_id"`
	Name             string     `json:"name"`
	ContactName      *string    `json:"contact_name"`
	Phone            *string    `json:"phone"`
	TelegramUsername *string    `json:"telegram_username"`
	Note             *string    `json:"note"`
	DeletedAt        *time.Time `json:"deleted_at"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type Unit struct {
	ID        uuid.UUID `json:"id"`
	ShopID    uuid.UUID `json:"shop_id"`
	Code      string    `json:"code"`
	Precision int16     `json:"precision"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UnitTranslation struct {
	UnitID uuid.UUID `json:"unit_id"`
	Locale string    `json:"locale"`
	Name   string    `json:"name"`
}

type User struct {
	ID           uuid.UUID  `json:"id"`
	ShopID       uuid.UUID  `json:"shop_id"`
	Username     string     `json:"username"`
	PasswordHash string     `json:"password_hash"`
	FullName     string     `json:"full_name"`
	Phone        *string    `json:"phone"`
	Role         UserRole   `json:"role"`
	Locale       string     `json:"locale"`
	IsActive     bool       `json:"is_active"`
	LastLoginAt  *time.Time `json:"last_login_at"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}
