// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOTPCode = `-- name: CreateOTPCode :one
INSERT INTO otp_codes (id, shop_id, user_id, purpose, code_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, shop_id, user_id, purpose, code_hash, expires_at, used_at, attempts, created_at
`

type CreateOTPCodeParams struct {
	ID        uuid.UUID  `json:"id"`
	ShopID    uuid.UUID  `json:"shop_id"`
	UserID    uuid.UUID  `json:"user_id"`
	Purpose   OtpPurpose `json:"purpose"`
	CodeHash  []byte     `json:"code_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
}

func (q *Queries) CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTPCode,
		arg.ID,
		arg.ShopID,
		arg.UserID,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const expireOTPCodes = `-- name: ExpireOTPCodes :execrows
UPDATE otp_codes
SET used_at = now()
WHERE shop_id = $1 AND user_id = $2 AND purpose = $3 AND used_at IS NULL
`

type ExpireOTPCodesParams struct {
	ShopID  uuid.UUID  `json:"shop_id"`
	UserID  uuid.UUID  `json:"user_id"`
	Purpose OtpPurpose `json:"purpose"`
}

// Issuing a fresh code for the same (user, purpose) invalidates every
// still-active one first (D-06): only one code is ever checkable at a
// time. Already-expired-but-unused rows are also marked used here — they
// are dead either way, and this keeps GetActiveOTPCode's "at most one
// live row" invariant simple to reason about.
func (q *Queries) ExpireOTPCodes(ctx context.Context, arg ExpireOTPCodesParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireOTPCodes, arg.ShopID, arg.UserID, arg.Purpose)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveOTPCode = `-- name: GetActiveOTPCode :one
SELECT id, shop_id, user_id, purpose, code_hash, expires_at, used_at, attempts, created_at FROM otp_codes
WHERE shop_id = $1 AND user_id = $2 AND purpose = $3
    AND used_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveOTPCodeParams struct {
	ShopID  uuid.UUID  `json:"shop_id"`
	UserID  uuid.UUID  `json:"user_id"`
	Purpose OtpPurpose `json:"purpose"`
}

// Newest unused, unexpired code for a (user, purpose) pair — the one the
// service checks the submitted code against. "Newest" matters because
// ExpireOTPCodes marks every earlier active code used when a new one is
// issued (D-06's "new code invalidates old"), but this query does not
// depend on that having run: it would still pick the most recently
// created active row even if two somehow existed at once.
func (q *Queries) GetActiveOTPCode(ctx context.Context, arg GetActiveOTPCodeParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getActiveOTPCode, arg.ShopID, arg.UserID, arg.Purpose)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :one
UPDATE otp_codes
SET attempts = attempts + 1
WHERE shop_id = $1 AND id = $2
RETURNING id, shop_id, user_id, purpose, code_hash, expires_at, used_at, attempts, created_at
`

type IncrementOTPAttemptsParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

// Called on every wrong-code submission; the service compares the
// returned attempts against its own max-attempts constant and marks the
// code used (MarkOTPUsed) once exceeded, same shape as a login lockout.
func (q *Queries) IncrementOTPAttempts(ctx context.Context, arg IncrementOTPAttemptsParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, incrementOTPAttempts, arg.ShopID, arg.ID)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const markOTPUsed = `-- name: MarkOTPUsed :one
UPDATE otp_codes
SET used_at = now()
WHERE shop_id = $1 AND id = $2 AND used_at IS NULL
RETURNING id, shop_id, user_id, purpose, code_hash, expires_at, used_at, attempts, created_at
`

type MarkOTPUsedParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

// used_at IS NULL guard: a code cannot be marked used twice, so a replay
// of an already-consumed code's id updates zero rows (:one still errors
// pgx.ErrNoRows in that case, which the service maps to "code invalid").
func (q *Queries) MarkOTPUsed(ctx context.Context, arg MarkOTPUsedParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, markOTPUsed, arg.ShopID, arg.ID)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}
