// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_images.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addProductImage = `-- name: AddProductImage :one
INSERT INTO product_images (id, shop_id, product_id, variant_id, media_id, sort_order, is_cover)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, shop_id, product_id, variant_id, media_id, sort_order, is_cover, created_at, updated_at
`

type AddProductImageParams struct {
	ID        uuid.UUID  `json:"id"`
	ShopID    uuid.UUID  `json:"shop_id"`
	ProductID uuid.UUID  `json:"product_id"`
	VariantID *uuid.UUID `json:"variant_id"`
	MediaID   uuid.UUID  `json:"media_id"`
	SortOrder int32      `json:"sort_order"`
	IsCover   bool       `json:"is_cover"`
}

func (q *Queries) AddProductImage(ctx context.Context, arg AddProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, addProductImage,
		arg.ID,
		arg.ShopID,
		arg.ProductID,
		arg.VariantID,
		arg.MediaID,
		arg.SortOrder,
		arg.IsCover,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ProductID,
		&i.VariantID,
		&i.MediaID,
		&i.SortOrder,
		&i.IsCover,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearCover = `-- name: ClearCover :exec
UPDATE product_images
SET is_cover = false, updated_at = now()
WHERE shop_id = $1 AND product_id = $2 AND is_cover
`

type ClearCoverParams struct {
	ShopID    uuid.UUID `json:"shop_id"`
	ProductID uuid.UUID `json:"product_id"`
}

// Run before SetCover in the same transaction so the partial unique index
// on (product_id) WHERE is_cover is never violated — same pattern as
// ClearDefaultLocation before UpdateLocation(..., is_default = true).
func (q *Queries) ClearCover(ctx context.Context, arg ClearCoverParams) error {
	_, err := q.db.Exec(ctx, clearCover, arg.ShopID, arg.ProductID)
	return err
}

const countProductImages = `-- name: CountProductImages :one
SELECT count(*) FROM product_images
WHERE shop_id = $1 AND product_id = $2
`

type CountProductImagesParams struct {
	ShopID    uuid.UUID `json:"shop_id"`
	ProductID uuid.UUID `json:"product_id"`
}

// Enforces the "up to 8 images per product" limit (D-34) in the service.
func (q *Queries) CountProductImages(ctx context.Context, arg CountProductImagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductImages, arg.ShopID, arg.ProductID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listImageIDsForProduct = `-- name: ListImageIDsForProduct :many
SELECT id FROM product_images
WHERE shop_id = $1 AND product_id = $2
`

type ListImageIDsForProductParams struct {
	ShopID    uuid.UUID `json:"shop_id"`
	ProductID uuid.UUID `json:"product_id"`
}

// Used by the service to validate that a reorder request names exactly the
// product's current image set before applying UpdateImageOrder per id.
func (q *Queries) ListImageIDsForProduct(ctx context.Context, arg ListImageIDsForProductParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listImageIDsForProduct, arg.ShopID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImages = `-- name: ListProductImages :many
SELECT
    pi.id, pi.shop_id, pi.product_id, pi.variant_id, pi.media_id,
    pi.sort_order, pi.is_cover, pi.created_at, pi.updated_at,
    mf.storage_key, mf.mime, mf.size_bytes, mf.width, mf.height
FROM product_images pi
JOIN media_files mf ON mf.id = pi.media_id
WHERE pi.shop_id = $1 AND pi.product_id = $2
ORDER BY pi.sort_order, pi.id
`

type ListProductImagesParams struct {
	ShopID    uuid.UUID `json:"shop_id"`
	ProductID uuid.UUID `json:"product_id"`
}

type ListProductImagesRow struct {
	ID         uuid.UUID  `json:"id"`
	ShopID     uuid.UUID  `json:"shop_id"`
	ProductID  uuid.UUID  `json:"product_id"`
	VariantID  *uuid.UUID `json:"variant_id"`
	MediaID    uuid.UUID  `json:"media_id"`
	SortOrder  int32      `json:"sort_order"`
	IsCover    bool       `json:"is_cover"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	StorageKey string     `json:"storage_key"`
	Mime       string     `json:"mime"`
	SizeBytes  int64      `json:"size_bytes"`
	Width      *int32     `json:"width"`
	Height     *int32     `json:"height"`
}

// Joined with media_files so the caller gets storage_key/mime/dimensions
// without a second round trip per image.
func (q *Queries) ListProductImages(ctx context.Context, arg ListProductImagesParams) ([]ListProductImagesRow, error) {
	rows, err := q.db.Query(ctx, listProductImages, arg.ShopID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductImagesRow
	for rows.Next() {
		var i ListProductImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ProductID,
			&i.VariantID,
			&i.MediaID,
			&i.SortOrder,
			&i.IsCover,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StorageKey,
			&i.Mime,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProductImage = `-- name: RemoveProductImage :exec
DELETE FROM product_images
WHERE shop_id = $1 AND id = $2
`

type RemoveProductImageParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

// Hard delete: product_images is a join row (§ 04-DATA-MODEL.md rule 7).
func (q *Queries) RemoveProductImage(ctx context.Context, arg RemoveProductImageParams) error {
	_, err := q.db.Exec(ctx, removeProductImage, arg.ShopID, arg.ID)
	return err
}

const setCover = `-- name: SetCover :exec
UPDATE product_images
SET is_cover = true, updated_at = now()
WHERE shop_id = $1 AND id = $2
`

type SetCoverParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SetCover(ctx context.Context, arg SetCoverParams) error {
	_, err := q.db.Exec(ctx, setCover, arg.ShopID, arg.ID)
	return err
}

const updateImageOrder = `-- name: UpdateImageOrder :exec
UPDATE product_images
SET sort_order = $3, updated_at = now()
WHERE shop_id = $1 AND id = $2
`

type UpdateImageOrderParams struct {
	ShopID    uuid.UUID `json:"shop_id"`
	ID        uuid.UUID `json:"id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateImageOrder(ctx context.Context, arg UpdateImageOrderParams) error {
	_, err := q.db.Exec(ctx, updateImageOrder, arg.ShopID, arg.ID, arg.SortOrder)
	return err
}

const updateProductImage = `-- name: UpdateProductImage :exec
UPDATE product_images
SET
    variant_id = CASE WHEN $1::bool THEN NULL ELSE COALESCE($2, variant_id) END,
    is_cover = COALESCE($3, is_cover),
    updated_at = now()
WHERE shop_id = $4 AND id = $5
`

type UpdateProductImageParams struct {
	ClearVariant bool       `json:"clear_variant"`
	VariantID    *uuid.UUID `json:"variant_id"`
	IsCover      *bool      `json:"is_cover"`
	ShopID       uuid.UUID  `json:"shop_id"`
	ID           uuid.UUID  `json:"id"`
}

// ProductImagePatch (D-43): patch with an explicit clear flag for
// variant_id (COALESCE cannot express "set to NULL"), same pattern as
// UpdateCategory/UpdateProduct/UpdateVariant. is_cover is a plain
// optional: when the caller sets it true, the service runs ClearCover
// first in the same transaction so this statement's is_cover = true never
// collides with product_images_one_cover_key; when false, this statement
// clears only this row's flag, no promotion.
func (q *Queries) UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) error {
	_, err := q.db.Exec(ctx, updateProductImage,
		arg.ClearVariant,
		arg.VariantID,
		arg.IsCover,
		arg.ShopID,
		arg.ID,
	)
	return err
}
