// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    id, shop_id, category_id, unit_id, slug, sku,
    base_price, cost_price, promo_price, promo_from, promo_to,
    is_active, is_featured, low_stock_threshold
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, shop_id, category_id, unit_id, slug, sku, base_price, cost_price, promo_price, promo_from, promo_to, is_active, is_featured, has_variants, deleted_at, created_at, updated_at, low_stock_threshold
`

type CreateProductParams struct {
	ID                uuid.UUID      `json:"id"`
	ShopID            uuid.UUID      `json:"shop_id"`
	CategoryID        *uuid.UUID     `json:"category_id"`
	UnitID            uuid.UUID      `json:"unit_id"`
	Slug              string         `json:"slug"`
	Sku               *string        `json:"sku"`
	BasePrice         pgtype.Numeric `json:"base_price"`
	CostPrice         pgtype.Numeric `json:"cost_price"`
	PromoPrice        pgtype.Numeric `json:"promo_price"`
	PromoFrom         *time.Time     `json:"promo_from"`
	PromoTo           *time.Time     `json:"promo_to"`
	IsActive          bool           `json:"is_active"`
	IsFeatured        bool           `json:"is_featured"`
	LowStockThreshold *int32         `json:"low_stock_threshold"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.ShopID,
		arg.CategoryID,
		arg.UnitID,
		arg.Slug,
		arg.Sku,
		arg.BasePrice,
		arg.CostPrice,
		arg.PromoPrice,
		arg.PromoFrom,
		arg.PromoTo,
		arg.IsActive,
		arg.IsFeatured,
		arg.LowStockThreshold,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.UnitID,
		&i.Slug,
		&i.Sku,
		&i.BasePrice,
		&i.CostPrice,
		&i.PromoPrice,
		&i.PromoFrom,
		&i.PromoTo,
		&i.IsActive,
		&i.IsFeatured,
		&i.HasVariants,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LowStockThreshold,
	)
	return i, err
}

const getProductForCashier = `-- name: GetProductForCashier :one
SELECT
    p.id, p.shop_id, p.category_id, p.unit_id, p.slug, p.sku,
    p.base_price, p.promo_price, p.promo_from, p.promo_to,
    p.is_active, p.is_featured, p.has_variants, p.deleted_at,
    p.low_stock_threshold, p.created_at, p.updated_at,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name
FROM products p
LEFT JOIN LATERAL (
    SELECT pt.locale, pt.name
    FROM product_translations pt
    WHERE pt.product_id = p.id
    ORDER BY
        CASE
            WHEN pt.locale = $1 THEN 0
            WHEN pt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE p.shop_id = $2 AND p.id = $3 AND p.deleted_at IS NULL
`

type GetProductForCashierParams struct {
	Locale string    `json:"locale"`
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

type GetProductForCashierRow struct {
	ID                uuid.UUID      `json:"id"`
	ShopID            uuid.UUID      `json:"shop_id"`
	CategoryID        *uuid.UUID     `json:"category_id"`
	UnitID            uuid.UUID      `json:"unit_id"`
	Slug              string         `json:"slug"`
	Sku               *string        `json:"sku"`
	BasePrice         pgtype.Numeric `json:"base_price"`
	PromoPrice        pgtype.Numeric `json:"promo_price"`
	PromoFrom         *time.Time     `json:"promo_from"`
	PromoTo           *time.Time     `json:"promo_to"`
	IsActive          bool           `json:"is_active"`
	IsFeatured        bool           `json:"is_featured"`
	HasVariants       bool           `json:"has_variants"`
	DeletedAt         *time.Time     `json:"deleted_at"`
	LowStockThreshold *int32         `json:"low_stock_threshold"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	LocaleUsed        string         `json:"locale_used"`
	Name              string         `json:"name"`
}

// Same locale-fallback + COALESCE pattern as ListProductsForCashier; no
// cost_price (§ 04-DATA-MODEL.md rule 8, ADR-010).
func (q *Queries) GetProductForCashier(ctx context.Context, arg GetProductForCashierParams) (GetProductForCashierRow, error) {
	row := q.db.QueryRow(ctx, getProductForCashier, arg.Locale, arg.ShopID, arg.ID)
	var i GetProductForCashierRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.UnitID,
		&i.Slug,
		&i.Sku,
		&i.BasePrice,
		&i.PromoPrice,
		&i.PromoFrom,
		&i.PromoTo,
		&i.IsActive,
		&i.IsFeatured,
		&i.HasVariants,
		&i.DeletedAt,
		&i.LowStockThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocaleUsed,
		&i.Name,
	)
	return i, err
}

const getProductForStaff = `-- name: GetProductForStaff :one
SELECT
    p.id, p.shop_id, p.category_id, p.unit_id, p.slug, p.sku, p.base_price, p.cost_price, p.promo_price, p.promo_from, p.promo_to, p.is_active, p.is_featured, p.has_variants, p.deleted_at, p.created_at, p.updated_at, p.low_stock_threshold,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name
FROM products p
LEFT JOIN LATERAL (
    SELECT pt.locale, pt.name
    FROM product_translations pt
    WHERE pt.product_id = p.id
    ORDER BY
        CASE
            WHEN pt.locale = $1 THEN 0
            WHEN pt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE p.shop_id = $2 AND p.id = $3 AND p.deleted_at IS NULL
`

type GetProductForStaffParams struct {
	Locale string    `json:"locale"`
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

type GetProductForStaffRow struct {
	ID                uuid.UUID      `json:"id"`
	ShopID            uuid.UUID      `json:"shop_id"`
	CategoryID        *uuid.UUID     `json:"category_id"`
	UnitID            uuid.UUID      `json:"unit_id"`
	Slug              string         `json:"slug"`
	Sku               *string        `json:"sku"`
	BasePrice         pgtype.Numeric `json:"base_price"`
	CostPrice         pgtype.Numeric `json:"cost_price"`
	PromoPrice        pgtype.Numeric `json:"promo_price"`
	PromoFrom         *time.Time     `json:"promo_from"`
	PromoTo           *time.Time     `json:"promo_to"`
	IsActive          bool           `json:"is_active"`
	IsFeatured        bool           `json:"is_featured"`
	HasVariants       bool           `json:"has_variants"`
	DeletedAt         *time.Time     `json:"deleted_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	LowStockThreshold *int32         `json:"low_stock_threshold"`
	LocaleUsed        string         `json:"locale_used"`
	Name              string         `json:"name"`
}

// Same locale-fallback + COALESCE pattern as ListProductsForStaff.
func (q *Queries) GetProductForStaff(ctx context.Context, arg GetProductForStaffParams) (GetProductForStaffRow, error) {
	row := q.db.QueryRow(ctx, getProductForStaff, arg.Locale, arg.ShopID, arg.ID)
	var i GetProductForStaffRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.UnitID,
		&i.Slug,
		&i.Sku,
		&i.BasePrice,
		&i.CostPrice,
		&i.PromoPrice,
		&i.PromoFrom,
		&i.PromoTo,
		&i.IsActive,
		&i.IsFeatured,
		&i.HasVariants,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LowStockThreshold,
		&i.LocaleUsed,
		&i.Name,
	)
	return i, err
}

const getProductPublic = `-- name: GetProductPublic :one
SELECT
    p.id, p.shop_id, p.category_id, p.unit_id, p.slug, p.sku,
    p.base_price, p.promo_price, p.promo_from, p.promo_to,
    p.is_featured, p.created_at,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name
FROM products p
LEFT JOIN LATERAL (
    SELECT pt.locale, pt.name
    FROM product_translations pt
    WHERE pt.product_id = p.id
    ORDER BY
        CASE
            WHEN pt.locale = $1 THEN 0
            WHEN pt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE p.shop_id = $2 AND p.id = $3 AND p.deleted_at IS NULL AND p.is_active
`

type GetProductPublicParams struct {
	Locale string    `json:"locale"`
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

type GetProductPublicRow struct {
	ID         uuid.UUID      `json:"id"`
	ShopID     uuid.UUID      `json:"shop_id"`
	CategoryID *uuid.UUID     `json:"category_id"`
	UnitID     uuid.UUID      `json:"unit_id"`
	Slug       string         `json:"slug"`
	Sku        *string        `json:"sku"`
	BasePrice  pgtype.Numeric `json:"base_price"`
	PromoPrice pgtype.Numeric `json:"promo_price"`
	PromoFrom  *time.Time     `json:"promo_from"`
	PromoTo    *time.Time     `json:"promo_to"`
	IsFeatured bool           `json:"is_featured"`
	CreatedAt  time.Time      `json:"created_at"`
	LocaleUsed string         `json:"locale_used"`
	Name       string         `json:"name"`
}

// Same locale-fallback + COALESCE pattern as ListProductsPublic; active
// only, never cost.
func (q *Queries) GetProductPublic(ctx context.Context, arg GetProductPublicParams) (GetProductPublicRow, error) {
	row := q.db.QueryRow(ctx, getProductPublic, arg.Locale, arg.ShopID, arg.ID)
	var i GetProductPublicRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.UnitID,
		&i.Slug,
		&i.Sku,
		&i.BasePrice,
		&i.PromoPrice,
		&i.PromoFrom,
		&i.PromoTo,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.LocaleUsed,
		&i.Name,
	)
	return i, err
}

const getPublicProductBySlug = `-- name: GetPublicProductBySlug :one
SELECT
    p.id, p.shop_id, p.category_id, p.unit_id, p.slug, p.sku,
    p.base_price, p.promo_price, p.promo_from, p.promo_to,
    p.is_featured, p.created_at,
    c.slug AS category_slug,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name,
    t.description
FROM products p
LEFT JOIN categories c ON c.id = p.category_id AND c.shop_id = p.shop_id
LEFT JOIN LATERAL (
    SELECT pt.locale, pt.name, pt.description
    FROM product_translations pt
    WHERE pt.product_id = p.id
    ORDER BY
        CASE
            WHEN pt.locale = $1 THEN 0
            WHEN pt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE p.shop_id = $2
    AND p.slug = $3
    AND p.deleted_at IS NULL
    AND p.is_active
    AND (p.category_id IS NULL OR (c.deleted_at IS NULL AND c.is_active))
`

type GetPublicProductBySlugParams struct {
	Locale string    `json:"locale"`
	ShopID uuid.UUID `json:"shop_id"`
	Slug   string    `json:"slug"`
}

type GetPublicProductBySlugRow struct {
	ID           uuid.UUID      `json:"id"`
	ShopID       uuid.UUID      `json:"shop_id"`
	CategoryID   *uuid.UUID     `json:"category_id"`
	UnitID       uuid.UUID      `json:"unit_id"`
	Slug         string         `json:"slug"`
	Sku          *string        `json:"sku"`
	BasePrice    pgtype.Numeric `json:"base_price"`
	PromoPrice   pgtype.Numeric `json:"promo_price"`
	PromoFrom    *time.Time     `json:"promo_from"`
	PromoTo      *time.Time     `json:"promo_to"`
	IsFeatured   bool           `json:"is_featured"`
	CreatedAt    time.Time      `json:"created_at"`
	CategorySlug *string        `json:"category_slug"`
	LocaleUsed   string         `json:"locale_used"`
	Name         string         `json:"name"`
	Description  *string        `json:"description"`
}

func (q *Queries) GetPublicProductBySlug(ctx context.Context, arg GetPublicProductBySlugParams) (GetPublicProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicProductBySlug, arg.Locale, arg.ShopID, arg.Slug)
	var i GetPublicProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.UnitID,
		&i.Slug,
		&i.Sku,
		&i.BasePrice,
		&i.PromoPrice,
		&i.PromoFrom,
		&i.PromoTo,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.CategorySlug,
		&i.LocaleUsed,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const listProductTranslations = `-- name: ListProductTranslations :many
SELECT t.product_id, t.locale, t.name, t.description FROM product_translations t
JOIN products p ON p.id = t.product_id AND p.shop_id = $2
WHERE t.product_id = $1
ORDER BY t.locale
`

type ListProductTranslationsParams struct {
	ProductID uuid.UUID `json:"product_id"`
	ShopID    uuid.UUID `json:"shop_id"`
}

// shop_id is joined through the parent product, not a column on
// product_translations itself: a translation row must not be readable
// through the wrong shop_id (hard rule 1 — every query filters by
// shop_id), even though the bare product_id FK would otherwise let it scan.
func (q *Queries) ListProductTranslations(ctx context.Context, arg ListProductTranslationsParams) ([]ProductTranslation, error) {
	rows, err := q.db.Query(ctx, listProductTranslations, arg.ProductID, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductTranslation
	for rows.Next() {
		var i ProductTranslation
		if err := rows.Scan(
			&i.ProductID,
			&i.Locale,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsForCashier = `-- name: ListProductsForCashier :many
SELECT
    p.id, p.shop_id, p.category_id, p.unit_id, p.slug, p.sku,
    p.base_price, p.promo_price, p.promo_from, p.promo_to,
    p.is_active, p.is_featured, p.has_variants, p.deleted_at,
    p.low_stock_threshold, p.created_at, p.updated_at,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name
FROM products p
LEFT JOIN LATERAL (
    SELECT pt.locale, pt.name
    FROM product_translations pt
    WHERE pt.product_id = p.id
    ORDER BY
        CASE
            WHEN pt.locale = $1 THEN 0
            WHEN pt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE p.shop_id = $2
    AND p.deleted_at IS NULL
    AND ($3::bool OR p.is_active)
    AND ($4::uuid IS NULL OR p.category_id = $4)
    AND (
        $5::text IS NULL
        OR EXISTS (
            SELECT 1 FROM product_translations spt
            WHERE spt.product_id = p.id
                AND (spt.name ILIKE '%' || $5 || '%' OR spt.name % $5)
        )
    )
    AND (
        $6::timestamptz IS NULL
        OR (p.created_at, p.id) < ($6::timestamptz, $7::uuid)
    )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $8
`

type ListProductsForCashierParams struct {
	Locale          string     `json:"locale"`
	ShopID          uuid.UUID  `json:"shop_id"`
	IncludeInactive bool       `json:"include_inactive"`
	CategoryID      *uuid.UUID `json:"category_id"`
	Q               *string    `json:"q"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	Limit           int32      `json:"limit"`
}

type ListProductsForCashierRow struct {
	ID                uuid.UUID      `json:"id"`
	ShopID            uuid.UUID      `json:"shop_id"`
	CategoryID        *uuid.UUID     `json:"category_id"`
	UnitID            uuid.UUID      `json:"unit_id"`
	Slug              string         `json:"slug"`
	Sku               *string        `json:"sku"`
	BasePrice         pgtype.Numeric `json:"base_price"`
	PromoPrice        pgtype.Numeric `json:"promo_price"`
	PromoFrom         *time.Time     `json:"promo_from"`
	PromoTo           *time.Time     `json:"promo_to"`
	IsActive          bool           `json:"is_active"`
	IsFeatured        bool           `json:"is_featured"`
	HasVariants       bool           `json:"has_variants"`
	DeletedAt         *time.Time     `json:"deleted_at"`
	LowStockThreshold *int32         `json:"low_stock_threshold"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	LocaleUsed        string         `json:"locale_used"`
	Name              string         `json:"name"`
}

func (q *Queries) ListProductsForCashier(ctx context.Context, arg ListProductsForCashierParams) ([]ListProductsForCashierRow, error) {
	rows, err := q.db.Query(ctx, listProductsForCashier,
		arg.Locale,
		arg.ShopID,
		arg.IncludeInactive,
		arg.CategoryID,
		arg.Q,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsForCashierRow
	for rows.Next() {
		var i ListProductsForCashierRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.UnitID,
			&i.Slug,
			&i.Sku,
			&i.BasePrice,
			&i.PromoPrice,
			&i.PromoFrom,
			&i.PromoTo,
			&i.IsActive,
			&i.IsFeatured,
			&i.HasVariants,
			&i.DeletedAt,
			&i.LowStockThreshold,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocaleUsed,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsForStaff = `-- name: ListProductsForStaff :many

SELECT
    p.id, p.shop_id, p.category_id, p.unit_id, p.slug, p.sku, p.base_price, p.cost_price, p.promo_price, p.promo_from, p.promo_to, p.is_active, p.is_featured, p.has_variants, p.deleted_at, p.created_at, p.updated_at, p.low_stock_threshold,
    -- COALESCE to '': a product with zero translations must still list, not
    -- fail to scan (LEFT JOIN LATERAL leaves these NULL and sqlc does not
    -- infer that as nullable).
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name
FROM products p
LEFT JOIN LATERAL (
    SELECT pt.locale, pt.name
    FROM product_translations pt
    WHERE pt.product_id = p.id
    ORDER BY
        CASE
            WHEN pt.locale = $1 THEN 0
            WHEN pt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE p.shop_id = $2
    AND p.deleted_at IS NULL
    AND ($3::bool OR p.is_active)
    AND ($4::uuid IS NULL OR p.category_id = $4)
    AND (
        $5::text IS NULL
        OR EXISTS (
            SELECT 1 FROM product_translations spt
            WHERE spt.product_id = p.id
                AND (spt.name ILIKE '%' || $5 || '%' OR spt.name % $5)
        )
    )
    AND (
        $6::timestamptz IS NULL
        OR (p.created_at, p.id) < ($6::timestamptz, $7::uuid)
    )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $8
`

type ListProductsForStaffParams struct {
	Locale          string     `json:"locale"`
	ShopID          uuid.UUID  `json:"shop_id"`
	IncludeInactive bool       `json:"include_inactive"`
	CategoryID      *uuid.UUID `json:"category_id"`
	Q               *string    `json:"q"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	Limit           int32      `json:"limit"`
}

type ListProductsForStaffRow struct {
	ID                uuid.UUID      `json:"id"`
	ShopID            uuid.UUID      `json:"shop_id"`
	CategoryID        *uuid.UUID     `json:"category_id"`
	UnitID            uuid.UUID      `json:"unit_id"`
	Slug              string         `json:"slug"`
	Sku               *string        `json:"sku"`
	BasePrice         pgtype.Numeric `json:"base_price"`
	CostPrice         pgtype.Numeric `json:"cost_price"`
	PromoPrice        pgtype.Numeric `json:"promo_price"`
	PromoFrom         *time.Time     `json:"promo_from"`
	PromoTo           *time.Time     `json:"promo_to"`
	IsActive          bool           `json:"is_active"`
	IsFeatured        bool           `json:"is_featured"`
	HasVariants       bool           `json:"has_variants"`
	DeletedAt         *time.Time     `json:"deleted_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	LowStockThreshold *int32         `json:"low_stock_threshold"`
	LocaleUsed        string         `json:"locale_used"`
	Name              string         `json:"name"`
}

// Three list/get families, one per role, with different column sets rather
// than one query filtered in Go (§ 04-DATA-MODEL.md rule 8, ADR-010):
// ...ForStaff selects cost_price, ...ForCashier and ...Public never do.
//
// Shared filters across all three lists:
//
//	q                 trigram match (ILIKE substring OR pg_trgm similarity)
//	                   against any locale's translated name
//	category_id       optional exact match (sqlc.narg)
//	cursor_created_at/cursor_id  keyset pagination, newest first
//
// ForStaff/ForCashier additionally take include_inactive; Public is always
// active-only and never sees inactive products.
func (q *Queries) ListProductsForStaff(ctx context.Context, arg ListProductsForStaffParams) ([]ListProductsForStaffRow, error) {
	rows, err := q.db.Query(ctx, listProductsForStaff,
		arg.Locale,
		arg.ShopID,
		arg.IncludeInactive,
		arg.CategoryID,
		arg.Q,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsForStaffRow
	for rows.Next() {
		var i ListProductsForStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.UnitID,
			&i.Slug,
			&i.Sku,
			&i.BasePrice,
			&i.CostPrice,
			&i.PromoPrice,
			&i.PromoFrom,
			&i.PromoTo,
			&i.IsActive,
			&i.IsFeatured,
			&i.HasVariants,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LowStockThreshold,
			&i.LocaleUsed,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsPublic = `-- name: ListProductsPublic :many
SELECT
    p.id, p.shop_id, p.category_id, p.unit_id, p.slug, p.sku,
    p.base_price, p.promo_price, p.promo_from, p.promo_to,
    p.is_featured, p.created_at,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name
FROM products p
LEFT JOIN LATERAL (
    SELECT pt.locale, pt.name
    FROM product_translations pt
    WHERE pt.product_id = p.id
    ORDER BY
        CASE
            WHEN pt.locale = $1 THEN 0
            WHEN pt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE p.shop_id = $2
    AND p.deleted_at IS NULL
    AND p.is_active
    AND ($3::uuid IS NULL OR p.category_id = $3)
    AND (
        $4::text IS NULL
        OR EXISTS (
            SELECT 1 FROM product_translations spt
            WHERE spt.product_id = p.id
                AND (spt.name ILIKE '%' || $4 || '%' OR spt.name % $4)
        )
    )
    AND (
        $5::timestamptz IS NULL
        OR (p.created_at, p.id) < ($5::timestamptz, $6::uuid)
    )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $7
`

type ListProductsPublicParams struct {
	Locale          string     `json:"locale"`
	ShopID          uuid.UUID  `json:"shop_id"`
	CategoryID      *uuid.UUID `json:"category_id"`
	Q               *string    `json:"q"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	Limit           int32      `json:"limit"`
}

type ListProductsPublicRow struct {
	ID         uuid.UUID      `json:"id"`
	ShopID     uuid.UUID      `json:"shop_id"`
	CategoryID *uuid.UUID     `json:"category_id"`
	UnitID     uuid.UUID      `json:"unit_id"`
	Slug       string         `json:"slug"`
	Sku        *string        `json:"sku"`
	BasePrice  pgtype.Numeric `json:"base_price"`
	PromoPrice pgtype.Numeric `json:"promo_price"`
	PromoFrom  *time.Time     `json:"promo_from"`
	PromoTo    *time.Time     `json:"promo_to"`
	IsFeatured bool           `json:"is_featured"`
	CreatedAt  time.Time      `json:"created_at"`
	LocaleUsed string         `json:"locale_used"`
	Name       string         `json:"name"`
}

// Active only, always; no include_inactive parameter at all.
func (q *Queries) ListProductsPublic(ctx context.Context, arg ListProductsPublicParams) ([]ListProductsPublicRow, error) {
	rows, err := q.db.Query(ctx, listProductsPublic,
		arg.Locale,
		arg.ShopID,
		arg.CategoryID,
		arg.Q,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsPublicRow
	for rows.Next() {
		var i ListProductsPublicRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.UnitID,
			&i.Slug,
			&i.Sku,
			&i.BasePrice,
			&i.PromoPrice,
			&i.PromoFrom,
			&i.PromoTo,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.LocaleUsed,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicProducts = `-- name: ListPublicProducts :many

WITH RECURSIVE matched_categories AS (
    SELECT id, 1 AS depth FROM categories
    WHERE shop_id = $2 AND deleted_at IS NULL AND is_active
        AND $3::text IS NOT NULL AND slug = $3

    UNION ALL

    SELECT ch.id, m.depth + 1
    FROM categories ch
    JOIN matched_categories m ON ch.parent_id = m.id
    WHERE ch.shop_id = $2 AND ch.deleted_at IS NULL AND ch.is_active
        AND m.depth < 4
)
SELECT
    p.id, p.shop_id, p.category_id, p.unit_id, p.slug, p.sku,
    p.base_price, p.promo_price, p.promo_from, p.promo_to,
    p.is_featured, p.created_at,
    c.slug AS category_slug,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS name
FROM products p
LEFT JOIN categories c ON c.id = p.category_id AND c.shop_id = p.shop_id
LEFT JOIN LATERAL (
    SELECT pt.locale, pt.name
    FROM product_translations pt
    WHERE pt.product_id = p.id
    ORDER BY
        CASE
            WHEN pt.locale = $1 THEN 0
            WHEN pt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE p.shop_id = $2
    AND p.deleted_at IS NULL
    AND p.is_active
    AND (p.category_id IS NULL OR (c.deleted_at IS NULL AND c.is_active))
    AND ($3::text IS NULL OR p.category_id IN (SELECT id FROM matched_categories))
    AND ($4::bool IS NULL OR p.is_featured = $4)
    AND (
        $5::text IS NULL
        OR EXISTS (
            SELECT 1 FROM product_translations spt
            WHERE spt.product_id = p.id
                AND (spt.name ILIKE '%' || $5 || '%' OR spt.name % $5)
        )
    )
    AND (
        $6::timestamptz IS NULL
        OR (p.created_at, p.id) < ($6::timestamptz, $7::uuid)
    )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $8
`

type ListPublicProductsParams struct {
	Locale          string     `json:"locale"`
	ShopID          uuid.UUID  `json:"shop_id"`
	CategorySlug    *string    `json:"category_slug"`
	Featured        *bool      `json:"featured"`
	Q               *string    `json:"q"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	Limit           int32      `json:"limit"`
}

type ListPublicProductsRow struct {
	ID           uuid.UUID      `json:"id"`
	ShopID       uuid.UUID      `json:"shop_id"`
	CategoryID   *uuid.UUID     `json:"category_id"`
	UnitID       uuid.UUID      `json:"unit_id"`
	Slug         string         `json:"slug"`
	Sku          *string        `json:"sku"`
	BasePrice    pgtype.Numeric `json:"base_price"`
	PromoPrice   pgtype.Numeric `json:"promo_price"`
	PromoFrom    *time.Time     `json:"promo_from"`
	PromoTo      *time.Time     `json:"promo_to"`
	IsFeatured   bool           `json:"is_featured"`
	CreatedAt    time.Time      `json:"created_at"`
	CategorySlug *string        `json:"category_slug"`
	LocaleUsed   string         `json:"locale_used"`
	Name         string         `json:"name"`
}

// Phase 6 public catalogue (docs/06-ROADMAP.md Phase 6, D-99, D-103). Both
// queries below LEFT JOIN categories (orchestrator ruling, O-row TBD): a
// product with no category (category_id IS NULL) still belongs in the
// public catalogue — only a product whose category exists and is
// soft-deleted/inactive is hidden. category_slug is therefore nullable:
// NULL when the product has no category at all. When category_slug is
// given as a filter, an uncategorized product's c.slug is NULL and never
// equals the filter, so it is excluded from a category-filtered list, and
// the visibility condition below still requires that category to be
// active — a category-filtered list never surfaces a product whose
// matching category is inactive. Neither embeds a cover image: the
// handler reuses ListCoverImagesForProducts (D-83, same one-query-per-page
// pattern ListProducts already uses) against this query's page of product
// ids instead of duplicating that selection logic (flagged cover else
// first by position) in another LATERAL here. GetPublicProductBySlug's
// own LATERAL (below) resolves name+description+locale in the same
// pass as the product row (T3 review round 1: previously the handler
// discarded that LATERAL's name/locale_used and ran a second
// ListProductTranslations query, redoing the same fallback in Go for
// name+description together — now description is selected alongside
// name so the LATERAL is the single source, no second query). Variants
// and images for the product-detail page still reuse
// ListVariantsForCashier (filtered to is_active in the handler — its
// column set already excludes cost_override, the only thing rule 8
// requires a separate query for) and ListProductImages.
// T7: `category_slug` matches the named category AND every one of its
// active, non-deleted descendants (matched_categories, a recursive walk
// down parent_id from the one category named by slug) — a parent slug
// like "erkaklar" now lists its children's products too, not just
// (usually zero) products assigned directly to the parent. When
// category_slug is NULL the base case's own IS NOT NULL guard makes
// matched_categories empty and the OR short-circuits, same as before
// T7. A product whose direct category is inactive is still excluded
// entirely by the unrelated (p.category_id IS NULL OR (c.deleted_at IS
// NULL AND c.is_active)) line below (O-22) — matched_categories only
// widens which *active* categories count as a match, it does not loosen
// that visibility rule.
//
// T7 review round 1, MAJOR 1: matched_categories carries a depth column
// and stops recursing once depth reaches 4 (one past the schema's own
// depth <= 3 rule, 04-DATA-MODEL.md) — this endpoint has no auth and
// must not trust catalog.Service's own depth guard alone; a parent_id
// cycle from a manual DB edit would otherwise recurse forever (same
// reasoning as ListPublicCategories' descendants/paths CTEs).
func (q *Queries) ListPublicProducts(ctx context.Context, arg ListPublicProductsParams) ([]ListPublicProductsRow, error) {
	rows, err := q.db.Query(ctx, listPublicProducts,
		arg.Locale,
		arg.ShopID,
		arg.CategorySlug,
		arg.Featured,
		arg.Q,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicProductsRow
	for rows.Next() {
		var i ListPublicProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.UnitID,
			&i.Slug,
			&i.Sku,
			&i.BasePrice,
			&i.PromoPrice,
			&i.PromoFrom,
			&i.PromoTo,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.CategorySlug,
			&i.LocaleUsed,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductHasVariants = `-- name: SetProductHasVariants :exec
UPDATE products
SET has_variants = $3, updated_at = now()
WHERE shop_id = $1 AND id = $2
`

type SetProductHasVariantsParams struct {
	ShopID      uuid.UUID `json:"shop_id"`
	ID          uuid.UUID `json:"id"`
	HasVariants bool      `json:"has_variants"`
}

// Flipped by the service once the second variant is added (or back once
// only the default variant remains) — never part of the general patch.
func (q *Queries) SetProductHasVariants(ctx context.Context, arg SetProductHasVariantsParams) error {
	_, err := q.db.Exec(ctx, setProductHasVariants, arg.ShopID, arg.ID, arg.HasVariants)
	return err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products
SET deleted_at = now(), updated_at = now()
WHERE shop_id = $1 AND id = $2
`

type SoftDeleteProductParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, arg.ShopID, arg.ID)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    category_id = CASE WHEN $1::bool THEN NULL ELSE COALESCE($2, category_id) END,
    unit_id = COALESCE($3, unit_id),
    slug = COALESCE($4, slug),
    sku = CASE WHEN $5::bool THEN NULL ELSE COALESCE($6, sku) END,
    base_price = COALESCE($7, base_price),
    cost_price = CASE WHEN $8::bool THEN NULL ELSE COALESCE($9, cost_price) END,
    promo_price = CASE WHEN $10::bool THEN NULL ELSE COALESCE($11, promo_price) END,
    promo_from = CASE WHEN $10::bool THEN NULL ELSE COALESCE($12, promo_from) END,
    promo_to = CASE WHEN $10::bool THEN NULL ELSE COALESCE($13, promo_to) END,
    is_active = COALESCE($14, is_active),
    is_featured = COALESCE($15, is_featured),
    low_stock_threshold = CASE WHEN $16::bool THEN NULL ELSE COALESCE($17, low_stock_threshold) END,
    updated_at = now()
WHERE shop_id = $18 AND id = $19 AND deleted_at IS NULL
RETURNING id, shop_id, category_id, unit_id, slug, sku, base_price, cost_price, promo_price, promo_from, promo_to, is_active, is_featured, has_variants, deleted_at, created_at, updated_at, low_stock_threshold
`

type UpdateProductParams struct {
	ClearCategory          bool           `json:"clear_category"`
	CategoryID             *uuid.UUID     `json:"category_id"`
	UnitID                 *uuid.UUID     `json:"unit_id"`
	Slug                   *string        `json:"slug"`
	ClearSku               bool           `json:"clear_sku"`
	Sku                    *string        `json:"sku"`
	BasePrice              pgtype.Numeric `json:"base_price"`
	ClearCost              bool           `json:"clear_cost"`
	CostPrice              pgtype.Numeric `json:"cost_price"`
	ClearPromo             bool           `json:"clear_promo"`
	PromoPrice             pgtype.Numeric `json:"promo_price"`
	PromoFrom              *time.Time     `json:"promo_from"`
	PromoTo                *time.Time     `json:"promo_to"`
	IsActive               *bool          `json:"is_active"`
	IsFeatured             *bool          `json:"is_featured"`
	ClearLowStockThreshold bool           `json:"clear_low_stock_threshold"`
	LowStockThreshold      *int32         `json:"low_stock_threshold"`
	ShopID                 uuid.UUID      `json:"shop_id"`
	ID                     uuid.UUID      `json:"id"`
}

// Patch with explicit clear flags for nullable fields: COALESCE cannot
// express "set to NULL", so clear_category/clear_sku/clear_cost/
// clear_low_stock_threshold clear their column outright, and clear_promo
// clears promo_price/promo_from/promo_to together (they are one concept).
// has_variants is not editable here — see SetProductHasVariants, a
// single-purpose statement like ClearUserPhone.
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ClearCategory,
		arg.CategoryID,
		arg.UnitID,
		arg.Slug,
		arg.ClearSku,
		arg.Sku,
		arg.BasePrice,
		arg.ClearCost,
		arg.CostPrice,
		arg.ClearPromo,
		arg.PromoPrice,
		arg.PromoFrom,
		arg.PromoTo,
		arg.IsActive,
		arg.IsFeatured,
		arg.ClearLowStockThreshold,
		arg.LowStockThreshold,
		arg.ShopID,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.UnitID,
		&i.Slug,
		&i.Sku,
		&i.BasePrice,
		&i.CostPrice,
		&i.PromoPrice,
		&i.PromoFrom,
		&i.PromoTo,
		&i.IsActive,
		&i.IsFeatured,
		&i.HasVariants,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LowStockThreshold,
	)
	return i, err
}

const upsertProductTranslation = `-- name: UpsertProductTranslation :exec
INSERT INTO product_translations (product_id, locale, name, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (product_id, locale) DO UPDATE
SET name = EXCLUDED.name, description = EXCLUDED.description
`

type UpsertProductTranslationParams struct {
	ProductID   uuid.UUID `json:"product_id"`
	Locale      string    `json:"locale"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) UpsertProductTranslation(ctx context.Context, arg UpsertProductTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertProductTranslation,
		arg.ProductID,
		arg.Locale,
		arg.Name,
		arg.Description,
	)
	return err
}
