// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchases.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchases (
    id, shop_id, supplier_id, location_id, number,
    supplier_invoice_no, note, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, shop_id, supplier_id, location_id, number, supplier_invoice_no, status, received_at, note, total_cost, created_by, cancelled_at, created_at, updated_at
`

type CreatePurchaseParams struct {
	ID                uuid.UUID  `json:"id"`
	ShopID            uuid.UUID  `json:"shop_id"`
	SupplierID        uuid.UUID  `json:"supplier_id"`
	LocationID        uuid.UUID  `json:"location_id"`
	Number            string     `json:"number"`
	SupplierInvoiceNo *string    `json:"supplier_invoice_no"`
	Note              *string    `json:"note"`
	CreatedBy         *uuid.UUID `json:"created_by"`
}

// number is always server-generated by the service from
// NextPurchaseNumber, never client-supplied (D-45, hard rule 8).
func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, createPurchase,
		arg.ID,
		arg.ShopID,
		arg.SupplierID,
		arg.LocationID,
		arg.Number,
		arg.SupplierInvoiceNo,
		arg.Note,
		arg.CreatedBy,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.SupplierID,
		&i.LocationID,
		&i.Number,
		&i.SupplierInvoiceNo,
		&i.Status,
		&i.ReceivedAt,
		&i.Note,
		&i.TotalCost,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPurchaseItem = `-- name: CreatePurchaseItem :one
INSERT INTO purchase_items (id, shop_id, purchase_id, variant_id, qty, unit_cost, line_total)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, shop_id, purchase_id, variant_id, qty, unit_cost, line_total, created_at, updated_at
`

type CreatePurchaseItemParams struct {
	ID         uuid.UUID      `json:"id"`
	ShopID     uuid.UUID      `json:"shop_id"`
	PurchaseID uuid.UUID      `json:"purchase_id"`
	VariantID  uuid.UUID      `json:"variant_id"`
	Qty        pgtype.Numeric `json:"qty"`
	UnitCost   pgtype.Numeric `json:"unit_cost"`
	LineTotal  pgtype.Numeric `json:"line_total"`
}

func (q *Queries) CreatePurchaseItem(ctx context.Context, arg CreatePurchaseItemParams) (PurchaseItem, error) {
	row := q.db.QueryRow(ctx, createPurchaseItem,
		arg.ID,
		arg.ShopID,
		arg.PurchaseID,
		arg.VariantID,
		arg.Qty,
		arg.UnitCost,
		arg.LineTotal,
	)
	var i PurchaseItem
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.PurchaseID,
		&i.VariantID,
		&i.Qty,
		&i.UnitCost,
		&i.LineTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePurchaseItems = `-- name: DeletePurchaseItems :execrows
DELETE FROM purchase_items
USING purchases
WHERE purchase_items.purchase_id = purchases.id
    AND purchase_items.shop_id = $1
    AND purchase_items.purchase_id = $2
    AND purchases.status = 'draft'
`

type DeletePurchaseItemsParams struct {
	ShopID     uuid.UUID `json:"shop_id"`
	PurchaseID uuid.UUID `json:"purchase_id"`
}

// Join rows, hard-deleted (§ 04-DATA-MODEL.md rule 7); used by the service
// to replace a draft's item list (delete then re-CreatePurchaseItem). The
// USING join guards status = 'draft' at the SQL level too (defense in
// depth alongside the service's own GetPurchaseForUpdate check): on a
// received/cancelled purchase this affects 0 rows, same signal shape as
// UpdatePurchaseHeader/SetPurchaseReceived/SetPurchaseCancelled. The
// affected-row count is not on its own a reliable "was it draft" check —
// a draft with no items yet also affects 0 rows — the service still reads
// status from GetPurchaseForUpdate first.
func (q *Queries) DeletePurchaseItems(ctx context.Context, arg DeletePurchaseItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePurchaseItems, arg.ShopID, arg.PurchaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPurchase = `-- name: GetPurchase :one
SELECT id, shop_id, supplier_id, location_id, number, supplier_invoice_no, status, received_at, note, total_cost, created_by, cancelled_at, created_at, updated_at FROM purchases
WHERE shop_id = $1 AND id = $2
`

type GetPurchaseParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetPurchase(ctx context.Context, arg GetPurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, getPurchase, arg.ShopID, arg.ID)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.SupplierID,
		&i.LocationID,
		&i.Number,
		&i.SupplierInvoiceNo,
		&i.Status,
		&i.ReceivedAt,
		&i.Note,
		&i.TotalCost,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPurchaseForUpdate = `-- name: GetPurchaseForUpdate :one
SELECT id, shop_id, supplier_id, location_id, number, supplier_invoice_no, status, received_at, note, total_cost, created_by, cancelled_at, created_at, updated_at FROM purchases
WHERE shop_id = $1 AND id = $2
FOR UPDATE
`

type GetPurchaseForUpdateParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

// Locks the header row before a draft-only mutation (update header,
// replace items, receive, cancel) so two concurrent requests cannot both
// observe status = 'draft' and race past each other.
func (q *Queries) GetPurchaseForUpdate(ctx context.Context, arg GetPurchaseForUpdateParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, getPurchaseForUpdate, arg.ShopID, arg.ID)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.SupplierID,
		&i.LocationID,
		&i.Number,
		&i.SupplierInvoiceNo,
		&i.Status,
		&i.ReceivedAt,
		&i.Note,
		&i.TotalCost,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPurchaseItems = `-- name: ListPurchaseItems :many
SELECT id, shop_id, purchase_id, variant_id, qty, unit_cost, line_total, created_at, updated_at FROM purchase_items
WHERE shop_id = $1 AND purchase_id = $2
ORDER BY created_at, id
`

type ListPurchaseItemsParams struct {
	ShopID     uuid.UUID `json:"shop_id"`
	PurchaseID uuid.UUID `json:"purchase_id"`
}

// `, id` tiebreaker for determinism, same reasoning as
// ListVariantsForStaff (created_at alone can tie within one transaction).
func (q *Queries) ListPurchaseItems(ctx context.Context, arg ListPurchaseItemsParams) ([]PurchaseItem, error) {
	rows, err := q.db.Query(ctx, listPurchaseItems, arg.ShopID, arg.PurchaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseItem
	for rows.Next() {
		var i PurchaseItem
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.PurchaseID,
			&i.VariantID,
			&i.Qty,
			&i.UnitCost,
			&i.LineTotal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseItemsWithLabels = `-- name: ListPurchaseItemsWithLabels :many
SELECT
    pi.id, pi.purchase_id, pi.variant_id, pi.qty, pi.unit_cost, pi.line_total, pi.created_at,
    v.sku AS variant_sku,
    v.attributes AS variant_attributes,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS product_name
FROM purchase_items pi
JOIN product_variants v ON v.id = pi.variant_id AND v.shop_id = pi.shop_id
JOIN products p ON p.id = v.product_id AND p.shop_id = pi.shop_id
LEFT JOIN LATERAL (
    SELECT pt.locale, pt.name
    FROM product_translations pt
    WHERE pt.product_id = p.id
    ORDER BY
        CASE
            WHEN pt.locale = $1 THEN 0
            WHEN pt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE pi.shop_id = $2 AND pi.purchase_id = $3
ORDER BY pi.created_at, pi.id
`

type ListPurchaseItemsWithLabelsParams struct {
	Locale     string    `json:"locale"`
	ShopID     uuid.UUID `json:"shop_id"`
	PurchaseID uuid.UUID `json:"purchase_id"`
}

type ListPurchaseItemsWithLabelsRow struct {
	ID                uuid.UUID       `json:"id"`
	PurchaseID        uuid.UUID       `json:"purchase_id"`
	VariantID         uuid.UUID       `json:"variant_id"`
	Qty               pgtype.Numeric  `json:"qty"`
	UnitCost          pgtype.Numeric  `json:"unit_cost"`
	LineTotal         pgtype.Numeric  `json:"line_total"`
	CreatedAt         time.Time       `json:"created_at"`
	VariantSku        *string         `json:"variant_sku"`
	VariantAttributes json.RawMessage `json:"variant_attributes"`
	LocaleUsed        string          `json:"locale_used"`
	ProductName       string          `json:"product_name"`
}

// Joins each purchase_items row to its variant and product for the
// response-only productName/variantLabel/sku fields
// (contracts/openapi.yaml's PurchaseItem, T4): variantLabel itself is
// built in Go from variant_sku/variant_attributes plus
// attribute_definitions' sort order (mirrors
// admin/src/catalog/variants.ts's own variantLabel), not computed in SQL.
// productName uses the same locale-fallback (requested -> 'uz' -> any,
// ADR-012) as ListProductsForStaff. v.shop_id/p.shop_id are joined
// explicitly, not just pi.shop_id, so a row can never resolve through
// another shop's variant/product even though every id here was already
// validated at CreatePurchase time (hard rule 1, defense in depth).
func (q *Queries) ListPurchaseItemsWithLabels(ctx context.Context, arg ListPurchaseItemsWithLabelsParams) ([]ListPurchaseItemsWithLabelsRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseItemsWithLabels, arg.Locale, arg.ShopID, arg.PurchaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchaseItemsWithLabelsRow
	for rows.Next() {
		var i ListPurchaseItemsWithLabelsRow
		if err := rows.Scan(
			&i.ID,
			&i.PurchaseID,
			&i.VariantID,
			&i.Qty,
			&i.UnitCost,
			&i.LineTotal,
			&i.CreatedAt,
			&i.VariantSku,
			&i.VariantAttributes,
			&i.LocaleUsed,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchases = `-- name: ListPurchases :many
SELECT id, shop_id, supplier_id, location_id, number, supplier_invoice_no, status, received_at, note, total_cost, created_by, cancelled_at, created_at, updated_at FROM purchases
WHERE shop_id = $1
    AND ($2::purchase_status IS NULL OR status = $2)
    AND ($3::uuid IS NULL OR supplier_id = $3)
    AND (
        $4::timestamptz IS NULL
        OR (created_at, id) < ($4::timestamptz, $5::uuid)
    )
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListPurchasesParams struct {
	ShopID          uuid.UUID       `json:"shop_id"`
	Status          *PurchaseStatus `json:"status"`
	SupplierID      *uuid.UUID      `json:"supplier_id"`
	CursorCreatedAt *time.Time      `json:"cursor_created_at"`
	CursorID        *uuid.UUID      `json:"cursor_id"`
	Limit           int32           `json:"limit"`
}

// Keyset pagination on (created_at, id), newest first. status/supplier_id
// are optional exact-match filters (sqlc.narg).
func (q *Queries) ListPurchases(ctx context.Context, arg ListPurchasesParams) ([]Purchase, error) {
	rows, err := q.db.Query(ctx, listPurchases,
		arg.ShopID,
		arg.Status,
		arg.SupplierID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Purchase
	for rows.Next() {
		var i Purchase
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.SupplierID,
			&i.LocationID,
			&i.Number,
			&i.SupplierInvoiceNo,
			&i.Status,
			&i.ReceivedAt,
			&i.Note,
			&i.TotalCost,
			&i.CreatedBy,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPurchaseNumber = `-- name: NextPurchaseNumber :one
UPDATE shops
SET next_purchase_number = next_purchase_number + 1
WHERE id = $1
RETURNING (next_purchase_number - 1)::bigint
`

// Row-locking increment, same pattern as sales.next_sale_number (D-45):
// the UPDATE itself takes the row lock, so no separate SELECT ... FOR
// UPDATE is needed. Returns the number this purchase should use (before
// the increment); the service formats it as "P-%06d" (D-45) and passes
// the formatted text into CreatePurchase.
func (q *Queries) NextPurchaseNumber(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextPurchaseNumber, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setPurchaseCancelled = `-- name: SetPurchaseCancelled :one
UPDATE purchases
SET status = 'cancelled', cancelled_at = now(), updated_at = now()
WHERE shop_id = $1 AND id = $2 AND status <> 'cancelled'
RETURNING id, shop_id, supplier_id, location_id, number, supplier_invoice_no, status, received_at, note, total_cost, created_by, cancelled_at, created_at, updated_at
`

type SetPurchaseCancelledParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

// Cancellable from 'draft' or 'received'; not from 'cancelled' again (the
// WHERE clause maps a second cancel to PURCHASE_ALREADY_CANCELLED in the
// service). Cancelling a 'received' purchase's reversing stock movements
// are written separately by stock.Service.Move before/after this call in
// the same transaction.
func (q *Queries) SetPurchaseCancelled(ctx context.Context, arg SetPurchaseCancelledParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, setPurchaseCancelled, arg.ShopID, arg.ID)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.SupplierID,
		&i.LocationID,
		&i.Number,
		&i.SupplierInvoiceNo,
		&i.Status,
		&i.ReceivedAt,
		&i.Note,
		&i.TotalCost,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPurchaseReceived = `-- name: SetPurchaseReceived :one
UPDATE purchases
SET status = 'received', received_at = now(), total_cost = $3, updated_at = now()
WHERE shop_id = $1 AND id = $2 AND status = 'draft'
RETURNING id, shop_id, supplier_id, location_id, number, supplier_invoice_no, status, received_at, note, total_cost, created_by, cancelled_at, created_at, updated_at
`

type SetPurchaseReceivedParams struct {
	ShopID    uuid.UUID      `json:"shop_id"`
	ID        uuid.UUID      `json:"id"`
	TotalCost pgtype.Numeric `json:"total_cost"`
}

// Only a 'draft' purchase can be received; the WHERE clause is the guard,
// same PURCHASE_NOT_DRAFT/PURCHASE_ALREADY_RECEIVED mapping as
// UpdatePurchaseHeader. total_cost is computed server-side from the items
// (never trust a client value, hard rule 8).
func (q *Queries) SetPurchaseReceived(ctx context.Context, arg SetPurchaseReceivedParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, setPurchaseReceived, arg.ShopID, arg.ID, arg.TotalCost)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.SupplierID,
		&i.LocationID,
		&i.Number,
		&i.SupplierInvoiceNo,
		&i.Status,
		&i.ReceivedAt,
		&i.Note,
		&i.TotalCost,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePurchaseHeader = `-- name: UpdatePurchaseHeader :one
UPDATE purchases
SET
    supplier_id = COALESCE($1, supplier_id),
    location_id = COALESCE($2, location_id),
    supplier_invoice_no = CASE WHEN $3::bool THEN NULL ELSE COALESCE($4, supplier_invoice_no) END,
    note = CASE WHEN $5::bool THEN NULL ELSE COALESCE($6, note) END,
    updated_at = now()
WHERE shop_id = $7 AND id = $8 AND status = 'draft'
RETURNING id, shop_id, supplier_id, location_id, number, supplier_invoice_no, status, received_at, note, total_cost, created_by, cancelled_at, created_at, updated_at
`

type UpdatePurchaseHeaderParams struct {
	SupplierID             *uuid.UUID `json:"supplier_id"`
	LocationID             *uuid.UUID `json:"location_id"`
	ClearSupplierInvoiceNo bool       `json:"clear_supplier_invoice_no"`
	SupplierInvoiceNo      *string    `json:"supplier_invoice_no"`
	ClearNote              bool       `json:"clear_note"`
	Note                   *string    `json:"note"`
	ShopID                 uuid.UUID  `json:"shop_id"`
	ID                     uuid.UUID  `json:"id"`
}

// Patch, allowed only while status = 'draft' (the WHERE clause is the
// enforcement; the service maps zero rows returned to
// PURCHASE_NOT_DRAFT/NOT_FOUND). supplier_invoice_no/note are nullable
// (D-35): explicit clear flags, same shape as UpdateSupplier.
func (q *Queries) UpdatePurchaseHeader(ctx context.Context, arg UpdatePurchaseHeaderParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, updatePurchaseHeader,
		arg.SupplierID,
		arg.LocationID,
		arg.ClearSupplierInvoiceNo,
		arg.SupplierInvoiceNo,
		arg.ClearNote,
		arg.Note,
		arg.ShopID,
		arg.ID,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.SupplierID,
		&i.LocationID,
		&i.Number,
		&i.SupplierInvoiceNo,
		&i.Status,
		&i.ReceivedAt,
		&i.Note,
		&i.TotalCost,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
