// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const salesByProduct = `-- name: SalesByProduct :many
WITH lines AS (
    SELECT
        i.id AS item_id,
        i.sale_id,
        p.id AS product_id,
        COALESCE(t.name, '') AS product_name,
        i.qty, i.unit_cost, i.line_total, s.kind, s.subtotal, s.discount_amount,
        row_number() OVER (PARTITION BY i.sale_id ORDER BY i.id) AS rn,
        count(*) OVER (PARTITION BY i.sale_id) AS line_count,
        -- 0 for a return leg or a zero-subtotal sale (nothing to
        -- allocate); never divides by zero.
        CASE
            WHEN s.kind = 'sale' AND s.subtotal <> 0
                THEN ROUND(i.line_total * s.discount_amount / s.subtotal, 2)
            ELSE 0
        END AS raw_share
    FROM sale_items i
    JOIN sales s ON s.id = i.sale_id AND s.shop_id = i.shop_id
    JOIN product_variants v ON v.id = i.variant_id AND v.shop_id = i.shop_id
    JOIN products p ON p.id = v.product_id AND p.shop_id = i.shop_id
    LEFT JOIN LATERAL (
        SELECT pt.name
        FROM product_translations pt
        WHERE pt.product_id = p.id
        ORDER BY
            CASE
                WHEN pt.locale = $4 THEN 0
                WHEN pt.locale = 'uz' THEN 1
                ELSE 2
            END
        LIMIT 1
    ) t ON true
    WHERE i.shop_id = $5
        AND s.status = 'completed'
        AND s.completed_at >= $6
        AND s.completed_at < $7
        AND ($8::uuid IS NULL OR s.location_id = $8)
),
items AS (
    SELECT
        product_id, product_name, qty, unit_cost, kind,
        CASE
            WHEN kind <> 'sale' THEN line_total
            WHEN subtotal = 0 THEN line_total
            WHEN rn = line_count THEN
                line_total - (discount_amount - COALESCE(
                    SUM(raw_share) OVER (
                        PARTITION BY sale_id ORDER BY item_id
                        ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
                    ), 0
                ))
            ELSE line_total - raw_share
        END AS net_line_revenue
    FROM lines
),
agg AS (
    SELECT
        product_id,
        max(product_name)::text AS product_name,
        COALESCE(sum(qty) FILTER (WHERE kind = 'sale'), 0)::numeric(12,3) AS qty_sold,
        COALESCE(sum(qty) FILTER (WHERE kind = 'return'), 0)::numeric(12,3) AS qty_returned,
        (
            COALESCE(sum(net_line_revenue) FILTER (WHERE kind = 'sale'), 0)
            - COALESCE(sum(net_line_revenue) FILTER (WHERE kind = 'return'), 0)
        )::numeric(14,2) AS revenue,
        (
            COALESCE(sum(qty * unit_cost) FILTER (WHERE kind = 'sale'), 0)
            - COALESCE(sum(qty * unit_cost) FILTER (WHERE kind = 'return'), 0)
        )::numeric(14,2) AS cost
    FROM items
    GROUP BY product_id
)
SELECT product_id, product_name, qty_sold, qty_returned, revenue, cost
FROM agg
WHERE (
    $1::numeric IS NULL
    OR (revenue, product_id) < ($1::numeric, $2::uuid)
)
ORDER BY revenue DESC, product_id DESC
LIMIT $3
`

type SalesByProductParams struct {
	CursorRevenue   pgtype.Numeric `json:"cursor_revenue"`
	CursorProductID *uuid.UUID     `json:"cursor_product_id"`
	Limit           int32          `json:"limit"`
	Locale          string         `json:"locale"`
	ShopID          uuid.UUID      `json:"shop_id"`
	From            time.Time      `json:"from"`
	To              time.Time      `json:"to"`
	LocationID      *uuid.UUID     `json:"location_id"`
}

type SalesByProductRow struct {
	ProductID   uuid.UUID      `json:"product_id"`
	ProductName string         `json:"product_name"`
	QtySold     pgtype.Numeric `json:"qty_sold"`
	QtyReturned pgtype.Numeric `json:"qty_returned"`
	Revenue     pgtype.Numeric `json:"revenue"`
	Cost        pgtype.Numeric `json:"cost"`
}

// Staff only (unit_cost, § 04-DATA-MODEL.md rule 8). Groups sale_items by
// product over [from, to), computing quantity sold/returned and net
// revenue/cost (sold minus returned).
//
// net_line_revenue nets each sale-leg line's own share of its sale's
// discount_amount so the sum reconciles exactly (owner ruling amending
// D-64): every line except the last one (in sale_items.id order — uuid
// v7, so insertion order) gets round(line_total * discount_amount /
// subtotal, 2); the last line gets whatever is left over
// (discount_amount minus the sum of the other lines' rounded shares),
// which absorbs the rounding remainder so the per-line shares always add
// up to exactly discount_amount, never a cent more or less. "raw" below
// computes each line's row_number()/count() and its own rounded share
// (raw_share) within its sale (partition by sale_id, order by item_id);
// "items" then picks, per line, either that share (not the last line) or
// discount_amount minus the running sum of every other line's share (the
// last line — the window frame UNBOUNDED PRECEDING TO 1 PRECEDING is
// exactly "every row before this one", which for the last row in the
// partition is every other row). subtotal = 0 is guarded explicitly (a
// line must never be dropped, not divided by zero); the sales service
// applies this same allocation for D-61 refunds, this query only mirrors
// it for the report — a return-leg line's line_total is already net (the
// service computed it that way), so it is used as-is, no share to
// compute. Keyset pagination on (revenue, product_id), both DESC — same
// tuple-comparison shape as every other cursor here, just with a
// computed sort key instead of a column, which is why the ordering and
// the aggregation are split into their own CTEs (a WHERE clause cannot
// filter on an aggregate directly).
func (q *Queries) SalesByProduct(ctx context.Context, arg SalesByProductParams) ([]SalesByProductRow, error) {
	rows, err := q.db.Query(ctx, salesByProduct,
		arg.CursorRevenue,
		arg.CursorProductID,
		arg.Limit,
		arg.Locale,
		arg.ShopID,
		arg.From,
		arg.To,
		arg.LocationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesByProductRow
	for rows.Next() {
		var i SalesByProductRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.QtySold,
			&i.QtyReturned,
			&i.Revenue,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesSummaryForCashier = `-- name: SalesSummaryForCashier :one
WITH sf AS (
    SELECT id, shop_id, number, kind, status, location_id, customer_id, cashier_id, original_sale_id, subtotal, discount_amount, discount_reason, total, note, completed_at, voided_at, voided_by, void_reason, created_at FROM sales
    WHERE shop_id = $1
        AND status = 'completed'
        AND completed_at >= $2
        AND completed_at < $3
        AND ($4::uuid IS NULL OR location_id = $4)
        AND ($5::uuid IS NULL OR cashier_id = $5)
)
SELECT
    count(*) FILTER (WHERE kind = 'sale')::bigint AS sales_count,
    count(*) FILTER (WHERE kind = 'return')::bigint AS returns_count,
    COALESCE(sum(total) FILTER (WHERE kind = 'sale'), 0)::numeric(14,2) AS revenue,
    COALESCE(sum(total) FILTER (WHERE kind = 'return'), 0)::numeric(14,2) AS refunds,
    COALESCE(sum(discount_amount) FILTER (WHERE kind = 'sale'), 0)::numeric(14,2) AS discounts
FROM sf
`

type SalesSummaryForCashierParams struct {
	ShopID     uuid.UUID  `json:"shop_id"`
	From       time.Time  `json:"from"`
	To         time.Time  `json:"to"`
	LocationID *uuid.UUID `json:"location_id"`
	CashierID  *uuid.UUID `json:"cashier_id"`
}

type SalesSummaryForCashierRow struct {
	SalesCount   int64          `json:"sales_count"`
	ReturnsCount int64          `json:"returns_count"`
	Revenue      pgtype.Numeric `json:"revenue"`
	Refunds      pgtype.Numeric `json:"refunds"`
	Discounts    pgtype.Numeric `json:"discounts"`
}

// Same filters as SalesSummaryForStaff, no cost column (§ 04-DATA-MODEL.md
// rule 8, D-63) — the permission matrix's "own-day sales only" for a
// cashier is enforced by the service passing from/to and cashier_id, not
// by this query.
func (q *Queries) SalesSummaryForCashier(ctx context.Context, arg SalesSummaryForCashierParams) (SalesSummaryForCashierRow, error) {
	row := q.db.QueryRow(ctx, salesSummaryForCashier,
		arg.ShopID,
		arg.From,
		arg.To,
		arg.LocationID,
		arg.CashierID,
	)
	var i SalesSummaryForCashierRow
	err := row.Scan(
		&i.SalesCount,
		&i.ReturnsCount,
		&i.Revenue,
		&i.Refunds,
		&i.Discounts,
	)
	return i, err
}

const salesSummaryForStaff = `-- name: SalesSummaryForStaff :one
WITH sf AS (
    SELECT id, shop_id, number, kind, status, location_id, customer_id, cashier_id, original_sale_id, subtotal, discount_amount, discount_reason, total, note, completed_at, voided_at, voided_by, void_reason, created_at FROM sales sales_row
    WHERE sales_row.shop_id = $1
        AND sales_row.status = 'completed'
        AND sales_row.completed_at >= $2
        AND sales_row.completed_at < $3
        AND ($4::uuid IS NULL OR sales_row.location_id = $4)
        AND ($5::uuid IS NULL OR sales_row.cashier_id = $5)
),
sale_cost AS (
    SELECT sf.kind, sum(i.qty * i.unit_cost) AS total_cost
    FROM sf
    JOIN sale_items i ON i.sale_id = sf.id AND i.shop_id = sf.shop_id
    GROUP BY sf.kind
)
SELECT
    count(*) FILTER (WHERE kind = 'sale')::bigint AS sales_count,
    count(*) FILTER (WHERE kind = 'return')::bigint AS returns_count,
    COALESCE(sum(total) FILTER (WHERE kind = 'sale'), 0)::numeric(14,2) AS revenue,
    COALESCE(sum(total) FILTER (WHERE kind = 'return'), 0)::numeric(14,2) AS refunds,
    -- Sale leg only (D-64): a fully returned discounted sale still reports
    -- the discount it gave at checkout, it is not netted back out here —
    -- SalesByProduct's per-line net revenue is what already reflects the
    -- return's effect on discount-adjusted revenue.
    COALESCE(sum(discount_amount) FILTER (WHERE kind = 'sale'), 0)::numeric(14,2) AS discounts,
    (
        COALESCE((SELECT total_cost FROM sale_cost WHERE kind = 'sale'), 0)
        - COALESCE((SELECT total_cost FROM sale_cost WHERE kind = 'return'), 0)
    )::numeric(14,2) AS cost
FROM sf
`

type SalesSummaryForStaffParams struct {
	ShopID     uuid.UUID  `json:"shop_id"`
	From       time.Time  `json:"from"`
	To         time.Time  `json:"to"`
	LocationID *uuid.UUID `json:"location_id"`
	CashierID  *uuid.UUID `json:"cashier_id"`
}

type SalesSummaryForStaffRow struct {
	SalesCount   int64          `json:"sales_count"`
	ReturnsCount int64          `json:"returns_count"`
	Revenue      pgtype.Numeric `json:"revenue"`
	Refunds      pgtype.Numeric `json:"refunds"`
	Discounts    pgtype.Numeric `json:"discounts"`
	Cost         pgtype.Numeric `json:"cost"`
}

// Counts and sums split by kind over [from, to) — from/to are timestamptz
// bounds computed by the service (§ 04-DATA-MODEL.md rule 9: shop
// timezone is applied there, not in SQL). The "sf" CTE filters the sales
// header once; a second CTE aggregates cost from sale_items separately so
// joining items never fans out the header-level sums (revenue, refunds,
// discounts) — a naive single JOIN would multiply each sale's total by
// its item count. cost = cost of sold items minus cost of returned items
// (net cost of goods actually kept by customers); staff only (§
// 04-DATA-MODEL.md rule 8) — see SalesSummaryForCashier for the cashier
// equivalent with no cost column.
func (q *Queries) SalesSummaryForStaff(ctx context.Context, arg SalesSummaryForStaffParams) (SalesSummaryForStaffRow, error) {
	row := q.db.QueryRow(ctx, salesSummaryForStaff,
		arg.ShopID,
		arg.From,
		arg.To,
		arg.LocationID,
		arg.CashierID,
	)
	var i SalesSummaryForStaffRow
	err := row.Scan(
		&i.SalesCount,
		&i.ReturnsCount,
		&i.Revenue,
		&i.Refunds,
		&i.Discounts,
		&i.Cost,
	)
	return i, err
}
