// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sale_drafts.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSaleDraft = `-- name: CreateSaleDraft :one
INSERT INTO sale_drafts (
    id, shop_id, location_id, customer_id,
    discount_type, discount_value, discount_reason, note, created_by
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9
)
RETURNING id, shop_id, location_id, customer_id, discount_type, discount_value, discount_reason, note, created_by, created_at, updated_at
`

type CreateSaleDraftParams struct {
	ID             uuid.UUID      `json:"id"`
	ShopID         uuid.UUID      `json:"shop_id"`
	LocationID     uuid.UUID      `json:"location_id"`
	CustomerID     *uuid.UUID     `json:"customer_id"`
	DiscountType   *DiscountType  `json:"discount_type"`
	DiscountValue  pgtype.Numeric `json:"discount_value"`
	DiscountReason *string        `json:"discount_reason"`
	Note           *string        `json:"note"`
	CreatedBy      *uuid.UUID     `json:"created_by"`
}

// The draft header. Written whole at POST time (unlike purchases' own
// draft state, a sale draft has no separate "create empty, add items
// later" step in the API — POST /sales/drafts takes the full body,
// D-87) — discount_type/discount_value/discount_reason/customer_id/note
// are all optional and simply narg here, no clear-flag dance (that is
// only needed for the PATCH path, UpdateSaleDraft below). No price, no
// sale number (D-87): those exist only once the draft completes.
func (q *Queries) CreateSaleDraft(ctx context.Context, arg CreateSaleDraftParams) (SaleDraft, error) {
	row := q.db.QueryRow(ctx, createSaleDraft,
		arg.ID,
		arg.ShopID,
		arg.LocationID,
		arg.CustomerID,
		arg.DiscountType,
		arg.DiscountValue,
		arg.DiscountReason,
		arg.Note,
		arg.CreatedBy,
	)
	var i SaleDraft
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.LocationID,
		&i.CustomerID,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSaleDraft = `-- name: DeleteSaleDraft :execrows
DELETE FROM sale_drafts
WHERE shop_id = $1 AND id = $2
`

type DeleteSaleDraftParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

// Hard delete (D-89: drafts are hard-deleted, no ledger effect). The
// ON DELETE CASCADE on sale_draft_items.sale_draft_id (0017_sale_drafts.sql)
// removes its lines in the same statement; DeleteSaleDraftItems above
// exists only for the PATCH replace-items path, not for this delete.
func (q *Queries) DeleteSaleDraft(ctx context.Context, arg DeleteSaleDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSaleDraft, arg.ShopID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSaleDraftItems = `-- name: DeleteSaleDraftItems :execrows
DELETE FROM sale_draft_items
WHERE shop_id = $1 AND sale_draft_id = $2
`

type DeleteSaleDraftItemsParams struct {
	ShopID      uuid.UUID `json:"shop_id"`
	SaleDraftID uuid.UUID `json:"sale_draft_id"`
}

// Join rows, hard-deleted (§ 04-DATA-MODEL.md rule 7); used by the
// service to replace a draft's whole line set on PATCH (delete then
// re-InsertSaleDraftItem), same pattern as DeletePurchaseItems. Unlike
// DeletePurchaseItems there is no status guard here — a draft has no
// status, it is editable until it is completed or deleted.
func (q *Queries) DeleteSaleDraftItems(ctx context.Context, arg DeleteSaleDraftItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSaleDraftItems, arg.ShopID, arg.SaleDraftID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSaleDraft = `-- name: GetSaleDraft :one
SELECT sd.id, sd.shop_id, sd.location_id, sd.customer_id, sd.discount_type, sd.discount_value, sd.discount_reason, sd.note, sd.created_by, sd.created_at, sd.updated_at, u.full_name AS created_by_name
FROM sale_drafts sd
LEFT JOIN users u ON u.id = sd.created_by AND u.shop_id = sd.shop_id
WHERE sd.shop_id = $1 AND sd.id = $2
`

type GetSaleDraftParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

type GetSaleDraftRow struct {
	ID             uuid.UUID      `json:"id"`
	ShopID         uuid.UUID      `json:"shop_id"`
	LocationID     uuid.UUID      `json:"location_id"`
	CustomerID     *uuid.UUID     `json:"customer_id"`
	DiscountType   *DiscountType  `json:"discount_type"`
	DiscountValue  pgtype.Numeric `json:"discount_value"`
	DiscountReason *string        `json:"discount_reason"`
	Note           *string        `json:"note"`
	CreatedBy      *uuid.UUID     `json:"created_by"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	CreatedByName  *string        `json:"created_by_name"`
}

// LEFT JOIN, not JOIN: created_by is nullable (D-89's "no creator on
// record" case) and a user row could in principle be gone later — either
// case still returns the draft, with created_by_name simply NULL, same
// reasoning as ListMovementsWithCreatedByName (stock.sql). Resolving the
// name here avoids a second lookup by the admin/mobile client.
func (q *Queries) GetSaleDraft(ctx context.Context, arg GetSaleDraftParams) (GetSaleDraftRow, error) {
	row := q.db.QueryRow(ctx, getSaleDraft, arg.ShopID, arg.ID)
	var i GetSaleDraftRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.LocationID,
		&i.CustomerID,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
	)
	return i, err
}

const getSaleDraftForUpdate = `-- name: GetSaleDraftForUpdate :one
SELECT id, shop_id, location_id, customer_id, discount_type, discount_value, discount_reason, note, created_by, created_at, updated_at FROM sale_drafts
WHERE shop_id = $1 AND id = $2
FOR UPDATE
`

type GetSaleDraftForUpdateParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

// Locks the header row before the complete flow (D-87: completion
// creates the sale via sales.Service and deletes the draft in the same
// transaction), so two concurrent completions of the same draft cannot
// both proceed — mirrors GetSaleForUpdate/GetPurchaseForUpdate.
func (q *Queries) GetSaleDraftForUpdate(ctx context.Context, arg GetSaleDraftForUpdateParams) (SaleDraft, error) {
	row := q.db.QueryRow(ctx, getSaleDraftForUpdate, arg.ShopID, arg.ID)
	var i SaleDraft
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.LocationID,
		&i.CustomerID,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSaleDraftItem = `-- name: InsertSaleDraftItem :one
INSERT INTO sale_draft_items (id, shop_id, sale_draft_id, variant_id, qty, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, shop_id, sale_draft_id, variant_id, qty, position, created_at
`

type InsertSaleDraftItemParams struct {
	ID          uuid.UUID      `json:"id"`
	ShopID      uuid.UUID      `json:"shop_id"`
	SaleDraftID uuid.UUID      `json:"sale_draft_id"`
	VariantID   uuid.UUID      `json:"variant_id"`
	Qty         pgtype.Numeric `json:"qty"`
	Position    int32          `json:"position"`
}

// One line. No price/cost column (D-87) — qty and position only; the
// service assigns position (line order) as it inserts each line.
func (q *Queries) InsertSaleDraftItem(ctx context.Context, arg InsertSaleDraftItemParams) (SaleDraftItem, error) {
	row := q.db.QueryRow(ctx, insertSaleDraftItem,
		arg.ID,
		arg.ShopID,
		arg.SaleDraftID,
		arg.VariantID,
		arg.Qty,
		arg.Position,
	)
	var i SaleDraftItem
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.SaleDraftID,
		&i.VariantID,
		&i.Qty,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listSaleDraftItems = `-- name: ListSaleDraftItems :many
SELECT id, shop_id, sale_draft_id, variant_id, qty, position, created_at FROM sale_draft_items
WHERE shop_id = $1 AND sale_draft_id = $2
ORDER BY position, id
`

type ListSaleDraftItemsParams struct {
	ShopID      uuid.UUID `json:"shop_id"`
	SaleDraftID uuid.UUID `json:"sale_draft_id"`
}

// Ordered by position (line order), `, id` tiebreaker for determinism if
// two lines ever share a position (same reasoning as
// ListPurchaseItems/ListVariantsForStaff's own tiebreakers).
func (q *Queries) ListSaleDraftItems(ctx context.Context, arg ListSaleDraftItemsParams) ([]SaleDraftItem, error) {
	rows, err := q.db.Query(ctx, listSaleDraftItems, arg.ShopID, arg.SaleDraftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleDraftItem
	for rows.Next() {
		var i SaleDraftItem
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.SaleDraftID,
			&i.VariantID,
			&i.Qty,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleDraftItemsForPricing = `-- name: ListSaleDraftItemsForPricing :many
SELECT
    sdi.sale_draft_id, sdi.id, sdi.variant_id, sdi.qty, sdi.position,
    pv.sku AS variant_sku, pv.attributes AS variant_attributes, pv.price_override,
    (pv.is_active AND pv.deleted_at IS NULL) AS variant_available,
    p.id AS product_id,
    (p.is_active AND p.deleted_at IS NULL) AS product_available,
    p.base_price, p.promo_price, p.promo_from, p.promo_to,
    COALESCE(t.name, '') AS product_name
FROM sale_draft_items sdi
JOIN product_variants pv ON pv.id = sdi.variant_id AND pv.shop_id = sdi.shop_id
JOIN products p ON p.id = pv.product_id AND p.shop_id = sdi.shop_id
LEFT JOIN LATERAL (
    SELECT pt.name
    FROM product_translations pt
    WHERE pt.product_id = p.id
    ORDER BY
        CASE
            WHEN pt.locale = $1 THEN 0
            WHEN pt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
WHERE sdi.shop_id = $2 AND sdi.sale_draft_id = ANY($3::uuid[])
ORDER BY sdi.sale_draft_id, sdi.position, sdi.id
`

type ListSaleDraftItemsForPricingParams struct {
	Locale       string      `json:"locale"`
	ShopID       uuid.UUID   `json:"shop_id"`
	SaleDraftIds []uuid.UUID `json:"sale_draft_ids"`
}

type ListSaleDraftItemsForPricingRow struct {
	SaleDraftID       uuid.UUID       `json:"sale_draft_id"`
	ID                uuid.UUID       `json:"id"`
	VariantID         uuid.UUID       `json:"variant_id"`
	Qty               pgtype.Numeric  `json:"qty"`
	Position          int32           `json:"position"`
	VariantSku        *string         `json:"variant_sku"`
	VariantAttributes json.RawMessage `json:"variant_attributes"`
	PriceOverride     pgtype.Numeric  `json:"price_override"`
	VariantAvailable  *bool           `json:"variant_available"`
	ProductID         uuid.UUID       `json:"product_id"`
	ProductAvailable  *bool           `json:"product_available"`
	BasePrice         pgtype.Numeric  `json:"base_price"`
	PromoPrice        pgtype.Numeric  `json:"promo_price"`
	PromoFrom         *time.Time      `json:"promo_from"`
	PromoTo           *time.Time      `json:"promo_to"`
	ProductName       string          `json:"product_name"`
}

// Batched replacement for a per-line GetVariantForCashier +
// GetProductForCashier round trip (review MAJOR: N+1 in ListSaleDrafts):
// one query prices every line of every draft named in sale_draft_ids at
// once, the same ANY($ids) batching ListCoverImagesForProducts already
// uses for D-83. Cost-free (product_variants/products columns only, no
// cost_price/cost_override) — a draft never exposes cost to any role
// (§ 04-DATA-MODEL.md rule 8). Plain (not LEFT) JOINs are safe here: the
// NOT NULL FK on both product_variants.id and products.id blocks a hard
// delete while a draft line still references them (rule 7), so a row
// always resolves even after a soft delete — variant_available/
// product_available surface that state (deleted_at IS NULL AND
// is_active) instead of a missing row, so the service can render the
// line with available: false rather than erroring (review CRITICAL:
// priceDraftItems must not 500 on an inactive/soft-deleted line).
func (q *Queries) ListSaleDraftItemsForPricing(ctx context.Context, arg ListSaleDraftItemsForPricingParams) ([]ListSaleDraftItemsForPricingRow, error) {
	rows, err := q.db.Query(ctx, listSaleDraftItemsForPricing, arg.Locale, arg.ShopID, arg.SaleDraftIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSaleDraftItemsForPricingRow
	for rows.Next() {
		var i ListSaleDraftItemsForPricingRow
		if err := rows.Scan(
			&i.SaleDraftID,
			&i.ID,
			&i.VariantID,
			&i.Qty,
			&i.Position,
			&i.VariantSku,
			&i.VariantAttributes,
			&i.PriceOverride,
			&i.VariantAvailable,
			&i.ProductID,
			&i.ProductAvailable,
			&i.BasePrice,
			&i.PromoPrice,
			&i.PromoFrom,
			&i.PromoTo,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleDrafts = `-- name: ListSaleDrafts :many
SELECT sd.id, sd.shop_id, sd.location_id, sd.customer_id, sd.discount_type, sd.discount_value, sd.discount_reason, sd.note, sd.created_by, sd.created_at, sd.updated_at, u.full_name AS created_by_name
FROM sale_drafts sd
LEFT JOIN users u ON u.id = sd.created_by AND u.shop_id = sd.shop_id
WHERE sd.shop_id = $1
    AND ($2::uuid IS NULL OR sd.created_by = $2)
    AND (
        $3::timestamptz IS NULL
        OR (sd.created_at, sd.id) < ($3::timestamptz, $4::uuid)
    )
ORDER BY sd.created_at DESC, sd.id DESC
LIMIT $5
`

type ListSaleDraftsParams struct {
	ShopID          uuid.UUID  `json:"shop_id"`
	CreatedBy       *uuid.UUID `json:"created_by"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	Limit           int32      `json:"limit"`
}

type ListSaleDraftsRow struct {
	ID             uuid.UUID      `json:"id"`
	ShopID         uuid.UUID      `json:"shop_id"`
	LocationID     uuid.UUID      `json:"location_id"`
	CustomerID     *uuid.UUID     `json:"customer_id"`
	DiscountType   *DiscountType  `json:"discount_type"`
	DiscountValue  pgtype.Numeric `json:"discount_value"`
	DiscountReason *string        `json:"discount_reason"`
	Note           *string        `json:"note"`
	CreatedBy      *uuid.UUID     `json:"created_by"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	CreatedByName  *string        `json:"created_by_name"`
}

// Keyset pagination on (created_at, id), newest first, same convention as
// ListSalesForStaff/ListPurchases. created_by is an optional exact-match
// filter (GET /sales/drafts?createdBy=..., § 05-API.md). LEFT JOIN users
// for created_by_name, same one-query-per-page shape
// ListMovementsWithCreatedByName (stock.sql) and ListSalesForStaff's own
// cashier_name join already use — a page's worth of names in this same
// query, never a lookup per row (no N+1).
func (q *Queries) ListSaleDrafts(ctx context.Context, arg ListSaleDraftsParams) ([]ListSaleDraftsRow, error) {
	rows, err := q.db.Query(ctx, listSaleDrafts,
		arg.ShopID,
		arg.CreatedBy,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSaleDraftsRow
	for rows.Next() {
		var i ListSaleDraftsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.LocationID,
			&i.CustomerID,
			&i.DiscountType,
			&i.DiscountValue,
			&i.DiscountReason,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSaleDraft = `-- name: UpdateSaleDraft :one
UPDATE sale_drafts
SET
    location_id = COALESCE($1, location_id),
    customer_id = CASE WHEN $2::bool THEN NULL ELSE COALESCE($3, customer_id) END,
    discount_type = CASE WHEN $4::bool THEN NULL ELSE COALESCE($5, discount_type) END,
    discount_value = CASE WHEN $4::bool THEN NULL ELSE COALESCE($6, discount_value) END,
    discount_reason = CASE WHEN $7::bool THEN NULL ELSE COALESCE($8, discount_reason) END,
    note = CASE WHEN $9::bool THEN NULL ELSE COALESCE($10, note) END,
    updated_at = now()
WHERE shop_id = $11 AND id = $12
RETURNING id, shop_id, location_id, customer_id, discount_type, discount_value, discount_reason, note, created_by, created_at, updated_at
`

type UpdateSaleDraftParams struct {
	LocationID          *uuid.UUID     `json:"location_id"`
	ClearCustomer       bool           `json:"clear_customer"`
	CustomerID          *uuid.UUID     `json:"customer_id"`
	ClearDiscount       bool           `json:"clear_discount"`
	DiscountType        *DiscountType  `json:"discount_type"`
	DiscountValue       pgtype.Numeric `json:"discount_value"`
	ClearDiscountReason bool           `json:"clear_discount_reason"`
	DiscountReason      *string        `json:"discount_reason"`
	ClearNote           bool           `json:"clear_note"`
	Note                *string        `json:"note"`
	ShopID              uuid.UUID      `json:"shop_id"`
	ID                  uuid.UUID      `json:"id"`
}

// Patch, same clear-flag shape as UpdatePurchaseHeader/UpdateProduct:
// COALESCE cannot express "set to NULL". clear_customer clears
// customer_id alone; clear_discount clears discount_type AND
// discount_value together (they are one concept, same reasoning as
// UpdateProduct's clear_promo) — discount_reason has its own
// clear_discount_reason since a reason can outlive or be cleared
// independently of the discount amount itself. items are not touched
// here (PATCH .../drafts/{id} replaces the whole line set separately via
// DeleteSaleDraftItems + InsertSaleDraftItem, same pattern as
// purchase_items).
func (q *Queries) UpdateSaleDraft(ctx context.Context, arg UpdateSaleDraftParams) (SaleDraft, error) {
	row := q.db.QueryRow(ctx, updateSaleDraft,
		arg.LocationID,
		arg.ClearCustomer,
		arg.CustomerID,
		arg.ClearDiscount,
		arg.DiscountType,
		arg.DiscountValue,
		arg.ClearDiscountReason,
		arg.DiscountReason,
		arg.ClearNote,
		arg.Note,
		arg.ShopID,
		arg.ID,
	)
	var i SaleDraft
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.LocationID,
		&i.CustomerID,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
