// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCompletedReturnsForSale = `-- name: CountCompletedReturnsForSale :one
SELECT count(*) FROM sales
WHERE shop_id = $1 AND original_sale_id = $2 AND kind = 'return' AND status = 'completed'
`

type CountCompletedReturnsForSaleParams struct {
	ShopID         uuid.UUID  `json:"shop_id"`
	OriginalSaleID *uuid.UUID `json:"original_sale_id"`
}

// D-62: a sale with an existing completed return cannot be voided; the
// service checks this before calling VoidSale.
func (q *Queries) CountCompletedReturnsForSale(ctx context.Context, arg CountCompletedReturnsForSaleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedReturnsForSale, arg.ShopID, arg.OriginalSaleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSaleForCashier = `-- name: GetSaleForCashier :one
SELECT
    s.id, s.shop_id, s.number, s.kind, s.status, s.location_id, s.customer_id, s.cashier_id, s.original_sale_id, s.subtotal, s.discount_amount, s.discount_reason, s.total, s.note, s.completed_at, s.voided_at, s.voided_by, s.void_reason, s.created_at,
    l.name AS location_name,
    c.full_name AS customer_name,
    u.full_name AS cashier_name,
    p.method AS payment_method,
    p.amount AS payment_amount,
    EXISTS (
        SELECT 1 FROM sales r
        WHERE r.shop_id = s.shop_id AND r.original_sale_id = s.id
            AND r.kind = 'return' AND r.status = 'completed'
    ) AS has_returns
FROM sales s
JOIN locations l ON l.id = s.location_id
LEFT JOIN customers c ON c.id = s.customer_id
JOIN users u ON u.id = s.cashier_id
LEFT JOIN sale_payments p ON p.sale_id = s.id
WHERE s.shop_id = $1 AND s.id = $2
`

type GetSaleForCashierParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

type GetSaleForCashierRow struct {
	ID             uuid.UUID      `json:"id"`
	ShopID         uuid.UUID      `json:"shop_id"`
	Number         int64          `json:"number"`
	Kind           SaleKind       `json:"kind"`
	Status         SaleStatus     `json:"status"`
	LocationID     uuid.UUID      `json:"location_id"`
	CustomerID     *uuid.UUID     `json:"customer_id"`
	CashierID      uuid.UUID      `json:"cashier_id"`
	OriginalSaleID *uuid.UUID     `json:"original_sale_id"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	DiscountReason *string        `json:"discount_reason"`
	Total          pgtype.Numeric `json:"total"`
	Note           *string        `json:"note"`
	CompletedAt    time.Time      `json:"completed_at"`
	VoidedAt       *time.Time     `json:"voided_at"`
	VoidedBy       *uuid.UUID     `json:"voided_by"`
	VoidReason     *string        `json:"void_reason"`
	CreatedAt      time.Time      `json:"created_at"`
	LocationName   string         `json:"location_name"`
	CustomerName   *string        `json:"customer_name"`
	CashierName    string         `json:"cashier_name"`
	PaymentMethod  *PaymentMethod `json:"payment_method"`
	PaymentAmount  pgtype.Numeric `json:"payment_amount"`
	HasReturns     bool           `json:"has_returns"`
}

// Same shape as GetSaleForStaff — the sales header carries no cost/margin
// column, so there is nothing to strip today (D-63). Kept as its own
// query, not a shared one filtered in Go, so a future header-level cost
// column cannot leak into the cashier path by accident (§ 04-DATA-MODEL.md
// rule 8).
func (q *Queries) GetSaleForCashier(ctx context.Context, arg GetSaleForCashierParams) (GetSaleForCashierRow, error) {
	row := q.db.QueryRow(ctx, getSaleForCashier, arg.ShopID, arg.ID)
	var i GetSaleForCashierRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.LocationID,
		&i.CustomerID,
		&i.CashierID,
		&i.OriginalSaleID,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.DiscountReason,
		&i.Total,
		&i.Note,
		&i.CompletedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedAt,
		&i.LocationName,
		&i.CustomerName,
		&i.CashierName,
		&i.PaymentMethod,
		&i.PaymentAmount,
		&i.HasReturns,
	)
	return i, err
}

const getSaleForStaff = `-- name: GetSaleForStaff :one
SELECT
    s.id, s.shop_id, s.number, s.kind, s.status, s.location_id, s.customer_id, s.cashier_id, s.original_sale_id, s.subtotal, s.discount_amount, s.discount_reason, s.total, s.note, s.completed_at, s.voided_at, s.voided_by, s.void_reason, s.created_at,
    l.name AS location_name,
    c.full_name AS customer_name,
    u.full_name AS cashier_name,
    p.method AS payment_method,
    p.amount AS payment_amount,
    EXISTS (
        SELECT 1 FROM sales r
        WHERE r.shop_id = s.shop_id AND r.original_sale_id = s.id
            AND r.kind = 'return' AND r.status = 'completed'
    ) AS has_returns
FROM sales s
JOIN locations l ON l.id = s.location_id
LEFT JOIN customers c ON c.id = s.customer_id
JOIN users u ON u.id = s.cashier_id
LEFT JOIN sale_payments p ON p.sale_id = s.id
WHERE s.shop_id = $1 AND s.id = $2
`

type GetSaleForStaffParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

type GetSaleForStaffRow struct {
	ID             uuid.UUID      `json:"id"`
	ShopID         uuid.UUID      `json:"shop_id"`
	Number         int64          `json:"number"`
	Kind           SaleKind       `json:"kind"`
	Status         SaleStatus     `json:"status"`
	LocationID     uuid.UUID      `json:"location_id"`
	CustomerID     *uuid.UUID     `json:"customer_id"`
	CashierID      uuid.UUID      `json:"cashier_id"`
	OriginalSaleID *uuid.UUID     `json:"original_sale_id"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	DiscountReason *string        `json:"discount_reason"`
	Total          pgtype.Numeric `json:"total"`
	Note           *string        `json:"note"`
	CompletedAt    time.Time      `json:"completed_at"`
	VoidedAt       *time.Time     `json:"voided_at"`
	VoidedBy       *uuid.UUID     `json:"voided_by"`
	VoidReason     *string        `json:"void_reason"`
	CreatedAt      time.Time      `json:"created_at"`
	LocationName   string         `json:"location_name"`
	CustomerName   *string        `json:"customer_name"`
	CashierName    string         `json:"cashier_name"`
	PaymentMethod  *PaymentMethod `json:"payment_method"`
	PaymentAmount  pgtype.Numeric `json:"payment_amount"`
	HasReturns     bool           `json:"has_returns"`
}

// has_returns backs D-62 (a sale with an existing return cannot be
// voided) without a second round trip. payment_method/payment_amount
// come from the sale's one payment (D-54, sale_payments unique(sale_id));
// LEFT JOIN so a header still resolves even in the — currently
// impossible, but defensive — case a payment row is missing.
func (q *Queries) GetSaleForStaff(ctx context.Context, arg GetSaleForStaffParams) (GetSaleForStaffRow, error) {
	row := q.db.QueryRow(ctx, getSaleForStaff, arg.ShopID, arg.ID)
	var i GetSaleForStaffRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.LocationID,
		&i.CustomerID,
		&i.CashierID,
		&i.OriginalSaleID,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.DiscountReason,
		&i.Total,
		&i.Note,
		&i.CompletedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedAt,
		&i.LocationName,
		&i.CustomerName,
		&i.CashierName,
		&i.PaymentMethod,
		&i.PaymentAmount,
		&i.HasReturns,
	)
	return i, err
}

const getSaleForUpdate = `-- name: GetSaleForUpdate :one
SELECT id, shop_id, number, kind, status, location_id, customer_id, cashier_id, original_sale_id, subtotal, discount_amount, discount_reason, total, note, completed_at, voided_at, voided_by, void_reason, created_at FROM sales
WHERE shop_id = $1 AND id = $2
FOR UPDATE
`

type GetSaleForUpdateParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

// Locks the header row before a void or a return-against-it, so two
// concurrent requests cannot both observe status = 'completed' and race
// (mirrors GetPurchaseForUpdate).
func (q *Queries) GetSaleForUpdate(ctx context.Context, arg GetSaleForUpdateParams) (Sale, error) {
	row := q.db.QueryRow(ctx, getSaleForUpdate, arg.ShopID, arg.ID)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.LocationID,
		&i.CustomerID,
		&i.CashierID,
		&i.OriginalSaleID,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.DiscountReason,
		&i.Total,
		&i.Note,
		&i.CompletedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedAt,
	)
	return i, err
}

const getSaleItemsForUpdate = `-- name: GetSaleItemsForUpdate :many
SELECT id, shop_id, sale_id, variant_id, qty, unit_price, unit_cost, line_total, original_sale_item_id, created_at FROM sale_items
WHERE shop_id = $1 AND sale_id = $2
ORDER BY created_at, id
FOR UPDATE
`

type GetSaleItemsForUpdateParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	SaleID uuid.UUID `json:"sale_id"`
}

// Locks the original sale's item rows before computing "already returned
// per line" for a new partial return, so two concurrent partial returns
// against the same sale cannot both under-count what was already
// refunded.
func (q *Queries) GetSaleItemsForUpdate(ctx context.Context, arg GetSaleItemsForUpdateParams) ([]SaleItem, error) {
	rows, err := q.db.Query(ctx, getSaleItemsForUpdate, arg.ShopID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleItem
	for rows.Next() {
		var i SaleItem
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.SaleID,
			&i.VariantID,
			&i.Qty,
			&i.UnitPrice,
			&i.UnitCost,
			&i.LineTotal,
			&i.OriginalSaleItemID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariantForSale = `-- name: GetVariantForSale :one
SELECT
    v.id AS variant_id, v.product_id, v.price_override, v.cost_override,
    v.is_active AS variant_is_active,
    p.base_price, p.cost_price, p.promo_price, p.promo_from, p.promo_to,
    p.is_active AS product_is_active
FROM product_variants v
JOIN products p ON p.id = v.product_id AND p.shop_id = v.shop_id
WHERE v.shop_id = $1 AND v.id = $2
    AND v.deleted_at IS NULL AND p.deleted_at IS NULL
`

type GetVariantForSaleParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

type GetVariantForSaleRow struct {
	VariantID       uuid.UUID      `json:"variant_id"`
	ProductID       uuid.UUID      `json:"product_id"`
	PriceOverride   pgtype.Numeric `json:"price_override"`
	CostOverride    pgtype.Numeric `json:"cost_override"`
	VariantIsActive bool           `json:"variant_is_active"`
	BasePrice       pgtype.Numeric `json:"base_price"`
	CostPrice       pgtype.Numeric `json:"cost_price"`
	PromoPrice      pgtype.Numeric `json:"promo_price"`
	PromoFrom       *time.Time     `json:"promo_from"`
	PromoTo         *time.Time     `json:"promo_to"`
	ProductIsActive bool           `json:"product_is_active"`
}

// Loads a variant plus its product's pricing/cost fields in one round
// trip, for CreateSale's per-line price resolution (D-56, T3): only a
// variant that belongs to the shop and is not soft-deleted, whose product
// is also not soft-deleted, resolves at all — deleted_at IS NULL on both,
// the same guard GetVariantForStaff/GetProductForStaff each already
// apply. The service additionally checks variant_is_active and
// product_is_active (both returned here) before selling: an inactive
// variant or product is not client-supplied pricing, so this is not a
// pricing rule, but "not for sale" is still this query's concern to
// surface, not a second round trip's. price_override/cost_override are
// the variant's own (§ 04-DATA-MODEL.md § 2); base_price/cost_price/
// promo_price/promo_from/promo_to are the product's — the caller combines
// them into one effective unit price and unit cost.
//
// This query reads cost_price/cost_override on every CreateSale call,
// including a cashier's — not a rule 8 violation (orchestrator ruling):
// rule 8 governs response-shaping queries; an internal pricing query may
// read cost inside the write transaction as long as no cost value ever
// reaches a cashier response (CreateSaleTx freezes it into
// sale_items.unit_cost, which ListSaleItemsForCashier/GetSaleForCashier
// never select).
func (q *Queries) GetVariantForSale(ctx context.Context, arg GetVariantForSaleParams) (GetVariantForSaleRow, error) {
	row := q.db.QueryRow(ctx, getVariantForSale, arg.ShopID, arg.ID)
	var i GetVariantForSaleRow
	err := row.Scan(
		&i.VariantID,
		&i.ProductID,
		&i.PriceOverride,
		&i.CostOverride,
		&i.VariantIsActive,
		&i.BasePrice,
		&i.CostPrice,
		&i.PromoPrice,
		&i.PromoFrom,
		&i.PromoTo,
		&i.ProductIsActive,
	)
	return i, err
}

const insertSale = `-- name: InsertSale :one
INSERT INTO sales (
    id, shop_id, number, kind, location_id, customer_id, cashier_id,
    original_sale_id, subtotal, discount_amount, discount_reason, total, note
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13
)
RETURNING id, shop_id, number, kind, status, location_id, customer_id, cashier_id, original_sale_id, subtotal, discount_amount, discount_reason, total, note, completed_at, voided_at, voided_by, void_reason, created_at
`

type InsertSaleParams struct {
	ID             uuid.UUID      `json:"id"`
	ShopID         uuid.UUID      `json:"shop_id"`
	Number         int64          `json:"number"`
	Kind           SaleKind       `json:"kind"`
	LocationID     uuid.UUID      `json:"location_id"`
	CustomerID     *uuid.UUID     `json:"customer_id"`
	CashierID      uuid.UUID      `json:"cashier_id"`
	OriginalSaleID *uuid.UUID     `json:"original_sale_id"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	DiscountReason *string        `json:"discount_reason"`
	Total          pgtype.Numeric `json:"total"`
	Note           *string        `json:"note"`
}

// The sale header, written once and complete (no draft state — unlike
// purchases). number always comes from NextSaleNumber. subtotal/total are
// computed server-side from the items about to be inserted, never trusted
// from the client (hard rule 8).
func (q *Queries) InsertSale(ctx context.Context, arg InsertSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, insertSale,
		arg.ID,
		arg.ShopID,
		arg.Number,
		arg.Kind,
		arg.LocationID,
		arg.CustomerID,
		arg.CashierID,
		arg.OriginalSaleID,
		arg.Subtotal,
		arg.DiscountAmount,
		arg.DiscountReason,
		arg.Total,
		arg.Note,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.LocationID,
		&i.CustomerID,
		&i.CashierID,
		&i.OriginalSaleID,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.DiscountReason,
		&i.Total,
		&i.Note,
		&i.CompletedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedAt,
	)
	return i, err
}

const insertSaleItem = `-- name: InsertSaleItem :one
INSERT INTO sale_items (
    id, shop_id, sale_id, variant_id, qty, unit_price, unit_cost, line_total, original_sale_item_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9
)
RETURNING id, shop_id, sale_id, variant_id, qty, unit_price, unit_cost, line_total, original_sale_item_id, created_at
`

type InsertSaleItemParams struct {
	ID                 uuid.UUID      `json:"id"`
	ShopID             uuid.UUID      `json:"shop_id"`
	SaleID             uuid.UUID      `json:"sale_id"`
	VariantID          uuid.UUID      `json:"variant_id"`
	Qty                pgtype.Numeric `json:"qty"`
	UnitPrice          pgtype.Numeric `json:"unit_price"`
	UnitCost           pgtype.Numeric `json:"unit_cost"`
	LineTotal          pgtype.Numeric `json:"line_total"`
	OriginalSaleItemID *uuid.UUID     `json:"original_sale_item_id"`
}

// unit_price/unit_cost are frozen at sale time by the service (catalogue
// price/promo, cost_price or cost_override) — never client-supplied.
// original_sale_item_id is set only for a return row (D-61).
func (q *Queries) InsertSaleItem(ctx context.Context, arg InsertSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, insertSaleItem,
		arg.ID,
		arg.ShopID,
		arg.SaleID,
		arg.VariantID,
		arg.Qty,
		arg.UnitPrice,
		arg.UnitCost,
		arg.LineTotal,
		arg.OriginalSaleItemID,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.SaleID,
		&i.VariantID,
		&i.Qty,
		&i.UnitPrice,
		&i.UnitCost,
		&i.LineTotal,
		&i.OriginalSaleItemID,
		&i.CreatedAt,
	)
	return i, err
}

const insertSalePayment = `-- name: InsertSalePayment :one
INSERT INTO sale_payments (id, shop_id, sale_id, method, amount)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, shop_id, sale_id, method, amount, created_at
`

type InsertSalePaymentParams struct {
	ID     uuid.UUID      `json:"id"`
	ShopID uuid.UUID      `json:"shop_id"`
	SaleID uuid.UUID      `json:"sale_id"`
	Method PaymentMethod  `json:"method"`
	Amount pgtype.Numeric `json:"amount"`
}

func (q *Queries) InsertSalePayment(ctx context.Context, arg InsertSalePaymentParams) (SalePayment, error) {
	row := q.db.QueryRow(ctx, insertSalePayment,
		arg.ID,
		arg.ShopID,
		arg.SaleID,
		arg.Method,
		arg.Amount,
	)
	var i SalePayment
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.SaleID,
		&i.Method,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listSaleItemsForCashier = `-- name: ListSaleItemsForCashier :many
SELECT
    si.id, si.sale_id, si.variant_id, si.qty, si.unit_price, si.line_total,
    si.original_sale_item_id, si.created_at,
    p.id AS product_id,
    v.sku AS variant_sku,
    v.attributes AS variant_attributes,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS product_name,
    COALESCE(r.returned_qty, 0)::numeric(12,3) AS returned_qty
FROM sale_items si
JOIN product_variants v ON v.id = si.variant_id AND v.shop_id = si.shop_id
JOIN products p ON p.id = v.product_id AND p.shop_id = si.shop_id
LEFT JOIN LATERAL (
    SELECT pt.locale, pt.name
    FROM product_translations pt
    WHERE pt.product_id = p.id
    ORDER BY
        CASE
            WHEN pt.locale = $1 THEN 0
            WHEN pt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
LEFT JOIN LATERAL (
    SELECT sum(ri.qty) AS returned_qty
    FROM sale_items ri
    JOIN sales rs ON rs.id = ri.sale_id
    WHERE ri.shop_id = si.shop_id AND ri.original_sale_item_id = si.id AND rs.shop_id = si.shop_id AND rs.kind = 'return' AND rs.status = 'completed'
) r ON true
WHERE si.shop_id = $2 AND si.sale_id = $3
ORDER BY si.created_at, si.id
`

type ListSaleItemsForCashierParams struct {
	Locale string    `json:"locale"`
	ShopID uuid.UUID `json:"shop_id"`
	SaleID uuid.UUID `json:"sale_id"`
}

type ListSaleItemsForCashierRow struct {
	ID                 uuid.UUID       `json:"id"`
	SaleID             uuid.UUID       `json:"sale_id"`
	VariantID          uuid.UUID       `json:"variant_id"`
	Qty                pgtype.Numeric  `json:"qty"`
	UnitPrice          pgtype.Numeric  `json:"unit_price"`
	LineTotal          pgtype.Numeric  `json:"line_total"`
	OriginalSaleItemID *uuid.UUID      `json:"original_sale_item_id"`
	CreatedAt          time.Time       `json:"created_at"`
	ProductID          uuid.UUID       `json:"product_id"`
	VariantSku         *string         `json:"variant_sku"`
	VariantAttributes  json.RawMessage `json:"variant_attributes"`
	LocaleUsed         string          `json:"locale_used"`
	ProductName        string          `json:"product_name"`
	ReturnedQty        pgtype.Numeric  `json:"returned_qty"`
}

// Same as ListSaleItemsForStaff, minus unit_cost (§ 04-DATA-MODEL.md rule
// 8, D-63): a separate query, not the staff one filtered in Go.
func (q *Queries) ListSaleItemsForCashier(ctx context.Context, arg ListSaleItemsForCashierParams) ([]ListSaleItemsForCashierRow, error) {
	rows, err := q.db.Query(ctx, listSaleItemsForCashier, arg.Locale, arg.ShopID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSaleItemsForCashierRow
	for rows.Next() {
		var i ListSaleItemsForCashierRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.VariantID,
			&i.Qty,
			&i.UnitPrice,
			&i.LineTotal,
			&i.OriginalSaleItemID,
			&i.CreatedAt,
			&i.ProductID,
			&i.VariantSku,
			&i.VariantAttributes,
			&i.LocaleUsed,
			&i.ProductName,
			&i.ReturnedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleItemsForStaff = `-- name: ListSaleItemsForStaff :many
SELECT
    si.id, si.sale_id, si.variant_id, si.qty, si.unit_price, si.unit_cost, si.line_total,
    si.original_sale_item_id, si.created_at,
    p.id AS product_id,
    v.sku AS variant_sku,
    v.attributes AS variant_attributes,
    COALESCE(t.locale, '') AS locale_used,
    COALESCE(t.name, '') AS product_name,
    COALESCE(r.returned_qty, 0)::numeric(12,3) AS returned_qty
FROM sale_items si
JOIN product_variants v ON v.id = si.variant_id AND v.shop_id = si.shop_id
JOIN products p ON p.id = v.product_id AND p.shop_id = si.shop_id
LEFT JOIN LATERAL (
    SELECT pt.locale, pt.name
    FROM product_translations pt
    WHERE pt.product_id = p.id
    ORDER BY
        CASE
            WHEN pt.locale = $1 THEN 0
            WHEN pt.locale = 'uz' THEN 1
            ELSE 2
        END
    LIMIT 1
) t ON true
LEFT JOIN LATERAL (
    SELECT sum(ri.qty) AS returned_qty
    FROM sale_items ri
    JOIN sales rs ON rs.id = ri.sale_id
    WHERE ri.shop_id = si.shop_id AND ri.original_sale_item_id = si.id AND rs.shop_id = si.shop_id AND rs.kind = 'return' AND rs.status = 'completed'
) r ON true
WHERE si.shop_id = $2 AND si.sale_id = $3
ORDER BY si.created_at, si.id
`

type ListSaleItemsForStaffParams struct {
	Locale string    `json:"locale"`
	ShopID uuid.UUID `json:"shop_id"`
	SaleID uuid.UUID `json:"sale_id"`
}

type ListSaleItemsForStaffRow struct {
	ID                 uuid.UUID       `json:"id"`
	SaleID             uuid.UUID       `json:"sale_id"`
	VariantID          uuid.UUID       `json:"variant_id"`
	Qty                pgtype.Numeric  `json:"qty"`
	UnitPrice          pgtype.Numeric  `json:"unit_price"`
	UnitCost           pgtype.Numeric  `json:"unit_cost"`
	LineTotal          pgtype.Numeric  `json:"line_total"`
	OriginalSaleItemID *uuid.UUID      `json:"original_sale_item_id"`
	CreatedAt          time.Time       `json:"created_at"`
	ProductID          uuid.UUID       `json:"product_id"`
	VariantSku         *string         `json:"variant_sku"`
	VariantAttributes  json.RawMessage `json:"variant_attributes"`
	LocaleUsed         string          `json:"locale_used"`
	ProductName        string          `json:"product_name"`
	ReturnedQty        pgtype.Numeric  `json:"returned_qty"`
}

// Mirrors ListPurchaseItemsWithLabels (purchases.sql): joins each
// sale_items row to its variant and product for the response-only
// productId/productName/variantLabel/sku fields, with the same locale
// fallback (requested -> 'uz' -> any, ADR-012). returned_qty sums the qty
// of return-kind items whose original_sale_item_id points back at this
// row, counting only completed returns (a voided return never happened).
// unit_cost is included — staff only (§ 04-DATA-MODEL.md rule 8).
func (q *Queries) ListSaleItemsForStaff(ctx context.Context, arg ListSaleItemsForStaffParams) ([]ListSaleItemsForStaffRow, error) {
	rows, err := q.db.Query(ctx, listSaleItemsForStaff, arg.Locale, arg.ShopID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSaleItemsForStaffRow
	for rows.Next() {
		var i ListSaleItemsForStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.VariantID,
			&i.Qty,
			&i.UnitPrice,
			&i.UnitCost,
			&i.LineTotal,
			&i.OriginalSaleItemID,
			&i.CreatedAt,
			&i.ProductID,
			&i.VariantSku,
			&i.VariantAttributes,
			&i.LocaleUsed,
			&i.ProductName,
			&i.ReturnedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesForCashier = `-- name: ListSalesForCashier :many
SELECT
    s.id, s.shop_id, s.number, s.kind, s.status, s.location_id, s.customer_id, s.cashier_id, s.original_sale_id, s.subtotal, s.discount_amount, s.discount_reason, s.total, s.note, s.completed_at, s.voided_at, s.voided_by, s.void_reason, s.created_at,
    l.name AS location_name,
    c.full_name AS customer_name,
    u.full_name AS cashier_name,
    p.method AS payment_method,
    EXISTS (
        SELECT 1 FROM sales r
        WHERE r.shop_id = s.shop_id AND r.original_sale_id = s.id
            AND r.kind = 'return' AND r.status = 'completed'
    ) AS has_returns
FROM sales s
JOIN locations l ON l.id = s.location_id
LEFT JOIN customers c ON c.id = s.customer_id
JOIN users u ON u.id = s.cashier_id
LEFT JOIN sale_payments p ON p.sale_id = s.id AND p.shop_id = s.shop_id
WHERE s.shop_id = $1
    AND ($2::timestamptz IS NULL OR s.completed_at >= $2)
    AND ($3::timestamptz IS NULL OR s.completed_at < $3)
    AND ($4::uuid IS NULL OR s.location_id = $4)
    AND ($5::uuid IS NULL OR s.cashier_id = $5)
    AND ($6::uuid IS NULL OR s.customer_id = $6)
    AND ($7::sale_kind IS NULL OR s.kind = $7)
    AND ($8::sale_status IS NULL OR s.status = $8)
    AND (
        $9::timestamptz IS NULL
        OR (s.completed_at, s.id) < ($9::timestamptz, $10::uuid)
    )
ORDER BY s.completed_at DESC, s.id DESC
LIMIT $11
`

type ListSalesForCashierParams struct {
	ShopID            uuid.UUID   `json:"shop_id"`
	From              *time.Time  `json:"from"`
	To                *time.Time  `json:"to"`
	LocationID        *uuid.UUID  `json:"location_id"`
	CashierID         *uuid.UUID  `json:"cashier_id"`
	CustomerID        *uuid.UUID  `json:"customer_id"`
	Kind              *SaleKind   `json:"kind"`
	Status            *SaleStatus `json:"status"`
	CursorCompletedAt *time.Time  `json:"cursor_completed_at"`
	CursorID          *uuid.UUID  `json:"cursor_id"`
	Limit             int32       `json:"limit"`
}

type ListSalesForCashierRow struct {
	ID             uuid.UUID      `json:"id"`
	ShopID         uuid.UUID      `json:"shop_id"`
	Number         int64          `json:"number"`
	Kind           SaleKind       `json:"kind"`
	Status         SaleStatus     `json:"status"`
	LocationID     uuid.UUID      `json:"location_id"`
	CustomerID     *uuid.UUID     `json:"customer_id"`
	CashierID      uuid.UUID      `json:"cashier_id"`
	OriginalSaleID *uuid.UUID     `json:"original_sale_id"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	DiscountReason *string        `json:"discount_reason"`
	Total          pgtype.Numeric `json:"total"`
	Note           *string        `json:"note"`
	CompletedAt    time.Time      `json:"completed_at"`
	VoidedAt       *time.Time     `json:"voided_at"`
	VoidedBy       *uuid.UUID     `json:"voided_by"`
	VoidReason     *string        `json:"void_reason"`
	CreatedAt      time.Time      `json:"created_at"`
	LocationName   string         `json:"location_name"`
	CustomerName   *string        `json:"customer_name"`
	CashierName    string         `json:"cashier_name"`
	PaymentMethod  *PaymentMethod `json:"payment_method"`
	HasReturns     bool           `json:"has_returns"`
}

// Same shape as ListSalesForStaff (D-63): the sales header carries no
// cost/margin column, kept as its own query for the same reason as
// GetSaleForCashier above.
func (q *Queries) ListSalesForCashier(ctx context.Context, arg ListSalesForCashierParams) ([]ListSalesForCashierRow, error) {
	rows, err := q.db.Query(ctx, listSalesForCashier,
		arg.ShopID,
		arg.From,
		arg.To,
		arg.LocationID,
		arg.CashierID,
		arg.CustomerID,
		arg.Kind,
		arg.Status,
		arg.CursorCompletedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesForCashierRow
	for rows.Next() {
		var i ListSalesForCashierRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Number,
			&i.Kind,
			&i.Status,
			&i.LocationID,
			&i.CustomerID,
			&i.CashierID,
			&i.OriginalSaleID,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.DiscountReason,
			&i.Total,
			&i.Note,
			&i.CompletedAt,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.CreatedAt,
			&i.LocationName,
			&i.CustomerName,
			&i.CashierName,
			&i.PaymentMethod,
			&i.HasReturns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesForStaff = `-- name: ListSalesForStaff :many
SELECT
    s.id, s.shop_id, s.number, s.kind, s.status, s.location_id, s.customer_id, s.cashier_id, s.original_sale_id, s.subtotal, s.discount_amount, s.discount_reason, s.total, s.note, s.completed_at, s.voided_at, s.voided_by, s.void_reason, s.created_at,
    l.name AS location_name,
    c.full_name AS customer_name,
    u.full_name AS cashier_name,
    p.method AS payment_method,
    EXISTS (
        SELECT 1 FROM sales r
        WHERE r.shop_id = s.shop_id AND r.original_sale_id = s.id
            AND r.kind = 'return' AND r.status = 'completed'
    ) AS has_returns
FROM sales s
JOIN locations l ON l.id = s.location_id
LEFT JOIN customers c ON c.id = s.customer_id
JOIN users u ON u.id = s.cashier_id
LEFT JOIN sale_payments p ON p.sale_id = s.id AND p.shop_id = s.shop_id
WHERE s.shop_id = $1
    AND ($2::timestamptz IS NULL OR s.completed_at >= $2)
    AND ($3::timestamptz IS NULL OR s.completed_at < $3)
    AND ($4::uuid IS NULL OR s.location_id = $4)
    AND ($5::uuid IS NULL OR s.cashier_id = $5)
    AND ($6::uuid IS NULL OR s.customer_id = $6)
    AND ($7::sale_kind IS NULL OR s.kind = $7)
    AND ($8::sale_status IS NULL OR s.status = $8)
    AND (
        $9::timestamptz IS NULL
        OR (s.completed_at, s.id) < ($9::timestamptz, $10::uuid)
    )
ORDER BY s.completed_at DESC, s.id DESC
LIMIT $11
`

type ListSalesForStaffParams struct {
	ShopID            uuid.UUID   `json:"shop_id"`
	From              *time.Time  `json:"from"`
	To                *time.Time  `json:"to"`
	LocationID        *uuid.UUID  `json:"location_id"`
	CashierID         *uuid.UUID  `json:"cashier_id"`
	CustomerID        *uuid.UUID  `json:"customer_id"`
	Kind              *SaleKind   `json:"kind"`
	Status            *SaleStatus `json:"status"`
	CursorCompletedAt *time.Time  `json:"cursor_completed_at"`
	CursorID          *uuid.UUID  `json:"cursor_id"`
	Limit             int32       `json:"limit"`
}

type ListSalesForStaffRow struct {
	ID             uuid.UUID      `json:"id"`
	ShopID         uuid.UUID      `json:"shop_id"`
	Number         int64          `json:"number"`
	Kind           SaleKind       `json:"kind"`
	Status         SaleStatus     `json:"status"`
	LocationID     uuid.UUID      `json:"location_id"`
	CustomerID     *uuid.UUID     `json:"customer_id"`
	CashierID      uuid.UUID      `json:"cashier_id"`
	OriginalSaleID *uuid.UUID     `json:"original_sale_id"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	DiscountReason *string        `json:"discount_reason"`
	Total          pgtype.Numeric `json:"total"`
	Note           *string        `json:"note"`
	CompletedAt    time.Time      `json:"completed_at"`
	VoidedAt       *time.Time     `json:"voided_at"`
	VoidedBy       *uuid.UUID     `json:"voided_by"`
	VoidReason     *string        `json:"void_reason"`
	CreatedAt      time.Time      `json:"created_at"`
	LocationName   string         `json:"location_name"`
	CustomerName   *string        `json:"customer_name"`
	CashierName    string         `json:"cashier_name"`
	PaymentMethod  *PaymentMethod `json:"payment_method"`
	HasReturns     bool           `json:"has_returns"`
}

// Keyset pagination on (completed_at, id), newest first, same convention
// as ListMovements/ListPurchases. from/to are timestamptz bounds computed
// by the service (e.g. a shop-timezone calendar day, § 04-DATA-MODEL.md
// rule 9: timestamps are UTC, the shop timezone is applied in the
// service/reports layer, not here). location/cashier/customer/kind/status
// are optional exact-match filters. payment_method backs SaleSummary's
// required `paymentMethod` field (T3 addition) — LEFT JOIN, same as
// GetSaleForStaff's own payment join, so a header still lists even in the
// — currently impossible, but defensive — case a payment row is missing.
// has_returns is the same EXISTS correlated subquery GetSaleForStaff
// already uses, backing SaleSummary's required `hasReturns` field.
func (q *Queries) ListSalesForStaff(ctx context.Context, arg ListSalesForStaffParams) ([]ListSalesForStaffRow, error) {
	rows, err := q.db.Query(ctx, listSalesForStaff,
		arg.ShopID,
		arg.From,
		arg.To,
		arg.LocationID,
		arg.CashierID,
		arg.CustomerID,
		arg.Kind,
		arg.Status,
		arg.CursorCompletedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesForStaffRow
	for rows.Next() {
		var i ListSalesForStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Number,
			&i.Kind,
			&i.Status,
			&i.LocationID,
			&i.CustomerID,
			&i.CashierID,
			&i.OriginalSaleID,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.DiscountReason,
			&i.Total,
			&i.Note,
			&i.CompletedAt,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.CreatedAt,
			&i.LocationName,
			&i.CustomerName,
			&i.CashierName,
			&i.PaymentMethod,
			&i.HasReturns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSaleNumber = `-- name: NextSaleNumber :one
UPDATE shops
SET next_sale_number = next_sale_number + 1
WHERE id = $1
RETURNING (next_sale_number - 1)::bigint
`

// Row-locking increment, same pattern as NextPurchaseNumber
// (purchases.sql, D-45): the UPDATE itself takes the row lock, so no
// separate SELECT ... FOR UPDATE is needed. Returns the number this sale
// should use (before the increment); never client-supplied (hard rule 8).
func (q *Queries) NextSaleNumber(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextSaleNumber, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const voidSale = `-- name: VoidSale :one
UPDATE sales
SET status = 'voided', voided_at = now(), voided_by = $1, void_reason = $2
WHERE shop_id = $3 AND id = $4 AND status = 'completed' AND kind = 'sale'
RETURNING id, shop_id, number, kind, status, location_id, customer_id, cashier_id, original_sale_id, subtotal, discount_amount, discount_reason, total, note, completed_at, voided_at, voided_by, void_reason, created_at
`

type VoidSaleParams struct {
	VoidedBy   *uuid.UUID `json:"voided_by"`
	VoidReason *string    `json:"void_reason"`
	ShopID     uuid.UUID  `json:"shop_id"`
	ID         uuid.UUID  `json:"id"`
}

// The only UPDATE ever allowed on a sale (ADR-014): the four void
// columns, and only from status = 'completed' AND kind = 'sale' — D-66:
// returns are final and cannot be voided; a wrong return is corrected by
// a new sale, not a void. The `kind = 'sale'` predicate here is this
// query's own guard, not backed by any DB-level constraint — the
// sales_immutable trigger does not look at kind at all (it only checks
// the completed -> voided status transition and which columns changed),
// so nothing in the schema stops a return from being voided by a
// different code path; the service must not call this query, or any
// other write, on a return for a void. A second void or a void of a
// return-kind row returns no row; the service maps that to
// SALE_NOT_VOIDABLE.
func (q *Queries) VoidSale(ctx context.Context, arg VoidSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, voidSale,
		arg.VoidedBy,
		arg.VoidReason,
		arg.ShopID,
		arg.ID,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.LocationID,
		&i.CustomerID,
		&i.CashierID,
		&i.OriginalSaleID,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.DiscountReason,
		&i.Total,
		&i.Note,
		&i.CompletedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedAt,
	)
	return i, err
}
