// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sale_drafts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSaleDraft = `-- name: CreateSaleDraft :one
INSERT INTO sale_drafts (
    id, shop_id, location_id, customer_id,
    discount_type, discount_value, discount_reason, note, created_by
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9
)
RETURNING id, shop_id, location_id, customer_id, discount_type, discount_value, discount_reason, note, created_by, created_at, updated_at
`

type CreateSaleDraftParams struct {
	ID             uuid.UUID      `json:"id"`
	ShopID         uuid.UUID      `json:"shop_id"`
	LocationID     uuid.UUID      `json:"location_id"`
	CustomerID     *uuid.UUID     `json:"customer_id"`
	DiscountType   *DiscountType  `json:"discount_type"`
	DiscountValue  pgtype.Numeric `json:"discount_value"`
	DiscountReason *string        `json:"discount_reason"`
	Note           *string        `json:"note"`
	CreatedBy      *uuid.UUID     `json:"created_by"`
}

// The draft header. Written whole at POST time (unlike purchases' own
// draft state, a sale draft has no separate "create empty, add items
// later" step in the API — POST /sales/drafts takes the full body,
// D-87) — discount_type/discount_value/discount_reason/customer_id/note
// are all optional and simply narg here, no clear-flag dance (that is
// only needed for the PATCH path, UpdateSaleDraft below). No price, no
// sale number (D-87): those exist only once the draft completes.
func (q *Queries) CreateSaleDraft(ctx context.Context, arg CreateSaleDraftParams) (SaleDraft, error) {
	row := q.db.QueryRow(ctx, createSaleDraft,
		arg.ID,
		arg.ShopID,
		arg.LocationID,
		arg.CustomerID,
		arg.DiscountType,
		arg.DiscountValue,
		arg.DiscountReason,
		arg.Note,
		arg.CreatedBy,
	)
	var i SaleDraft
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.LocationID,
		&i.CustomerID,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSaleDraft = `-- name: DeleteSaleDraft :execrows
DELETE FROM sale_drafts
WHERE shop_id = $1 AND id = $2
`

type DeleteSaleDraftParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

// Hard delete (D-89: drafts are hard-deleted, no ledger effect). The
// ON DELETE CASCADE on sale_draft_items.draft_id (0017_sale_drafts.sql)
// removes its lines in the same statement; DeleteSaleDraftItems above
// exists only for the PATCH replace-items path, not for this delete.
func (q *Queries) DeleteSaleDraft(ctx context.Context, arg DeleteSaleDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSaleDraft, arg.ShopID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSaleDraftItems = `-- name: DeleteSaleDraftItems :execrows
DELETE FROM sale_draft_items
WHERE shop_id = $1 AND draft_id = $2
`

type DeleteSaleDraftItemsParams struct {
	ShopID  uuid.UUID `json:"shop_id"`
	DraftID uuid.UUID `json:"draft_id"`
}

// Join rows, hard-deleted (§ 04-DATA-MODEL.md rule 7); used by the
// service to replace a draft's whole line set on PATCH (delete then
// re-InsertSaleDraftItem), same pattern as DeletePurchaseItems. Unlike
// DeletePurchaseItems there is no status guard here — a draft has no
// status, it is editable until it is completed or deleted.
func (q *Queries) DeleteSaleDraftItems(ctx context.Context, arg DeleteSaleDraftItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSaleDraftItems, arg.ShopID, arg.DraftID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSaleDraft = `-- name: GetSaleDraft :one
SELECT id, shop_id, location_id, customer_id, discount_type, discount_value, discount_reason, note, created_by, created_at, updated_at FROM sale_drafts
WHERE shop_id = $1 AND id = $2
`

type GetSaleDraftParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetSaleDraft(ctx context.Context, arg GetSaleDraftParams) (SaleDraft, error) {
	row := q.db.QueryRow(ctx, getSaleDraft, arg.ShopID, arg.ID)
	var i SaleDraft
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.LocationID,
		&i.CustomerID,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSaleDraftForUpdate = `-- name: GetSaleDraftForUpdate :one
SELECT id, shop_id, location_id, customer_id, discount_type, discount_value, discount_reason, note, created_by, created_at, updated_at FROM sale_drafts
WHERE shop_id = $1 AND id = $2
FOR UPDATE
`

type GetSaleDraftForUpdateParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

// Locks the header row before the complete flow (D-87: completion
// creates the sale via sales.Service and deletes the draft in the same
// transaction), so two concurrent completions of the same draft cannot
// both proceed — mirrors GetSaleForUpdate/GetPurchaseForUpdate.
func (q *Queries) GetSaleDraftForUpdate(ctx context.Context, arg GetSaleDraftForUpdateParams) (SaleDraft, error) {
	row := q.db.QueryRow(ctx, getSaleDraftForUpdate, arg.ShopID, arg.ID)
	var i SaleDraft
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.LocationID,
		&i.CustomerID,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSaleDraftItem = `-- name: InsertSaleDraftItem :one
INSERT INTO sale_draft_items (id, shop_id, draft_id, variant_id, qty, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, shop_id, draft_id, variant_id, qty, position, created_at
`

type InsertSaleDraftItemParams struct {
	ID        uuid.UUID      `json:"id"`
	ShopID    uuid.UUID      `json:"shop_id"`
	DraftID   uuid.UUID      `json:"draft_id"`
	VariantID uuid.UUID      `json:"variant_id"`
	Qty       pgtype.Numeric `json:"qty"`
	Position  int32          `json:"position"`
}

// One line. No price/cost column (D-87) — qty and position only; the
// service assigns position (line order) as it inserts each line.
func (q *Queries) InsertSaleDraftItem(ctx context.Context, arg InsertSaleDraftItemParams) (SaleDraftItem, error) {
	row := q.db.QueryRow(ctx, insertSaleDraftItem,
		arg.ID,
		arg.ShopID,
		arg.DraftID,
		arg.VariantID,
		arg.Qty,
		arg.Position,
	)
	var i SaleDraftItem
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.DraftID,
		&i.VariantID,
		&i.Qty,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listSaleDraftItems = `-- name: ListSaleDraftItems :many
SELECT id, shop_id, draft_id, variant_id, qty, position, created_at FROM sale_draft_items
WHERE shop_id = $1 AND draft_id = $2
ORDER BY position, id
`

type ListSaleDraftItemsParams struct {
	ShopID  uuid.UUID `json:"shop_id"`
	DraftID uuid.UUID `json:"draft_id"`
}

// Ordered by position (line order), `, id` tiebreaker for determinism if
// two lines ever share a position (same reasoning as
// ListPurchaseItems/ListVariantsForStaff's own tiebreakers).
func (q *Queries) ListSaleDraftItems(ctx context.Context, arg ListSaleDraftItemsParams) ([]SaleDraftItem, error) {
	rows, err := q.db.Query(ctx, listSaleDraftItems, arg.ShopID, arg.DraftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleDraftItem
	for rows.Next() {
		var i SaleDraftItem
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.DraftID,
			&i.VariantID,
			&i.Qty,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleDrafts = `-- name: ListSaleDrafts :many
SELECT id, shop_id, location_id, customer_id, discount_type, discount_value, discount_reason, note, created_by, created_at, updated_at FROM sale_drafts
WHERE shop_id = $1
    AND ($2::uuid IS NULL OR created_by = $2)
    AND (
        $3::timestamptz IS NULL
        OR (created_at, id) < ($3::timestamptz, $4::uuid)
    )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListSaleDraftsParams struct {
	ShopID          uuid.UUID  `json:"shop_id"`
	CreatedBy       *uuid.UUID `json:"created_by"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	Limit           int32      `json:"limit"`
}

// Keyset pagination on (created_at, id), newest first, same convention as
// ListSalesForStaff/ListPurchases. created_by is an optional exact-match
// filter (GET /sales/drafts?createdBy=..., § 05-API.md).
func (q *Queries) ListSaleDrafts(ctx context.Context, arg ListSaleDraftsParams) ([]SaleDraft, error) {
	rows, err := q.db.Query(ctx, listSaleDrafts,
		arg.ShopID,
		arg.CreatedBy,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleDraft
	for rows.Next() {
		var i SaleDraft
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.LocationID,
			&i.CustomerID,
			&i.DiscountType,
			&i.DiscountValue,
			&i.DiscountReason,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSaleDraft = `-- name: UpdateSaleDraft :one
UPDATE sale_drafts
SET
    location_id = COALESCE($1, location_id),
    customer_id = CASE WHEN $2::bool THEN NULL ELSE COALESCE($3, customer_id) END,
    discount_type = CASE WHEN $4::bool THEN NULL ELSE COALESCE($5, discount_type) END,
    discount_value = CASE WHEN $4::bool THEN NULL ELSE COALESCE($6, discount_value) END,
    discount_reason = CASE WHEN $7::bool THEN NULL ELSE COALESCE($8, discount_reason) END,
    note = CASE WHEN $9::bool THEN NULL ELSE COALESCE($10, note) END,
    updated_at = now()
WHERE shop_id = $11 AND id = $12
RETURNING id, shop_id, location_id, customer_id, discount_type, discount_value, discount_reason, note, created_by, created_at, updated_at
`

type UpdateSaleDraftParams struct {
	LocationID          *uuid.UUID     `json:"location_id"`
	ClearCustomer       bool           `json:"clear_customer"`
	CustomerID          *uuid.UUID     `json:"customer_id"`
	ClearDiscount       bool           `json:"clear_discount"`
	DiscountType        *DiscountType  `json:"discount_type"`
	DiscountValue       pgtype.Numeric `json:"discount_value"`
	ClearDiscountReason bool           `json:"clear_discount_reason"`
	DiscountReason      *string        `json:"discount_reason"`
	ClearNote           bool           `json:"clear_note"`
	Note                *string        `json:"note"`
	ShopID              uuid.UUID      `json:"shop_id"`
	ID                  uuid.UUID      `json:"id"`
}

// Patch, same clear-flag shape as UpdatePurchaseHeader/UpdateProduct:
// COALESCE cannot express "set to NULL". clear_customer clears
// customer_id alone; clear_discount clears discount_type AND
// discount_value together (they are one concept, same reasoning as
// UpdateProduct's clear_promo) — discount_reason has its own
// clear_discount_reason since a reason can outlive or be cleared
// independently of the discount amount itself. items are not touched
// here (PATCH .../drafts/{id} replaces the whole line set separately via
// DeleteSaleDraftItems + InsertSaleDraftItem, same pattern as
// purchase_items).
func (q *Queries) UpdateSaleDraft(ctx context.Context, arg UpdateSaleDraftParams) (SaleDraft, error) {
	row := q.db.QueryRow(ctx, updateSaleDraft,
		arg.LocationID,
		arg.ClearCustomer,
		arg.CustomerID,
		arg.ClearDiscount,
		arg.DiscountType,
		arg.DiscountValue,
		arg.ClearDiscountReason,
		arg.DiscountReason,
		arg.ClearNote,
		arg.Note,
		arg.ShopID,
		arg.ID,
	)
	var i SaleDraft
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.LocationID,
		&i.CustomerID,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
