// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, shop_id, user_id, token_hash, client, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, shop_id, user_id, token_hash, client, user_agent, ip, expires_at, last_seen_at, revoked_at, created_at
`

type CreateSessionParams struct {
	ID        uuid.UUID     `json:"id"`
	ShopID    uuid.UUID     `json:"shop_id"`
	UserID    uuid.UUID     `json:"user_id"`
	TokenHash []byte        `json:"token_hash"`
	Client    SessionClient `json:"client"`
	UserAgent *string       `json:"user_agent"`
	Ip        *netip.Addr   `json:"ip"`
	ExpiresAt time.Time     `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.ShopID,
		arg.UserID,
		arg.TokenHash,
		arg.Client,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.TokenHash,
		&i.Client,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    s.id, s.shop_id, s.user_id, s.token_hash, s.client, s.user_agent, s.ip,
    s.expires_at, s.last_seen_at, s.revoked_at, s.created_at,
    u.username, u.full_name, u.role, u.locale, u.is_active
FROM sessions s
JOIN users u ON u.id = s.user_id AND u.shop_id = s.shop_id
WHERE s.token_hash = $1
    AND s.revoked_at IS NULL
    AND s.expires_at > now()
`

type GetSessionByTokenHashRow struct {
	ID         uuid.UUID     `json:"id"`
	ShopID     uuid.UUID     `json:"shop_id"`
	UserID     uuid.UUID     `json:"user_id"`
	TokenHash  []byte        `json:"token_hash"`
	Client     SessionClient `json:"client"`
	UserAgent  *string       `json:"user_agent"`
	Ip         *netip.Addr   `json:"ip"`
	ExpiresAt  time.Time     `json:"expires_at"`
	LastSeenAt time.Time     `json:"last_seen_at"`
	RevokedAt  *time.Time    `json:"revoked_at"`
	CreatedAt  time.Time     `json:"created_at"`
	Username   string        `json:"username"`
	FullName   string        `json:"full_name"`
	Role       UserRole      `json:"role"`
	Locale     string        `json:"locale"`
	IsActive   bool          `json:"is_active"`
}

// The only lookup that runs before a shop_id is known: the hashed token is
// itself the credential (globally unique), and this query is how the auth
// context (including shop_id) gets established in the first place. Every
// query after this one takes shop_id from that context.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.TokenHash,
		&i.Client,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Username,
		&i.FullName,
		&i.Role,
		&i.Locale,
		&i.IsActive,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, shop_id, user_id, token_hash, client, user_agent, ip, expires_at, last_seen_at, revoked_at, created_at FROM sessions
WHERE shop_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type ListUserSessionsParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.ShopID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.UserID,
			&i.TokenHash,
			&i.Client,
			&i.UserAgent,
			&i.Ip,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE shop_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAllUserSessionsParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, arg.ShopID, arg.UserID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE shop_id = $1 AND id = $2 AND user_id = $3 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ShopID, arg.ID, arg.UserID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET expires_at = $3, last_seen_at = now()
WHERE shop_id = $1 AND id = $2 AND revoked_at IS NULL
`

type TouchSessionParams struct {
	ShopID    uuid.UUID `json:"shop_id"`
	ID        uuid.UUID `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Sliding session (D-29): the caller recomputes expires_at from the
// session's client (web 7d, mobile 30d) and extends it on every
// authenticated request.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ShopID, arg.ID, arg.ExpiresAt)
	return err
}
