// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shops.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createShop = `-- name: CreateShop :one
INSERT INTO shops (id, slug, name)
VALUES ($1, $2, $3)
RETURNING id, slug, name, currency, timezone, default_locale, allow_negative_stock, update_cost_on_purchase, next_sale_number, ai_daily_token_budget, created_at, updated_at, low_stock_threshold, next_purchase_number
`

type CreateShopParams struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

// For seeding: the MVP has exactly one shop (D-30). Columns with defaults
// (currency, timezone, default_locale, next_sale_number, ...) are left to
// the database; use UpdateShop to change them afterwards.
func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, createShop, arg.ID, arg.Slug, arg.Name)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Currency,
		&i.Timezone,
		&i.DefaultLocale,
		&i.AllowNegativeStock,
		&i.UpdateCostOnPurchase,
		&i.NextSaleNumber,
		&i.AiDailyTokenBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LowStockThreshold,
		&i.NextPurchaseNumber,
	)
	return i, err
}

const getShop = `-- name: GetShop :one
SELECT id, slug, name, currency, timezone, default_locale, allow_negative_stock, update_cost_on_purchase, next_sale_number, ai_daily_token_budget, created_at, updated_at, low_stock_threshold, next_purchase_number FROM shops
WHERE id = $1
`

func (q *Queries) GetShop(ctx context.Context, id uuid.UUID) (Shop, error) {
	row := q.db.QueryRow(ctx, getShop, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Currency,
		&i.Timezone,
		&i.DefaultLocale,
		&i.AllowNegativeStock,
		&i.UpdateCostOnPurchase,
		&i.NextSaleNumber,
		&i.AiDailyTokenBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LowStockThreshold,
		&i.NextPurchaseNumber,
	)
	return i, err
}

const getShopBySlug = `-- name: GetShopBySlug :one
SELECT id, slug, name, currency, timezone, default_locale, allow_negative_stock, update_cost_on_purchase, next_sale_number, ai_daily_token_budget, created_at, updated_at, low_stock_threshold, next_purchase_number FROM shops
WHERE slug = $1
`

func (q *Queries) GetShopBySlug(ctx context.Context, slug string) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopBySlug, slug)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Currency,
		&i.Timezone,
		&i.DefaultLocale,
		&i.AllowNegativeStock,
		&i.UpdateCostOnPurchase,
		&i.NextSaleNumber,
		&i.AiDailyTokenBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LowStockThreshold,
		&i.NextPurchaseNumber,
	)
	return i, err
}

const lockShop = `-- name: LockShop :one
SELECT id FROM shops
WHERE id = $1
FOR UPDATE
`

// Per-tenant serialization point for default-location changes: acquire this
// lock first, then decide/update location defaults within the same
// transaction.
func (q *Queries) LockShop(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockShop, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const updateShop = `-- name: UpdateShop :one
UPDATE shops
SET
    name = COALESCE($1, name),
    currency = COALESCE($2, currency),
    timezone = COALESCE($3, timezone),
    default_locale = COALESCE($4, default_locale),
    allow_negative_stock = COALESCE($5, allow_negative_stock),
    update_cost_on_purchase = COALESCE($6, update_cost_on_purchase),
    low_stock_threshold = COALESCE($7, low_stock_threshold),
    ai_daily_token_budget = COALESCE($8, ai_daily_token_budget),
    updated_at = now()
WHERE id = $9
RETURNING id, slug, name, currency, timezone, default_locale, allow_negative_stock, update_cost_on_purchase, next_sale_number, ai_daily_token_budget, created_at, updated_at, low_stock_threshold, next_purchase_number
`

type UpdateShopParams struct {
	Name                 *string   `json:"name"`
	Currency             *string   `json:"currency"`
	Timezone             *string   `json:"timezone"`
	DefaultLocale        *string   `json:"default_locale"`
	AllowNegativeStock   *bool     `json:"allow_negative_stock"`
	UpdateCostOnPurchase *bool     `json:"update_cost_on_purchase"`
	LowStockThreshold    *int32    `json:"low_stock_threshold"`
	AiDailyTokenBudget   *int32    `json:"ai_daily_token_budget"`
	ID                   uuid.UUID `json:"id"`
}

// Patch: every settings field is optional via sqlc.narg + COALESCE, so a
// caller only supplies the fields it wants to change. next_sale_number and
// next_purchase_number are deliberately not here: they are only ever
// advanced under row lock by the sales/purchases flows, never by a
// settings update.
func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, updateShop,
		arg.Name,
		arg.Currency,
		arg.Timezone,
		arg.DefaultLocale,
		arg.AllowNegativeStock,
		arg.UpdateCostOnPurchase,
		arg.LowStockThreshold,
		arg.AiDailyTokenBudget,
		arg.ID,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Currency,
		&i.Timezone,
		&i.DefaultLocale,
		&i.AllowNegativeStock,
		&i.UpdateCostOnPurchase,
		&i.NextSaleNumber,
		&i.AiDailyTokenBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LowStockThreshold,
		&i.NextPurchaseNumber,
	)
	return i, err
}
