// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyLevelDelta = `-- name: ApplyLevelDelta :one
UPDATE stock_levels
SET qty = qty + $1, updated_at = now()
WHERE shop_id = $2 AND variant_id = $3 AND location_id = $4
RETURNING qty
`

type ApplyLevelDeltaParams struct {
	Delta      pgtype.Numeric `json:"delta"`
	ShopID     uuid.UUID      `json:"shop_id"`
	VariantID  uuid.UUID      `json:"variant_id"`
	LocationID uuid.UUID      `json:"location_id"`
}

// THE ONLY WRITE TO stock_levels. Call only after GetLevelForUpdate has
// locked the row and the service has approved the resulting qty.
func (q *Queries) ApplyLevelDelta(ctx context.Context, arg ApplyLevelDeltaParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, applyLevelDelta,
		arg.Delta,
		arg.ShopID,
		arg.VariantID,
		arg.LocationID,
	)
	var qty pgtype.Numeric
	err := row.Scan(&qty)
	return qty, err
}

const countLevelsForShop = `-- name: CountLevelsForShop :one
SELECT count(*) FROM stock_levels WHERE shop_id = $1
`

// `savdo stock rebuild`'s summary line: how many stock_levels rows the
// shop has after the rebuild.
func (q *Queries) CountLevelsForShop(ctx context.Context, shopID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLevelsForShop, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMovementsForShop = `-- name: CountMovementsForShop :one
SELECT count(*) FROM stock_movements WHERE shop_id = $1
`

// `savdo stock rebuild`'s summary line: how many stock_movements rows the
// rebuild's sum was computed from.
func (q *Queries) CountMovementsForShop(ctx context.Context, shopID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMovementsForShop, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLevelForUpdate = `-- name: GetLevelForUpdate :one
SELECT shop_id, variant_id, location_id, qty, updated_at FROM stock_levels
WHERE shop_id = $1 AND variant_id = $2 AND location_id = $3
FOR UPDATE
`

type GetLevelForUpdateParams struct {
	ShopID     uuid.UUID `json:"shop_id"`
	VariantID  uuid.UUID `json:"variant_id"`
	LocationID uuid.UUID `json:"location_id"`
}

func (q *Queries) GetLevelForUpdate(ctx context.Context, arg GetLevelForUpdateParams) (StockLevel, error) {
	row := q.db.QueryRow(ctx, getLevelForUpdate, arg.ShopID, arg.VariantID, arg.LocationID)
	var i StockLevel
	err := row.Scan(
		&i.ShopID,
		&i.VariantID,
		&i.LocationID,
		&i.Qty,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMovement = `-- name: InsertMovement :one
INSERT INTO stock_movements (
    id, shop_id, variant_id, location_id, kind, qty, unit_cost,
    ref_type, ref_id, adjustment_reason, reason, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, shop_id, variant_id, location_id, kind, qty, unit_cost, ref_type, ref_id, adjustment_reason, reason, created_by, created_at
`

type InsertMovementParams struct {
	ID               uuid.UUID         `json:"id"`
	ShopID           uuid.UUID         `json:"shop_id"`
	VariantID        uuid.UUID         `json:"variant_id"`
	LocationID       uuid.UUID         `json:"location_id"`
	Kind             StockMovementKind `json:"kind"`
	Qty              pgtype.Numeric    `json:"qty"`
	UnitCost         pgtype.Numeric    `json:"unit_cost"`
	RefType          *string           `json:"ref_type"`
	RefID            *uuid.UUID        `json:"ref_id"`
	AdjustmentReason *AdjustmentReason `json:"adjustment_reason"`
	Reason           *string           `json:"reason"`
	CreatedBy        *uuid.UUID        `json:"created_by"`
}

// Append-only (a trigger on stock_movements rejects UPDATE/DELETE,
// 0012_stock_ledger.sql) — this is the only statement that ever inserts
// here; nothing updates or deletes a row afterwards.
func (q *Queries) InsertMovement(ctx context.Context, arg InsertMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, insertMovement,
		arg.ID,
		arg.ShopID,
		arg.VariantID,
		arg.LocationID,
		arg.Kind,
		arg.Qty,
		arg.UnitCost,
		arg.RefType,
		arg.RefID,
		arg.AdjustmentReason,
		arg.Reason,
		arg.CreatedBy,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.VariantID,
		&i.LocationID,
		&i.Kind,
		&i.Qty,
		&i.UnitCost,
		&i.RefType,
		&i.RefID,
		&i.AdjustmentReason,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listLevels = `-- name: ListLevels :many
SELECT sl.shop_id, sl.variant_id, sl.location_id, sl.qty, sl.updated_at, pv.product_id, pv.created_at AS variant_created_at
FROM stock_levels sl
JOIN product_variants pv ON pv.id = sl.variant_id AND pv.shop_id = sl.shop_id
WHERE sl.shop_id = $1
    AND ($2::uuid IS NULL OR sl.variant_id = $2)
    AND ($3::uuid IS NULL OR pv.product_id = $3)
    AND ($4::uuid IS NULL OR sl.location_id = $4)
    -- Invariant: cursor_variant_created_at, cursor_variant_id and
    -- cursor_location_id are either all NULL (first page) or all set
    -- (every later page) — never a partial cursor. levelCursorPtr
    -- (api/internal/stock/pagination.go) guarantees this by only ever
    -- returning all three pointers or all three nil. A partial cursor
    -- would silently drop rows: e.g. cursor_variant_created_at set with
    -- cursor_variant_id NULL would make the IS NULL check below only
    -- gate on the first arg, and the second OR branch's
    -- ` + "`" + `pv.id < NULL::uuid` + "`" + ` would then be NULL (neither true nor false)
    -- for every row, so a whole tied created_at group could vanish.
    AND (
        $5::timestamptz IS NULL
        OR pv.created_at < $5::timestamptz
        OR (pv.created_at = $5::timestamptz AND pv.id < $6::uuid)
        OR (
            pv.created_at = $5::timestamptz
            AND pv.id = $6::uuid
            AND sl.location_id > $7::uuid
        )
    )
ORDER BY pv.created_at DESC, pv.id DESC, sl.location_id
LIMIT $8
`

type ListLevelsParams struct {
	ShopID                 uuid.UUID  `json:"shop_id"`
	VariantID              *uuid.UUID `json:"variant_id"`
	ProductID              *uuid.UUID `json:"product_id"`
	LocationID             *uuid.UUID `json:"location_id"`
	CursorVariantCreatedAt *time.Time `json:"cursor_variant_created_at"`
	CursorVariantID        *uuid.UUID `json:"cursor_variant_id"`
	CursorLocationID       *uuid.UUID `json:"cursor_location_id"`
	Limit                  int32      `json:"limit"`
}

type ListLevelsRow struct {
	ShopID           uuid.UUID      `json:"shop_id"`
	VariantID        uuid.UUID      `json:"variant_id"`
	LocationID       uuid.UUID      `json:"location_id"`
	Qty              pgtype.Numeric `json:"qty"`
	UpdatedAt        time.Time      `json:"updated_at"`
	ProductID        uuid.UUID      `json:"product_id"`
	VariantCreatedAt time.Time      `json:"variant_created_at"`
}

// variant/product/location are optional filters (sqlc.narg); product_id is
// reached through product_variants since stock_levels itself has no
// product_id column. Ordered newest variant first, then location (D-92):
// ORDER BY pv.created_at DESC, pv.id DESC, sl.location_id. The cursor
// encodes (variant_created_at, variant_id, location_id); the first two
// columns sort DESC and the third sorts ASC, so a single tuple comparison
// would silently get the third column's direction wrong — the WHERE
// clause instead spells out "this row comes after the cursor row in that
// order" explicitly, one OR branch per tie-break level.
func (q *Queries) ListLevels(ctx context.Context, arg ListLevelsParams) ([]ListLevelsRow, error) {
	rows, err := q.db.Query(ctx, listLevels,
		arg.ShopID,
		arg.VariantID,
		arg.ProductID,
		arg.LocationID,
		arg.CursorVariantCreatedAt,
		arg.CursorVariantID,
		arg.CursorLocationID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLevelsRow
	for rows.Next() {
		var i ListLevelsRow
		if err := rows.Scan(
			&i.ShopID,
			&i.VariantID,
			&i.LocationID,
			&i.Qty,
			&i.UpdatedAt,
			&i.ProductID,
			&i.VariantCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLow = `-- name: ListLow :many
SELECT t.variant_id, t.product_id, t.qty::numeric(12,3) AS qty, COALESCE(p.low_stock_threshold, s.low_stock_threshold) AS threshold, t.variant_created_at
FROM (
    SELECT pv.id AS variant_id, pv.product_id, pv.created_at AS variant_created_at, SUM(sl.qty) AS qty
    FROM product_variants pv
    JOIN stock_levels sl ON sl.variant_id = pv.id AND sl.shop_id = pv.shop_id
    WHERE pv.shop_id = $1 AND pv.deleted_at IS NULL AND pv.is_active
    GROUP BY pv.id, pv.product_id, pv.created_at
) t
JOIN products p ON p.id = t.product_id AND p.deleted_at IS NULL AND p.is_active
JOIN shops s ON s.id = $1
WHERE t.qty <= COALESCE(p.low_stock_threshold, s.low_stock_threshold)
    AND (
        $2::timestamptz IS NULL
        OR (t.variant_created_at, t.variant_id) < ($2::timestamptz, $3::uuid)
    )
ORDER BY t.variant_created_at DESC, t.variant_id DESC
LIMIT $4
`

type ListLowParams struct {
	ShopID                 uuid.UUID  `json:"shop_id"`
	CursorVariantCreatedAt *time.Time `json:"cursor_variant_created_at"`
	CursorVariantID        *uuid.UUID `json:"cursor_variant_id"`
	Limit                  int32      `json:"limit"`
}

type ListLowRow struct {
	VariantID        uuid.UUID      `json:"variant_id"`
	ProductID        uuid.UUID      `json:"product_id"`
	Qty              pgtype.Numeric `json:"qty"`
	Threshold        int32          `json:"threshold"`
	VariantCreatedAt time.Time      `json:"variant_created_at"`
}

// A variant is low when its total qty across every location is at or
// below the effective threshold: the product's own low_stock_threshold
// override, else the shop's default (D-44). Owner ruling: only variants
// that have been stocked at least once (an INNER JOIN to stock_levels — a
// variant that has never had a stock_levels row, i.e. never moved, is not
// "low", it is simply not tracked yet; a variant that sold out to qty 0
// DOES still count, since it has a row), and only active products and
// active variants (soft-deleted rows are already excluded by
// deleted_at IS NULL). Ordered newest variant first (D-92): ORDER BY
// variant_created_at DESC, variant_id DESC — both columns sort the same
// direction, so the cursor is an ordinary two-column keyset comparison.
func (q *Queries) ListLow(ctx context.Context, arg ListLowParams) ([]ListLowRow, error) {
	rows, err := q.db.Query(ctx, listLow,
		arg.ShopID,
		arg.CursorVariantCreatedAt,
		arg.CursorVariantID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLowRow
	for rows.Next() {
		var i ListLowRow
		if err := rows.Scan(
			&i.VariantID,
			&i.ProductID,
			&i.Qty,
			&i.Threshold,
			&i.VariantCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovements = `-- name: ListMovements :many
SELECT id, shop_id, variant_id, location_id, kind, qty, unit_cost, ref_type, ref_id, adjustment_reason, reason, created_by, created_at FROM stock_movements
WHERE shop_id = $1
    AND ($2::uuid IS NULL OR variant_id = $2)
    AND ($3::uuid IS NULL OR location_id = $3)
    AND ($4::stock_movement_kind IS NULL OR kind = $4)
    AND ($5::timestamptz IS NULL OR created_at >= $5)
    AND ($6::timestamptz IS NULL OR created_at <= $6)
    AND (
        $7::timestamptz IS NULL
        OR (created_at, id) < ($7::timestamptz, $8::uuid)
    )
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListMovementsParams struct {
	ShopID          uuid.UUID          `json:"shop_id"`
	VariantID       *uuid.UUID         `json:"variant_id"`
	LocationID      *uuid.UUID         `json:"location_id"`
	Kind            *StockMovementKind `json:"kind"`
	From            *time.Time         `json:"from"`
	To              *time.Time         `json:"to"`
	CursorCreatedAt *time.Time         `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	Limit           int32              `json:"limit"`
}

// Keyset pagination on (created_at, id), newest first; variant/location/
// kind/from/to are optional filters (sqlc.narg).
func (q *Queries) ListMovements(ctx context.Context, arg ListMovementsParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listMovements,
		arg.ShopID,
		arg.VariantID,
		arg.LocationID,
		arg.Kind,
		arg.From,
		arg.To,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.VariantID,
			&i.LocationID,
			&i.Kind,
			&i.Qty,
			&i.UnitCost,
			&i.RefType,
			&i.RefID,
			&i.AdjustmentReason,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsWithCreatedByName = `-- name: ListMovementsWithCreatedByName :many
SELECT m.id, m.shop_id, m.variant_id, m.location_id, m.kind, m.qty, m.unit_cost,
    m.ref_type, m.ref_id, m.adjustment_reason, m.reason, m.created_by, m.created_at,
    u.full_name AS created_by_name
FROM stock_movements m
LEFT JOIN users u ON u.id = m.created_by AND u.shop_id = m.shop_id
WHERE m.shop_id = $1
    AND ($2::uuid IS NULL OR m.variant_id = $2)
    AND ($3::uuid IS NULL OR m.location_id = $3)
    AND ($4::stock_movement_kind IS NULL OR m.kind = $4)
    AND ($5::timestamptz IS NULL OR m.created_at >= $5)
    AND ($6::timestamptz IS NULL OR m.created_at <= $6)
    AND (
        $7::timestamptz IS NULL
        OR (m.created_at, m.id) < ($7::timestamptz, $8::uuid)
    )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $9
`

type ListMovementsWithCreatedByNameParams struct {
	ShopID          uuid.UUID          `json:"shop_id"`
	VariantID       *uuid.UUID         `json:"variant_id"`
	LocationID      *uuid.UUID         `json:"location_id"`
	Kind            *StockMovementKind `json:"kind"`
	From            *time.Time         `json:"from"`
	To              *time.Time         `json:"to"`
	CursorCreatedAt *time.Time         `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	Limit           int32              `json:"limit"`
}

type ListMovementsWithCreatedByNameRow struct {
	ID               uuid.UUID         `json:"id"`
	ShopID           uuid.UUID         `json:"shop_id"`
	VariantID        uuid.UUID         `json:"variant_id"`
	LocationID       uuid.UUID         `json:"location_id"`
	Kind             StockMovementKind `json:"kind"`
	Qty              pgtype.Numeric    `json:"qty"`
	UnitCost         pgtype.Numeric    `json:"unit_cost"`
	RefType          *string           `json:"ref_type"`
	RefID            *uuid.UUID        `json:"ref_id"`
	AdjustmentReason *AdjustmentReason `json:"adjustment_reason"`
	Reason           *string           `json:"reason"`
	CreatedBy        *uuid.UUID        `json:"created_by"`
	CreatedAt        time.Time         `json:"created_at"`
	CreatedByName    *string           `json:"created_by_name"`
}

// GET /stock/movements' own read: same filters and (created_at, id) cursor
// as ListMovements, plus the creating user's display name (contract's
// additive `createdByName`, T3) so the admin never has to look the user up
// itself. LEFT JOIN, not JOIN: created_by is nullable (a seed or a future
// system-written movement may carry no actor), and a user row could in
// principle be gone later — either case must still return the movement,
// with created_by_name simply NULL. u.shop_id = m.shop_id is belt-and-
// braces tenant scoping on the join (hard rule 1), even though created_by
// already only ever holds an id from the movement's own shop.
func (q *Queries) ListMovementsWithCreatedByName(ctx context.Context, arg ListMovementsWithCreatedByNameParams) ([]ListMovementsWithCreatedByNameRow, error) {
	rows, err := q.db.Query(ctx, listMovementsWithCreatedByName,
		arg.ShopID,
		arg.VariantID,
		arg.LocationID,
		arg.Kind,
		arg.From,
		arg.To,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMovementsWithCreatedByNameRow
	for rows.Next() {
		var i ListMovementsWithCreatedByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.VariantID,
			&i.LocationID,
			&i.Kind,
			&i.Qty,
			&i.UnitCost,
			&i.RefType,
			&i.RefID,
			&i.AdjustmentReason,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildLevelsFromMovements = `-- name: RebuildLevelsFromMovements :exec
INSERT INTO stock_levels (shop_id, variant_id, location_id, qty, updated_at)
SELECT m.shop_id, m.variant_id, m.location_id, SUM(m.qty), now()
FROM stock_movements m
WHERE m.shop_id = $1
GROUP BY m.shop_id, m.variant_id, m.location_id
`

// Step 2 of `savdo stock rebuild`. stock_movements is the only source of
// truth (ADR-006); this recomputes every level for the shop from it.
func (q *Queries) RebuildLevelsFromMovements(ctx context.Context, shopID uuid.UUID) error {
	_, err := q.db.Exec(ctx, rebuildLevelsFromMovements, shopID)
	return err
}

const sumMovementsForLevel = `-- name: SumMovementsForLevel :one
SELECT COALESCE(SUM(qty), 0::numeric)::numeric(12,3) AS qty
FROM stock_movements
WHERE shop_id = $1 AND variant_id = $2 AND location_id = $3
`

type SumMovementsForLevelParams struct {
	ShopID     uuid.UUID `json:"shop_id"`
	VariantID  uuid.UUID `json:"variant_id"`
	LocationID uuid.UUID `json:"location_id"`
}

// Used by the rebuild-equals-levels test: sums the ledger directly for one
// (variant, location) and compares it to the corresponding stock_levels
// row, proving ApplyLevelDelta and RebuildLevelsFromMovements agree.
func (q *Queries) SumMovementsForLevel(ctx context.Context, arg SumMovementsForLevelParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumMovementsForLevel, arg.ShopID, arg.VariantID, arg.LocationID)
	var qty pgtype.Numeric
	err := row.Scan(&qty)
	return qty, err
}

const sumVariantQtyByProduct = `-- name: SumVariantQtyByProduct :many

SELECT
    pv.id AS variant_id,
    COALESCE(SUM(sl.qty) FILTER (WHERE l.is_active), 0)::numeric(12,3) AS qty,
    COALESCE(p.low_stock_threshold, s.low_stock_threshold) AS threshold
FROM product_variants pv
JOIN products p ON p.id = pv.product_id AND p.shop_id = pv.shop_id
JOIN shops s ON s.id = pv.shop_id
LEFT JOIN stock_levels sl ON sl.variant_id = pv.id AND sl.shop_id = pv.shop_id
LEFT JOIN locations l ON l.id = sl.location_id AND l.shop_id = pv.shop_id
WHERE pv.shop_id = $1
    AND pv.product_id = $2
    AND pv.deleted_at IS NULL
GROUP BY pv.id, p.low_stock_threshold, s.low_stock_threshold
`

type SumVariantQtyByProductParams struct {
	ShopID    uuid.UUID `json:"shop_id"`
	ProductID uuid.UUID `json:"product_id"`
}

type SumVariantQtyByProductRow struct {
	VariantID uuid.UUID      `json:"variant_id"`
	Qty       pgtype.Numeric `json:"qty"`
	Threshold int32          `json:"threshold"`
}

// Phase 6 public availability (D-99, D-103: "in_stock|low|out_of_stock",
// never a raw quantity, in the response — that mapping happens in the
// service, these queries only sum the ledger-derived levels). Both LEFT
// JOIN stock_levels/locations so a variant with no stock_levels row at all
// (never moved) still returns one row with qty 0, the same "absent row
// means untracked, not necessarily low/out" reasoning ListLow's own doc
// comment uses — unlike ListLow, these do not require at least one
// stock_levels row to exist, since "does this product/page have any
// availability data at all" needs every variant represented, tracked or
// not. The threshold returned is the product's own low_stock_threshold
// override, else the shop's default (D-44) — there is no per-variant
// threshold column.
func (q *Queries) SumVariantQtyByProduct(ctx context.Context, arg SumVariantQtyByProductParams) ([]SumVariantQtyByProductRow, error) {
	rows, err := q.db.Query(ctx, sumVariantQtyByProduct, arg.ShopID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumVariantQtyByProductRow
	for rows.Next() {
		var i SumVariantQtyByProductRow
		if err := rows.Scan(&i.VariantID, &i.Qty, &i.Threshold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumVariantQtyForProducts = `-- name: SumVariantQtyForProducts :many
SELECT
    pv.product_id,
    pv.id AS variant_id,
    COALESCE(SUM(sl.qty) FILTER (WHERE l.is_active), 0)::numeric(12,3) AS qty,
    COALESCE(p.low_stock_threshold, s.low_stock_threshold) AS threshold
FROM product_variants pv
JOIN products p ON p.id = pv.product_id AND p.shop_id = pv.shop_id
JOIN shops s ON s.id = pv.shop_id
LEFT JOIN stock_levels sl ON sl.variant_id = pv.id AND sl.shop_id = pv.shop_id
LEFT JOIN locations l ON l.id = sl.location_id AND l.shop_id = pv.shop_id
WHERE pv.shop_id = $1
    AND pv.product_id = ANY($2::uuid[])
    AND pv.deleted_at IS NULL
GROUP BY pv.product_id, pv.id, p.low_stock_threshold, s.low_stock_threshold
`

type SumVariantQtyForProductsParams struct {
	ShopID     uuid.UUID   `json:"shop_id"`
	ProductIds []uuid.UUID `json:"product_ids"`
}

type SumVariantQtyForProductsRow struct {
	ProductID uuid.UUID      `json:"product_id"`
	VariantID uuid.UUID      `json:"variant_id"`
	Qty       pgtype.Numeric `json:"qty"`
	Threshold int32          `json:"threshold"`
}

// Same as SumVariantQtyByProduct but for a whole page of products in one
// query (no N+1), for the public product list's per-line availability.
func (q *Queries) SumVariantQtyForProducts(ctx context.Context, arg SumVariantQtyForProductsParams) ([]SumVariantQtyForProductsRow, error) {
	rows, err := q.db.Query(ctx, sumVariantQtyForProducts, arg.ShopID, arg.ProductIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumVariantQtyForProductsRow
	for rows.Next() {
		var i SumVariantQtyForProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.VariantID,
			&i.Qty,
			&i.Threshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateLevelsForShop = `-- name: TruncateLevelsForShop :exec
DELETE FROM stock_levels WHERE shop_id = $1
`

// Step 1 of `savdo stock rebuild`: clear this shop's levels (a scoped
// DELETE, not a table-level TRUNCATE — other shops' rows must survive),
// then RebuildLevelsFromMovements recomputes them, in the same transaction.
func (q *Queries) TruncateLevelsForShop(ctx context.Context, shopID uuid.UUID) error {
	_, err := q.db.Exec(ctx, truncateLevelsForShop, shopID)
	return err
}

const upsertLevelRow = `-- name: UpsertLevelRow :exec

INSERT INTO stock_levels (shop_id, variant_id, location_id, qty, updated_at)
VALUES ($1, $2, $3, 0, now())
ON CONFLICT (shop_id, variant_id, location_id) DO NOTHING
`

type UpsertLevelRowParams struct {
	ShopID     uuid.UUID `json:"shop_id"`
	VariantID  uuid.UUID `json:"variant_id"`
	LocationID uuid.UUID `json:"location_id"`
}

// stock.Service.Move's three-step write, in order, inside one transaction:
//  1. UpsertLevelRow   — guarantee a (shop_id, variant_id, location_id) row
//     exists, so step 2 has something to lock.
//  2. GetLevelForUpdate — SELECT ... FOR UPDATE, locks the row and reads
//     the current qty so the service can decide
//     whether the delta is allowed (D-41:
//     allow_negative_stock).
//  3. ApplyLevelDelta   — the actual write.
//
// ApplyLevelDelta is the ONLY statement in this codebase that writes
// stock_levels (ADR-006, § 04-DATA-MODEL.md rule 2); every other query
// here only reads.
func (q *Queries) UpsertLevelRow(ctx context.Context, arg UpsertLevelRowParams) error {
	_, err := q.db.Exec(ctx, upsertLevelRow, arg.ShopID, arg.VariantID, arg.LocationID)
	return err
}
