// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyLevelDelta = `-- name: ApplyLevelDelta :one
UPDATE stock_levels
SET qty = qty + $1, updated_at = now()
WHERE shop_id = $2 AND variant_id = $3 AND location_id = $4
RETURNING qty
`

type ApplyLevelDeltaParams struct {
	Delta      pgtype.Numeric `json:"delta"`
	ShopID     uuid.UUID      `json:"shop_id"`
	VariantID  uuid.UUID      `json:"variant_id"`
	LocationID uuid.UUID      `json:"location_id"`
}

// THE ONLY WRITE TO stock_levels. Call only after GetLevelForUpdate has
// locked the row and the service has approved the resulting qty.
func (q *Queries) ApplyLevelDelta(ctx context.Context, arg ApplyLevelDeltaParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, applyLevelDelta,
		arg.Delta,
		arg.ShopID,
		arg.VariantID,
		arg.LocationID,
	)
	var qty pgtype.Numeric
	err := row.Scan(&qty)
	return qty, err
}

const getLevelForUpdate = `-- name: GetLevelForUpdate :one
SELECT shop_id, variant_id, location_id, qty, updated_at FROM stock_levels
WHERE shop_id = $1 AND variant_id = $2 AND location_id = $3
FOR UPDATE
`

type GetLevelForUpdateParams struct {
	ShopID     uuid.UUID `json:"shop_id"`
	VariantID  uuid.UUID `json:"variant_id"`
	LocationID uuid.UUID `json:"location_id"`
}

func (q *Queries) GetLevelForUpdate(ctx context.Context, arg GetLevelForUpdateParams) (StockLevel, error) {
	row := q.db.QueryRow(ctx, getLevelForUpdate, arg.ShopID, arg.VariantID, arg.LocationID)
	var i StockLevel
	err := row.Scan(
		&i.ShopID,
		&i.VariantID,
		&i.LocationID,
		&i.Qty,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMovement = `-- name: InsertMovement :one
INSERT INTO stock_movements (
    id, shop_id, variant_id, location_id, kind, qty, unit_cost,
    ref_type, ref_id, adjustment_reason, reason, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, shop_id, variant_id, location_id, kind, qty, unit_cost, ref_type, ref_id, adjustment_reason, reason, created_by, created_at
`

type InsertMovementParams struct {
	ID               uuid.UUID         `json:"id"`
	ShopID           uuid.UUID         `json:"shop_id"`
	VariantID        uuid.UUID         `json:"variant_id"`
	LocationID       uuid.UUID         `json:"location_id"`
	Kind             StockMovementKind `json:"kind"`
	Qty              pgtype.Numeric    `json:"qty"`
	UnitCost         pgtype.Numeric    `json:"unit_cost"`
	RefType          *string           `json:"ref_type"`
	RefID            *uuid.UUID        `json:"ref_id"`
	AdjustmentReason *AdjustmentReason `json:"adjustment_reason"`
	Reason           *string           `json:"reason"`
	CreatedBy        *uuid.UUID        `json:"created_by"`
}

// Append-only (a trigger on stock_movements rejects UPDATE/DELETE,
// 0012_stock_ledger.sql) — this is the only statement that ever inserts
// here; nothing updates or deletes a row afterwards.
func (q *Queries) InsertMovement(ctx context.Context, arg InsertMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, insertMovement,
		arg.ID,
		arg.ShopID,
		arg.VariantID,
		arg.LocationID,
		arg.Kind,
		arg.Qty,
		arg.UnitCost,
		arg.RefType,
		arg.RefID,
		arg.AdjustmentReason,
		arg.Reason,
		arg.CreatedBy,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.VariantID,
		&i.LocationID,
		&i.Kind,
		&i.Qty,
		&i.UnitCost,
		&i.RefType,
		&i.RefID,
		&i.AdjustmentReason,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listLevels = `-- name: ListLevels :many
SELECT sl.shop_id, sl.variant_id, sl.location_id, sl.qty, sl.updated_at, pv.product_id
FROM stock_levels sl
JOIN product_variants pv ON pv.id = sl.variant_id
WHERE sl.shop_id = $1
    AND ($2::uuid IS NULL OR sl.variant_id = $2)
    AND ($3::uuid IS NULL OR pv.product_id = $3)
    AND ($4::uuid IS NULL OR sl.location_id = $4)
    AND (
        $5::uuid IS NULL
        OR (sl.variant_id, sl.location_id) > ($5::uuid, $6::uuid)
    )
ORDER BY sl.variant_id, sl.location_id
LIMIT $7
`

type ListLevelsParams struct {
	ShopID           uuid.UUID  `json:"shop_id"`
	VariantID        *uuid.UUID `json:"variant_id"`
	ProductID        *uuid.UUID `json:"product_id"`
	LocationID       *uuid.UUID `json:"location_id"`
	CursorVariantID  *uuid.UUID `json:"cursor_variant_id"`
	CursorLocationID *uuid.UUID `json:"cursor_location_id"`
	Limit            int32      `json:"limit"`
}

type ListLevelsRow struct {
	ShopID     uuid.UUID      `json:"shop_id"`
	VariantID  uuid.UUID      `json:"variant_id"`
	LocationID uuid.UUID      `json:"location_id"`
	Qty        pgtype.Numeric `json:"qty"`
	UpdatedAt  time.Time      `json:"updated_at"`
	ProductID  uuid.UUID      `json:"product_id"`
}

// variant/product/location are optional filters (sqlc.narg); product_id is
// reached through product_variants since stock_levels itself has no
// product_id column. Cursor on (variant_id, location_id): those are the
// immutable identity part of the PK, unlike updated_at, which changes on
// every stock move and would make keyset pagination unstable while paging.
func (q *Queries) ListLevels(ctx context.Context, arg ListLevelsParams) ([]ListLevelsRow, error) {
	rows, err := q.db.Query(ctx, listLevels,
		arg.ShopID,
		arg.VariantID,
		arg.ProductID,
		arg.LocationID,
		arg.CursorVariantID,
		arg.CursorLocationID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLevelsRow
	for rows.Next() {
		var i ListLevelsRow
		if err := rows.Scan(
			&i.ShopID,
			&i.VariantID,
			&i.LocationID,
			&i.Qty,
			&i.UpdatedAt,
			&i.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLow = `-- name: ListLow :many
SELECT t.variant_id, t.product_id, t.qty::numeric(12,3) AS qty, COALESCE(p.low_stock_threshold, s.low_stock_threshold) AS threshold
FROM (
    SELECT pv.id AS variant_id, pv.product_id, COALESCE(SUM(sl.qty), 0::numeric) AS qty
    FROM product_variants pv
    LEFT JOIN stock_levels sl ON sl.variant_id = pv.id AND sl.shop_id = pv.shop_id
    WHERE pv.shop_id = $1 AND pv.deleted_at IS NULL
    GROUP BY pv.id, pv.product_id
) t
JOIN products p ON p.id = t.product_id AND p.deleted_at IS NULL
JOIN shops s ON s.id = $1
WHERE t.qty <= COALESCE(p.low_stock_threshold, s.low_stock_threshold)
    AND (
        $2::uuid IS NULL
        OR t.variant_id > $2::uuid
    )
ORDER BY t.variant_id
LIMIT $3
`

type ListLowParams struct {
	ShopID          uuid.UUID  `json:"shop_id"`
	CursorVariantID *uuid.UUID `json:"cursor_variant_id"`
	Limit           int32      `json:"limit"`
}

type ListLowRow struct {
	VariantID uuid.UUID      `json:"variant_id"`
	ProductID uuid.UUID      `json:"product_id"`
	Qty       pgtype.Numeric `json:"qty"`
	Threshold int32          `json:"threshold"`
}

// A variant is low when its total qty across every location is at or
// below the effective threshold: the product's own low_stock_threshold
// override, else the shop's default (D-44). Starts from product_variants
// (not stock_levels) with a LEFT JOIN, so a variant with no stock_levels
// row at all (never moved) still totals to 0 and counts as low, not
// silently skipped. Cursor on variant_id (stable, unique).
func (q *Queries) ListLow(ctx context.Context, arg ListLowParams) ([]ListLowRow, error) {
	rows, err := q.db.Query(ctx, listLow, arg.ShopID, arg.CursorVariantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLowRow
	for rows.Next() {
		var i ListLowRow
		if err := rows.Scan(
			&i.VariantID,
			&i.ProductID,
			&i.Qty,
			&i.Threshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovements = `-- name: ListMovements :many
SELECT id, shop_id, variant_id, location_id, kind, qty, unit_cost, ref_type, ref_id, adjustment_reason, reason, created_by, created_at FROM stock_movements
WHERE shop_id = $1
    AND ($2::uuid IS NULL OR variant_id = $2)
    AND ($3::uuid IS NULL OR location_id = $3)
    AND ($4::stock_movement_kind IS NULL OR kind = $4)
    AND ($5::timestamptz IS NULL OR created_at >= $5)
    AND ($6::timestamptz IS NULL OR created_at <= $6)
    AND (
        $7::timestamptz IS NULL
        OR (created_at, id) < ($7::timestamptz, $8::uuid)
    )
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListMovementsParams struct {
	ShopID          uuid.UUID          `json:"shop_id"`
	VariantID       *uuid.UUID         `json:"variant_id"`
	LocationID      *uuid.UUID         `json:"location_id"`
	Kind            *StockMovementKind `json:"kind"`
	From            *time.Time         `json:"from"`
	To              *time.Time         `json:"to"`
	CursorCreatedAt *time.Time         `json:"cursor_created_at"`
	CursorID        *uuid.UUID         `json:"cursor_id"`
	Limit           int32              `json:"limit"`
}

// Keyset pagination on (created_at, id), newest first; variant/location/
// kind/from/to are optional filters (sqlc.narg).
func (q *Queries) ListMovements(ctx context.Context, arg ListMovementsParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listMovements,
		arg.ShopID,
		arg.VariantID,
		arg.LocationID,
		arg.Kind,
		arg.From,
		arg.To,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.VariantID,
			&i.LocationID,
			&i.Kind,
			&i.Qty,
			&i.UnitCost,
			&i.RefType,
			&i.RefID,
			&i.AdjustmentReason,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildLevelsFromMovements = `-- name: RebuildLevelsFromMovements :exec
INSERT INTO stock_levels (shop_id, variant_id, location_id, qty, updated_at)
SELECT m.shop_id, m.variant_id, m.location_id, SUM(m.qty), now()
FROM stock_movements m
WHERE m.shop_id = $1
GROUP BY m.shop_id, m.variant_id, m.location_id
`

// Step 2 of `savdo stock rebuild`. stock_movements is the only source of
// truth (ADR-006); this recomputes every level for the shop from it.
func (q *Queries) RebuildLevelsFromMovements(ctx context.Context, shopID uuid.UUID) error {
	_, err := q.db.Exec(ctx, rebuildLevelsFromMovements, shopID)
	return err
}

const sumMovementsForLevel = `-- name: SumMovementsForLevel :one
SELECT COALESCE(SUM(qty), 0::numeric)::numeric(12,3) AS qty
FROM stock_movements
WHERE shop_id = $1 AND variant_id = $2 AND location_id = $3
`

type SumMovementsForLevelParams struct {
	ShopID     uuid.UUID `json:"shop_id"`
	VariantID  uuid.UUID `json:"variant_id"`
	LocationID uuid.UUID `json:"location_id"`
}

// Used by the rebuild-equals-levels test: sums the ledger directly for one
// (variant, location) and compares it to the corresponding stock_levels
// row, proving ApplyLevelDelta and RebuildLevelsFromMovements agree.
func (q *Queries) SumMovementsForLevel(ctx context.Context, arg SumMovementsForLevelParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumMovementsForLevel, arg.ShopID, arg.VariantID, arg.LocationID)
	var qty pgtype.Numeric
	err := row.Scan(&qty)
	return qty, err
}

const truncateLevelsForShop = `-- name: TruncateLevelsForShop :exec
DELETE FROM stock_levels WHERE shop_id = $1
`

// Step 1 of `savdo stock rebuild`: clear this shop's levels (a scoped
// DELETE, not a table-level TRUNCATE — other shops' rows must survive),
// then RebuildLevelsFromMovements recomputes them, in the same transaction.
func (q *Queries) TruncateLevelsForShop(ctx context.Context, shopID uuid.UUID) error {
	_, err := q.db.Exec(ctx, truncateLevelsForShop, shopID)
	return err
}

const upsertLevelRow = `-- name: UpsertLevelRow :exec

INSERT INTO stock_levels (shop_id, variant_id, location_id, qty, updated_at)
VALUES ($1, $2, $3, 0, now())
ON CONFLICT (shop_id, variant_id, location_id) DO NOTHING
`

type UpsertLevelRowParams struct {
	ShopID     uuid.UUID `json:"shop_id"`
	VariantID  uuid.UUID `json:"variant_id"`
	LocationID uuid.UUID `json:"location_id"`
}

// stock.Service.Move's three-step write, in order, inside one transaction:
//  1. UpsertLevelRow   — guarantee a (shop_id, variant_id, location_id) row
//     exists, so step 2 has something to lock.
//  2. GetLevelForUpdate — SELECT ... FOR UPDATE, locks the row and reads
//     the current qty so the service can decide
//     whether the delta is allowed (D-41:
//     allow_negative_stock).
//  3. ApplyLevelDelta   — the actual write.
//
// ApplyLevelDelta is the ONLY statement in this codebase that writes
// stock_levels (ADR-006, § 04-DATA-MODEL.md rule 2); every other query
// here only reads.
func (q *Queries) UpsertLevelRow(ctx context.Context, arg UpsertLevelRowParams) error {
	_, err := q.db.Exec(ctx, upsertLevelRow, arg.ShopID, arg.VariantID, arg.LocationID)
	return err
}
