// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suppliers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (id, shop_id, name, contact_name, phone, telegram_username, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, shop_id, name, contact_name, phone, telegram_username, note, deleted_at, created_at, updated_at
`

type CreateSupplierParams struct {
	ID               uuid.UUID `json:"id"`
	ShopID           uuid.UUID `json:"shop_id"`
	Name             string    `json:"name"`
	ContactName      *string   `json:"contact_name"`
	Phone            *string   `json:"phone"`
	TelegramUsername *string   `json:"telegram_username"`
	Note             *string   `json:"note"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.ID,
		arg.ShopID,
		arg.Name,
		arg.ContactName,
		arg.Phone,
		arg.TelegramUsername,
		arg.Note,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.ContactName,
		&i.Phone,
		&i.TelegramUsername,
		&i.Note,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, shop_id, name, contact_name, phone, telegram_username, note, deleted_at, created_at, updated_at FROM suppliers
WHERE shop_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetSupplierParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplier, arg.ShopID, arg.ID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.ContactName,
		&i.Phone,
		&i.TelegramUsername,
		&i.Note,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, shop_id, name, contact_name, phone, telegram_username, note, deleted_at, created_at, updated_at FROM suppliers
WHERE shop_id = $1
    AND deleted_at IS NULL
    AND (
        $2::text IS NULL
        OR name ILIKE '%' || $2 || '%'
    )
    AND (
        $3::timestamptz IS NULL
        OR (created_at, id) < ($3::timestamptz, $4::uuid)
    )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListSuppliersParams struct {
	ShopID          uuid.UUID  `json:"shop_id"`
	Q               *string    `json:"q"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	Limit           int32      `json:"limit"`
}

// Keyset pagination on (created_at, id), newest first — same convention as
// ListUsers/ListLocations. q is a plain ILIKE substring match on name; the
// suppliers directory is small (O-15-style reasoning), no trigram index
// needed.
func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers,
		arg.ShopID,
		arg.Q,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.ContactName,
			&i.Phone,
			&i.TelegramUsername,
			&i.Note,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSupplier = `-- name: SoftDeleteSupplier :exec
UPDATE suppliers
SET deleted_at = now(), updated_at = now()
WHERE shop_id = $1 AND id = $2
`

type SoftDeleteSupplierParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteSupplier(ctx context.Context, arg SoftDeleteSupplierParams) error {
	_, err := q.db.Exec(ctx, softDeleteSupplier, arg.ShopID, arg.ID)
	return err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET
    name = COALESCE($1, name),
    contact_name = CASE WHEN $2::bool THEN NULL ELSE COALESCE($3, contact_name) END,
    phone = CASE WHEN $4::bool THEN NULL ELSE COALESCE($5, phone) END,
    telegram_username = CASE WHEN $6::bool THEN NULL ELSE COALESCE($7, telegram_username) END,
    note = CASE WHEN $8::bool THEN NULL ELSE COALESCE($9, note) END,
    updated_at = now()
WHERE shop_id = $10 AND id = $11 AND deleted_at IS NULL
RETURNING id, shop_id, name, contact_name, phone, telegram_username, note, deleted_at, created_at, updated_at
`

type UpdateSupplierParams struct {
	Name                  *string   `json:"name"`
	ClearContactName      bool      `json:"clear_contact_name"`
	ContactName           *string   `json:"contact_name"`
	ClearPhone            bool      `json:"clear_phone"`
	Phone                 *string   `json:"phone"`
	ClearTelegramUsername bool      `json:"clear_telegram_username"`
	TelegramUsername      *string   `json:"telegram_username"`
	ClearNote             bool      `json:"clear_note"`
	Note                  *string   `json:"note"`
	ShopID                uuid.UUID `json:"shop_id"`
	ID                    uuid.UUID `json:"id"`
}

// Patch with explicit clear flags for the nullable fields (COALESCE cannot
// express "set to NULL"), same shape as UpdateVariant/UpdateProduct.
func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.Name,
		arg.ClearContactName,
		arg.ContactName,
		arg.ClearPhone,
		arg.Phone,
		arg.ClearTelegramUsername,
		arg.TelegramUsername,
		arg.ClearNote,
		arg.Note,
		arg.ShopID,
		arg.ID,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.ContactName,
		&i.Phone,
		&i.TelegramUsername,
		&i.Note,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
