// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, shop_id, username, password_hash, full_name, phone, role, locale)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, shop_id, username, password_hash, full_name, phone, role, locale, is_active, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	ShopID       uuid.UUID `json:"shop_id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	FullName     string    `json:"full_name"`
	Phone        *string   `json:"phone"`
	Role         UserRole  `json:"role"`
	Locale       string    `json:"locale"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.ShopID,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Phone,
		arg.Role,
		arg.Locale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.Locale,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwner = `-- name: GetOwner :one
SELECT id, shop_id, username, password_hash, full_name, phone, role, locale, is_active, last_login_at, created_at, updated_at FROM users
WHERE shop_id = $1 AND role = 'owner'
ORDER BY created_at ASC
LIMIT 1
`

// The shop's owner account, used by `savdo reset-owner-password` (D-28).
// MVP has exactly one owner per shop; ORDER BY + LIMIT is defensive in case
// that ever changes.
func (q *Queries) GetOwner(ctx context.Context, shopID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getOwner, shopID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.Locale,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, shop_id, username, password_hash, full_name, phone, role, locale, is_active, last_login_at, created_at, updated_at FROM users
WHERE shop_id = $1 AND id = $2
`

type GetUserByIDParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ShopID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.Locale,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, shop_id, username, password_hash, full_name, phone, role, locale, is_active, last_login_at, created_at, updated_at FROM users
WHERE shop_id = $1 AND username = $2
`

type GetUserByUsernameParams struct {
	ShopID   uuid.UUID `json:"shop_id"`
	Username string    `json:"username"`
}

// username is citext: this comparison is case-insensitive by column type,
// no lower() needed.
func (q *Queries) GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, arg.ShopID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.Locale,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, shop_id, username, password_hash, full_name, phone, role, locale, is_active, last_login_at, created_at, updated_at FROM users
WHERE shop_id = $1
    AND (
        $2::timestamptz IS NULL
        OR (created_at, id) < ($2::timestamptz, $3::uuid)
    )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListUsersParams struct {
	ShopID          uuid.UUID  `json:"shop_id"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	Limit           int32      `json:"limit"`
}

// Keyset pagination on (created_at, id), newest first. Pass NULL for both
// cursor_created_at and cursor_id to get the first page; for the next page,
// pass the created_at/id of the last row returned.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.ShopID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.Phone,
			&i.Role,
			&i.Locale,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserLastLogin = `-- name: SetUserLastLogin :exec
UPDATE users
SET last_login_at = now()
WHERE shop_id = $1 AND id = $2
`

type SetUserLastLoginParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SetUserLastLogin(ctx context.Context, arg SetUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, setUserLastLogin, arg.ShopID, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash = $3, updated_at = now()
WHERE shop_id = $1 AND id = $2
`

type SetUserPasswordParams struct {
	ShopID       uuid.UUID `json:"shop_id"`
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ShopID, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    full_name = COALESCE($1, full_name),
    phone = COALESCE($2, phone),
    role = COALESCE($3, role),
    locale = COALESCE($4, locale),
    is_active = COALESCE($5, is_active),
    updated_at = now()
WHERE shop_id = $6 AND id = $7
RETURNING id, shop_id, username, password_hash, full_name, phone, role, locale, is_active, last_login_at, created_at, updated_at
`

type UpdateUserParams struct {
	FullName *string   `json:"full_name"`
	Phone    *string   `json:"phone"`
	Role     *UserRole `json:"role"`
	Locale   *string   `json:"locale"`
	IsActive *bool     `json:"is_active"`
	ShopID   uuid.UUID `json:"shop_id"`
	ID       uuid.UUID `json:"id"`
}

// Patch: full_name/phone/role/locale/is_active are optional. Password and
// last_login_at go through their own single-purpose statements below so a
// generic profile edit can never accidentally touch either.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FullName,
		arg.Phone,
		arg.Role,
		arg.Locale,
		arg.IsActive,
		arg.ShopID,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.Locale,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
