// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: variants.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveVariants = `-- name: CountActiveVariants :one
SELECT count(*) FROM product_variants
WHERE shop_id = $1 AND product_id = $2 AND deleted_at IS NULL AND is_active
`

type CountActiveVariantsParams struct {
	ShopID    uuid.UUID `json:"shop_id"`
	ProductID uuid.UUID `json:"product_id"`
}

// Used by the service to keep "every product has at least one variant"
// (§ 04-DATA-MODEL.md) — refuse deleting the last active variant of a
// product, and to decide when to flip products.has_variants.
func (q *Queries) CountActiveVariants(ctx context.Context, arg CountActiveVariantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveVariants, arg.ShopID, arg.ProductID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO product_variants (
    id, shop_id, product_id, sku, barcode, attributes,
    price_override, cost_override, is_active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, shop_id, product_id, sku, barcode, attributes, price_override, cost_override, is_active, deleted_at, created_at, updated_at
`

type CreateVariantParams struct {
	ID            uuid.UUID       `json:"id"`
	ShopID        uuid.UUID       `json:"shop_id"`
	ProductID     uuid.UUID       `json:"product_id"`
	Sku           *string         `json:"sku"`
	Barcode       *string         `json:"barcode"`
	Attributes    json.RawMessage `json:"attributes"`
	PriceOverride pgtype.Numeric  `json:"price_override"`
	CostOverride  pgtype.Numeric  `json:"cost_override"`
	IsActive      bool            `json:"is_active"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ID,
		arg.ShopID,
		arg.ProductID,
		arg.Sku,
		arg.Barcode,
		arg.Attributes,
		arg.PriceOverride,
		arg.CostOverride,
		arg.IsActive,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Attributes,
		&i.PriceOverride,
		&i.CostOverride,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantForCashier = `-- name: GetVariantForCashier :one
SELECT
    id, shop_id, product_id, sku, barcode, attributes,
    price_override, is_active, deleted_at, created_at, updated_at
FROM product_variants
WHERE shop_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetVariantForCashierParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

type GetVariantForCashierRow struct {
	ID            uuid.UUID       `json:"id"`
	ShopID        uuid.UUID       `json:"shop_id"`
	ProductID     uuid.UUID       `json:"product_id"`
	Sku           *string         `json:"sku"`
	Barcode       *string         `json:"barcode"`
	Attributes    json.RawMessage `json:"attributes"`
	PriceOverride pgtype.Numeric  `json:"price_override"`
	IsActive      bool            `json:"is_active"`
	DeletedAt     *time.Time      `json:"deleted_at"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

func (q *Queries) GetVariantForCashier(ctx context.Context, arg GetVariantForCashierParams) (GetVariantForCashierRow, error) {
	row := q.db.QueryRow(ctx, getVariantForCashier, arg.ShopID, arg.ID)
	var i GetVariantForCashierRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Attributes,
		&i.PriceOverride,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantForStaff = `-- name: GetVariantForStaff :one
SELECT id, shop_id, product_id, sku, barcode, attributes, price_override, cost_override, is_active, deleted_at, created_at, updated_at FROM product_variants
WHERE shop_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetVariantForStaffParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetVariantForStaff(ctx context.Context, arg GetVariantForStaffParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantForStaff, arg.ShopID, arg.ID)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Attributes,
		&i.PriceOverride,
		&i.CostOverride,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVariantsForCashier = `-- name: ListVariantsForCashier :many
SELECT
    id, shop_id, product_id, sku, barcode, attributes,
    price_override, is_active, deleted_at, created_at, updated_at
FROM product_variants
WHERE shop_id = $1 AND product_id = $2 AND deleted_at IS NULL
ORDER BY created_at
`

type ListVariantsForCashierParams struct {
	ShopID    uuid.UUID `json:"shop_id"`
	ProductID uuid.UUID `json:"product_id"`
}

type ListVariantsForCashierRow struct {
	ID            uuid.UUID       `json:"id"`
	ShopID        uuid.UUID       `json:"shop_id"`
	ProductID     uuid.UUID       `json:"product_id"`
	Sku           *string         `json:"sku"`
	Barcode       *string         `json:"barcode"`
	Attributes    json.RawMessage `json:"attributes"`
	PriceOverride pgtype.Numeric  `json:"price_override"`
	IsActive      bool            `json:"is_active"`
	DeletedAt     *time.Time      `json:"deleted_at"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

// No cost_override (§ 04-DATA-MODEL.md rule 8, ADR-010).
func (q *Queries) ListVariantsForCashier(ctx context.Context, arg ListVariantsForCashierParams) ([]ListVariantsForCashierRow, error) {
	rows, err := q.db.Query(ctx, listVariantsForCashier, arg.ShopID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVariantsForCashierRow
	for rows.Next() {
		var i ListVariantsForCashierRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ProductID,
			&i.Sku,
			&i.Barcode,
			&i.Attributes,
			&i.PriceOverride,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsForStaff = `-- name: ListVariantsForStaff :many
SELECT id, shop_id, product_id, sku, barcode, attributes, price_override, cost_override, is_active, deleted_at, created_at, updated_at FROM product_variants
WHERE shop_id = $1 AND product_id = $2 AND deleted_at IS NULL
ORDER BY created_at
`

type ListVariantsForStaffParams struct {
	ShopID    uuid.UUID `json:"shop_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) ListVariantsForStaff(ctx context.Context, arg ListVariantsForStaffParams) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsForStaff, arg.ShopID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ProductID,
			&i.Sku,
			&i.Barcode,
			&i.Attributes,
			&i.PriceOverride,
			&i.CostOverride,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVariant = `-- name: SoftDeleteVariant :exec
UPDATE product_variants
SET deleted_at = now(), updated_at = now()
WHERE shop_id = $1 AND id = $2
`

type SoftDeleteVariantParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteVariant(ctx context.Context, arg SoftDeleteVariantParams) error {
	_, err := q.db.Exec(ctx, softDeleteVariant, arg.ShopID, arg.ID)
	return err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE product_variants
SET
    sku = CASE WHEN $1::bool THEN NULL ELSE COALESCE($2, sku) END,
    barcode = CASE WHEN $3::bool THEN NULL ELSE COALESCE($4, barcode) END,
    price_override = CASE WHEN $5::bool THEN NULL ELSE COALESCE($6, price_override) END,
    cost_override = CASE WHEN $7::bool THEN NULL ELSE COALESCE($8, cost_override) END,
    is_active = COALESCE($9, is_active),
    updated_at = now()
WHERE shop_id = $10 AND id = $11 AND deleted_at IS NULL
RETURNING id, shop_id, product_id, sku, barcode, attributes, price_override, cost_override, is_active, deleted_at, created_at, updated_at
`

type UpdateVariantParams struct {
	ClearSku           bool           `json:"clear_sku"`
	Sku                *string        `json:"sku"`
	ClearBarcode       bool           `json:"clear_barcode"`
	Barcode            *string        `json:"barcode"`
	ClearPriceOverride bool           `json:"clear_price_override"`
	PriceOverride      pgtype.Numeric `json:"price_override"`
	ClearCostOverride  bool           `json:"clear_cost_override"`
	CostOverride       pgtype.Numeric `json:"cost_override"`
	IsActive           *bool          `json:"is_active"`
	ShopID             uuid.UUID      `json:"shop_id"`
	ID                 uuid.UUID      `json:"id"`
}

// Patch with explicit clear flags for sku/barcode/price_override/cost_override
// (COALESCE cannot express "set to NULL"). attributes is intentionally not
// patchable here: it participates in the (product_id, attributes) unique
// constraint and changing it is a delete+recreate at the service layer, not
// an in-place edit.
func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.ClearSku,
		arg.Sku,
		arg.ClearBarcode,
		arg.Barcode,
		arg.ClearPriceOverride,
		arg.PriceOverride,
		arg.ClearCostOverride,
		arg.CostOverride,
		arg.IsActive,
		arg.ShopID,
		arg.ID,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Attributes,
		&i.PriceOverride,
		&i.CostOverride,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
