/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check.
         * @description Reports the process is up. Does not touch the database.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check.
         * @description Reports whether the API's dependencies (currently the database) are reachable. Used by the orchestrator/deploy tooling, not by clients.
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate with username and password.
         * @description For `client: web`, sets the `savdo_session` cookie and omits `token`. For `client: mobile`, returns `token` for the caller to send as `Authorization: Bearer <token>`; no cookie is set (D-29).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user, their shop and their permissions. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user's own sessions. */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke one of the authenticated user's own sessions.
         * @description Revoking the caller's own current session behaves like `POST /auth/logout`. Revoking a session belonging to another user is not possible here — the owner revokes staff sessions by deactivating the staff member (`PATCH /staff/{id}`).
         */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current shop's settings. */
        get: operations["getShop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update shop settings.
         * @description Owner only.
         */
        patch: operations["updateShop"];
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the shop's locations. */
        get: operations["listLocations"];
        put?: never;
        /**
         * Create a location.
         * @description Owner only.
         */
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a location.
         * @description Owner only.
         */
        patch: operations["updateLocation"];
        trace?: never;
    };
    "/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the shop's staff.
         * @description Owner only.
         */
        get: operations["listStaff"];
        put?: never;
        /**
         * Create a staff member (manager or cashier).
         * @description Owner only. The password is set here; see D-28 for resets.
         */
        post: operations["createStaff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a staff member.
         * @description Owner only.
         */
        patch: operations["updateStaff"];
        trace?: never;
    };
    "/staff/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a staff member's password.
         * @description Owner only (D-28). There is no self-service "forgot password" until Phase 7's Telegram OTP flow.
         */
        post: operations["setStaffPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the shop's units of measure.
         * @description Seeded per shop, read-only in Phase 2 (docs/04-DATA-MODEL.md § 2). Not cursor-paginated — the set is small and fixed for now.
         */
        get: operations["listUnits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attribute-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the shop's attribute definitions (e.g. size, colour).
         * @description Not cursor-paginated — seeded with a handful of entries (D-32) and expected to stay small.
         */
        get: operations["listAttributeDefinitions"];
        put?: never;
        /**
         * Create an attribute definition.
         * @description Requires `catalog.write` (manager+).
         */
        post: operations["createAttributeDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attribute-definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update an attribute definition.
         * @description Requires `catalog.write` (manager+). `code` is not patchable — variants already reference it by key (docs/04-DATA-MODEL.md § 2).
         */
        patch: operations["updateAttributeDefinition"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the shop's categories as a flat list.
         * @description Flat, not cursor-paginated — the client builds the tree from `parentId`. Depth is capped at 3 (docs/04-DATA-MODEL.md § 2).
         */
        get: operations["listCategories"];
        put?: never;
        /**
         * Create a category.
         * @description Requires `catalog.write` (manager+). `400 fields.parentId: invalid` when the parent chain would exceed depth 3.
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a category. */
        get: operations["getCategory"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a category.
         * @description Requires `catalog.write` (manager+). `409 CONFLICT details.field: products` when products still reference this category (assumption: D-32/D-34 area, no cascading delete).
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /**
         * Update a category.
         * @description Requires `catalog.write` (manager+). `400 fields.parentId: invalid` when re-parenting would exceed depth 3 or create a cycle.
         */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List products.
         * @description Cursor-paginated. `Product`'s `costPrice`/`translations` are present only for owner/manager, never for a cashier (§ Conventions, ADR-010).
         */
        get: operations["listProducts"];
        put?: never;
        /**
         * Create a product.
         * @description Requires `catalog.write` (manager+).
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a product, including its variants and images.
         * @description `costPrice`/`translations` are present only for owner/manager, like `GET /products` (§ Conventions).
         */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a product.
         * @description Requires `catalog.write` (manager+).
         */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        /**
         * Update a product.
         * @description Requires `catalog.write` (manager+).
         */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/products/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a product's variants.
         * @description Not cursor-paginated — a product has at most a handful of variants. `Variant`'s `costOverride` is present only for owner/manager (§ Conventions).
         */
        get: operations["listVariants"];
        put?: never;
        /**
         * Add a variant to a product.
         * @description Requires `catalog.write` (manager+).
         */
        post: operations["createVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Soft-delete a variant.
         * @description Requires `catalog.write` (manager+). `400 fields.variantId: invalid` when this is the product's only variant — every product must keep at least one (docs/04-DATA-MODEL.md § 2).
         */
        delete: operations["deleteVariant"];
        options?: never;
        head?: never;
        /**
         * Update a variant.
         * @description Requires `catalog.write` (manager+).
         */
        patch: operations["updateVariant"];
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload an image.
         * @description Requires `catalog.write` (manager+). Generates thumb/card/full sizes as WebP (ADR-008). `400 fields.file: invalid` for an unsupported format, `400 fields.file: too_long` over the size limit.
         */
        post: operations["uploadMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach an uploaded image to a product.
         * @description Requires `catalog.write` (manager+). `400 fields.mediaId: invalid` once the product already has 8 images (D-34); `409 CONFLICT details.field: mediaId` when this media file is already attached to the product (`product_images` unique `(product_id, media_id)`, docs/04-DATA-MODEL.md § 2).
         */
        post: operations["addProductImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove an image from a product.
         * @description Requires `catalog.write` (manager+). Hard delete (join row).
         */
        delete: operations["removeProductImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/images/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reorder a product's images and/or change its cover image.
         * @description Requires `catalog.write` (manager+).
         */
        patch: operations["reorderProductImages"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Response body for `GET /healthz`. */
        Healthz: {
            /** @enum {string} */
            status: "ok";
        };
        /** @description Response body for `GET /readyz` (200 and 503 share this shape). */
        Readiness: {
            /** @enum {string} */
            status: "ok" | "degraded";
            checks: {
                /** @enum {string} */
                db: "ok" | "error";
            };
        };
        /**
         * @description Machine-readable error codes (ADR-013). A client translates a code to a display sentence; the API never returns one. Adding a new error code means adding it here first.
         * @enum {string}
         */
        ErrorCode: "VALIDATION_FAILED" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "INTERNAL";
        /** @description The error envelope every non-2xx JSON response uses (ADR-013). */
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description Optional machine-readable context, shape depends on `code`. For `VALIDATION_FAILED` this is `{ "fields": { "<field>": "<reason>" } }`. */
                details?: Record<string, never>;
            };
        };
        /**
         * Format: decimal
         * @description money and quantities as decimal strings (ADR-007)
         */
        Decimal: string;
        /**
         * @description A UI/data locale (ADR-012).
         * @enum {string}
         */
        Locale: "uz" | "ru" | "en";
        /**
         * @description A user's role (04-DATA-MODEL.md § 7 Permissions).
         * @enum {string}
         */
        Role: "owner" | "manager" | "cashier";
        /**
         * @description The roles the owner can assign when creating or editing a staff member. `owner` is not assignable — there is exactly one owner, seeded (D-30).
         * @enum {string}
         */
        StaffRole: "manager" | "cashier";
        /**
         * @description Which client created a session (D-29).
         * @enum {string}
         */
        SessionClient: "web" | "mobile";
        /** @enum {string} */
        LocationKind: "store" | "warehouse";
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            fullName: string;
            phone: string | null;
            role: components["schemas"]["Role"];
            locale: components["schemas"]["Locale"];
            isActive: boolean;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Cursor-paginated envelope for `GET /staff`. */
        UserList: {
            items: components["schemas"]["User"][];
            nextCursor: string | null;
        };
        Shop: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            /** @description ISO 4217 currency code, one per shop (ADR-007). `UZS` in MVP. */
            currency: string;
            /** @description IANA timezone name, e.g. `Asia/Tashkent`. */
            timezone: string;
            defaultLocale: components["schemas"]["Locale"];
            allowNegativeStock: boolean;
            updateCostOnPurchase: boolean;
        };
        /** @description Partial update — only provided fields change. */
        ShopPatch: {
            name?: string;
            timezone?: string;
            defaultLocale?: components["schemas"]["Locale"];
            allowNegativeStock?: boolean;
            updateCostOnPurchase?: boolean;
        };
        Location: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["LocationKind"];
            isDefault: boolean;
            isActive: boolean;
        };
        /** @description Cursor-paginated envelope for `GET /locations`. */
        LocationList: {
            items: components["schemas"]["Location"][];
            nextCursor: string | null;
        };
        LocationCreate: {
            name: string;
            kind: components["schemas"]["LocationKind"];
            isDefault?: boolean;
        };
        /** @description Partial update — only provided fields change. */
        LocationPatch: {
            name?: string;
            kind?: components["schemas"]["LocationKind"];
            isDefault?: boolean;
            isActive?: boolean;
        };
        Session: {
            /** Format: uuid */
            id: string;
            client: components["schemas"]["SessionClient"];
            userAgent: string | null;
            ip: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /**
             * Format: date-time
             * @description Recomputed on every authenticated use, sliding per `client` (D-29): 30 days for `mobile`, 7 days for `web`.
             */
            expiresAt: string;
            /** @description Whether this is the session the request was authenticated with. */
            current: boolean;
        };
        /** @description Cursor-paginated envelope for `GET /auth/sessions`. */
        SessionList: {
            items: components["schemas"]["Session"][];
            nextCursor: string | null;
        };
        LoginRequest: {
            username: string;
            password: string;
            client: components["schemas"]["SessionClient"];
        };
        LoginResponse: {
            user: components["schemas"]["User"];
            session: components["schemas"]["Session"];
            /** @description Bearer token for `client: mobile` only. Absent for `client: web`, which authenticates with the `savdo_session` cookie instead. */
            token?: string;
        };
        Me: {
            user: components["schemas"]["User"];
            shop: components["schemas"]["Shop"];
            /** @description Machine-readable capability strings the UI uses to show/hide actions. The API remains the enforcement point (ADR-010). */
            permissions: string[];
        };
        StaffCreate: {
            username: string;
            password: string;
            fullName: string;
            phone?: string;
            role: components["schemas"]["StaffRole"];
            locale?: components["schemas"]["Locale"];
        };
        /** @description Partial update — only provided fields change. */
        StaffPatch: {
            fullName?: string;
            phone?: string | null;
            role?: components["schemas"]["StaffRole"];
            isActive?: boolean;
            locale?: components["schemas"]["Locale"];
        };
        SetStaffPassword: {
            password: string;
        };
        /** @description One locale's name/description for a translatable entity. */
        TranslationEntry: {
            name: string;
            description?: string;
        };
        /** @description Per-locale name/description (ADR-012), keyed by `Locale`. On create, an entry for the shop's own default locale is required — expressible only as a service-level rule, since the JSON Schema can't know a given shop's `defaultLocale` value. On PATCH, each provided locale entry fully replaces the stored entry for that locale; omitted locales are left unchanged. Response fields outside this object (`name`/`description`/`locale`/ `translationFallback`) are the entity resolved for the caller's `Accept-Language`, fallback order `requested → uz → any`. */
        Translations: {
            uz?: components["schemas"]["TranslationEntry"];
            ru?: components["schemas"]["TranslationEntry"];
            en?: components["schemas"]["TranslationEntry"];
        };
        /** @description A unit of measure (docs/04-DATA-MODEL.md § 2). Seeded, read-only in Phase 2. */
        Unit: {
            /** Format: uuid */
            id: string;
            /** @description e.g. `pcs`, `kg`, `m`. */
            code: string;
            /** @description Decimal places a quantity in this unit is stored/displayed with (0 for `pcs`, 3 for `kg`). */
            precision: number;
            /** @description Resolved for the caller's `Accept-Language`. */
            name: string;
            locale: components["schemas"]["Locale"];
            translationFallback: boolean;
        };
        /** @description Flat envelope for `GET /units` (not cursor-paginated). */
        UnitList: {
            items: components["schemas"]["Unit"][];
        };
        /** @description A per-shop variant attribute, e.g. size or colour (D-32). */
        AttributeDefinition: {
            /** Format: uuid */
            id: string;
            /** @description Stable key `product_variants.attributes` values are keyed by, e.g. `size`. */
            code: string;
            sortOrder: number;
            /** @description Resolved for the caller's `Accept-Language`. */
            name: string;
            locale: components["schemas"]["Locale"];
            translationFallback: boolean;
            translations?: components["schemas"]["Translations"];
        };
        AttributeDefinitionCreate: {
            code: string;
            sortOrder?: number;
            translations: components["schemas"]["Translations"];
        };
        /** @description Partial update — only provided fields change. `code` is not patchable. */
        AttributeDefinitionPatch: {
            sortOrder?: number;
            translations?: components["schemas"]["Translations"];
        };
        /** @description Flat envelope for `GET /attribute-definitions` (not cursor-paginated). */
        AttributeDefinitionList: {
            items: components["schemas"]["AttributeDefinition"][];
        };
        Category: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId: string | null;
            slug: string;
            sortOrder: number;
            isActive: boolean;
            /** Format: uuid */
            imageId: string | null;
            /** @description Resolved for the caller's `Accept-Language`. */
            name: string;
            description: string | null;
            locale: components["schemas"]["Locale"];
            translationFallback: boolean;
            translations?: components["schemas"]["Translations"];
        };
        CategoryCreate: {
            /** Format: uuid */
            parentId?: string;
            slug?: string;
            sortOrder?: number;
            isActive?: boolean;
            /** Format: uuid */
            imageId?: string;
            translations: components["schemas"]["Translations"];
        };
        /** @description Partial update — only provided fields change. */
        CategoryPatch: {
            /**
             * Format: uuid
             * @description Explicit `null` moves the category to the top level.
             */
            parentId?: string | null;
            slug?: string;
            sortOrder?: number;
            isActive?: boolean;
            /**
             * Format: uuid
             * @description Explicit `null` removes the category's image.
             */
            imageId?: string | null;
            translations?: components["schemas"]["Translations"];
        };
        /** @description Flat envelope for `GET /categories` (not cursor-paginated; the client builds the tree from `parentId`). */
        CategoryList: {
            items: components["schemas"]["Category"][];
        };
        /** @description A variant's attribute values, keyed by `attribute_definitions.code` (e.g. `{"size": "L", "color": "blue"}`, D-32). */
        AttributeValues: {
            [key: string]: string;
        };
        /**
         * @description Public/bot-facing stock signal — never a quantity (ADR-010, hard rule 4/5).
         * @enum {string}
         */
        Availability: "in_stock" | "low" | "out_of_stock";
        /** @description `costOverride` is present only when the caller has the `cost.read` permission; absent (not null) otherwise (ADR-010). */
        Variant: {
            /** Format: uuid */
            id: string;
            sku: string | null;
            barcode: string | null;
            attributes: components["schemas"]["AttributeValues"];
            /** Format: decimal */
            priceOverride: string | null;
            /**
             * Format: decimal
             * @description Present only when the caller has the `cost.read` permission; absent (not null) otherwise (ADR-010).
             */
            costOverride?: string | null;
            isActive: boolean;
        };
        /** @description Defined now for Phase 6's public catalogue (D-32/D-34); no path references it yet. No cost, no `isActive` (only active variants are ever returned publicly); `availability` replaces any quantity (hard rule 4/5). */
        VariantPublic: {
            /** Format: uuid */
            id: string;
            sku: string | null;
            barcode: string | null;
            attributes: components["schemas"]["AttributeValues"];
            /** Format: decimal */
            priceOverride: string | null;
            availability: components["schemas"]["Availability"];
        };
        VariantCreate: {
            sku?: string;
            barcode?: string;
            attributes: components["schemas"]["AttributeValues"];
            priceOverride?: components["schemas"]["Decimal"];
            costOverride?: components["schemas"]["Decimal"];
            isActive?: boolean;
        };
        /** @description Partial update — only provided fields change. */
        VariantPatch: {
            sku?: string | null;
            barcode?: string | null;
            attributes?: components["schemas"]["AttributeValues"];
            /** Format: decimal */
            priceOverride?: string | null;
            /** Format: decimal */
            costOverride?: string | null;
            isActive?: boolean;
        };
        /** @description Flat envelope for `GET /products/{id}/variants` (not cursor-paginated). */
        VariantList: {
            items: components["schemas"]["Variant"][];
        };
        /** @description `costPrice` and `translations` are present only when the caller has the `cost.read` / `catalog.write` permission; absent (not null) otherwise (ADR-010). */
        Product: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            categoryId: string | null;
            slug: string;
            sku: string | null;
            /** Format: uuid */
            unitId: string;
            basePrice: components["schemas"]["Decimal"];
            /**
             * Format: decimal
             * @description Present only when the caller has the `cost.read` permission; absent (not null) otherwise (ADR-010).
             */
            costPrice?: string;
            /** Format: decimal */
            promoPrice: string | null;
            /** Format: date-time */
            promoFrom: string | null;
            /** Format: date-time */
            promoTo: string | null;
            isActive: boolean;
            isFeatured: boolean;
            /** @description Resolved for the caller's `Accept-Language`. */
            name: string;
            description: string | null;
            locale: components["schemas"]["Locale"];
            translationFallback: boolean;
            /** @description Present only when the caller has the `catalog.write` permission; absent otherwise (ADR-010). */
            translations?: components["schemas"]["Translations"];
            variants?: components["schemas"]["Variant"][];
            images?: components["schemas"]["ProductImage"][];
        };
        /** @description Defined now for Phase 6's public catalogue (D-32/D-34); no path references it yet. Only active products/variants are ever returned this way; variants carry `availability`, never cost or quantity (hard rule 4/5). */
        ProductPublic: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            categoryId: string | null;
            slug: string;
            sku: string | null;
            /** Format: uuid */
            unitId: string;
            basePrice: components["schemas"]["Decimal"];
            /** Format: decimal */
            promoPrice: string | null;
            /** Format: date-time */
            promoFrom: string | null;
            /** Format: date-time */
            promoTo: string | null;
            isActive: boolean;
            isFeatured: boolean;
            /** @description Resolved for the caller's `Accept-Language`. */
            name: string;
            description: string | null;
            locale: components["schemas"]["Locale"];
            translationFallback: boolean;
            variants?: components["schemas"]["VariantPublic"][];
            images?: components["schemas"]["ProductImage"][];
        };
        ProductCreate: {
            /** Format: uuid */
            categoryId?: string;
            slug?: string;
            sku?: string;
            /** Format: uuid */
            unitId: string;
            basePrice: components["schemas"]["Decimal"];
            costPrice?: components["schemas"]["Decimal"];
            promoPrice?: components["schemas"]["Decimal"];
            /** Format: date-time */
            promoFrom?: string;
            /** Format: date-time */
            promoTo?: string;
            isActive?: boolean;
            isFeatured?: boolean;
            translations: components["schemas"]["Translations"];
            variants?: components["schemas"]["VariantCreate"][];
        };
        /** @description Partial update — only provided fields change. `sku`, `promoPrice`, `promoFrom`, `promoTo`, `categoryId` and `costPrice` are nullable (D-35): explicit `null` clears the field. Variants are managed through `/products/{id}/variants` and `/variants/{id}`, not here. */
        ProductPatch: {
            /** Format: uuid */
            categoryId?: string | null;
            slug?: string;
            sku?: string | null;
            /** Format: uuid */
            unitId?: string;
            basePrice?: components["schemas"]["Decimal"];
            /** Format: decimal */
            costPrice?: string | null;
            /** Format: decimal */
            promoPrice?: string | null;
            /** Format: date-time */
            promoFrom?: string | null;
            /** Format: date-time */
            promoTo?: string | null;
            isActive?: boolean;
            isFeatured?: boolean;
            translations?: components["schemas"]["Translations"];
        };
        /** @description Cursor-paginated envelope for `GET /products`. */
        ProductList: {
            items: components["schemas"]["Product"][];
            nextCursor: string | null;
        };
        /** @description Request body for `POST /media` (`multipart/form-data`). */
        MediaUpload: {
            /** Format: binary */
            file: string;
        };
        MediaUrls: {
            /** Format: uri */
            thumb: string;
            /** Format: uri */
            card: string;
            /** Format: uri */
            full: string;
        };
        /** @description Response for `POST /media` (ADR-008 — thumb 200/card 600/full 1600, WebP). */
        MediaFile: {
            /** Format: uuid */
            id: string;
            mime: string;
            width: number;
            height: number;
            sizeBytes: number;
            urls: components["schemas"]["MediaUrls"];
        };
        ProductImage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            mediaId: string;
            /** Format: uuid */
            variantId: string | null;
            isCover: boolean;
            sortOrder: number;
            urls: components["schemas"]["MediaUrls"];
        };
        ProductImageCreate: {
            /** Format: uuid */
            mediaId: string;
            /**
             * Format: uuid
             * @description Ties this image to one variant, e.g. a colour (D-34).
             */
            variantId?: string;
            isCover?: boolean;
        };
        /** @description Request body for `PATCH /products/{id}/images/order`. */
        ProductImageOrder: {
            /** @description Every image id belonging to the product, in the new display order. */
            imageIds: string[];
            /** Format: uuid */
            coverImageId?: string;
        };
        /** @description Envelope for `PATCH /products/{id}/images/order`'s response. */
        ProductImageList: {
            items: components["schemas"]["ProductImage"][];
        };
    };
    responses: {
        /** @description The request has no valid session or bearer token. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The authenticated caller may not perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource does not exist (or is outside the caller's shop). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request body failed validation. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request conflicts with the current state of the resource (e.g. a duplicate username, phone or location name within the shop). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description An unexpected error occurred. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Maximum number of items to return. */
        Limit: number;
        /** @description Opaque cursor from a previous page's `nextCursor`. */
        Cursor: string;
        /** @description Preferred response locale. */
        AcceptLanguage: "uz" | "ru" | "en";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Healthz"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All checks passed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description One or more checks failed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor from a previous page's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    getShop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shop"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    updateShop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShopPatch"];
            };
        };
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shop"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listLocations: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor from a previous page's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationPatch"];
            };
        };
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listStaff: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor from a previous page's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createStaff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    updateStaff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffPatch"];
            };
        };
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    setStaffPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStaffPassword"];
            };
        };
        responses: {
            /** @description Password set. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listUnits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    listAttributeDefinitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinitionList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    createAttributeDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttributeDefinitionCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinition"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    updateAttributeDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttributeDefinitionPatch"];
            };
        };
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinition"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryPatch"];
            };
        };
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                /** @description Free-text search over product name (Postgres ILIKE/trigram). */
                q?: string;
                categoryId?: string;
                includeInactive?: boolean;
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor from a previous page's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductPatch"];
            };
        };
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listVariants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    createVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Variant"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantPatch"];
            };
        };
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Variant"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    uploadMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["MediaUpload"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaFile"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    addProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductImageCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImage"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    removeProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                imageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reorderProductImages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductImageOrder"];
            };
        };
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImageList"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
