/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check.
         * @description Reports the process is up. Does not touch the database.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Response body for `GET /healthz`. */
        Healthz: {
            /** @enum {string} */
            status: "ok";
        };
        /**
         * @description Machine-readable error codes (ADR-013). A client translates a code to a display sentence; the API never returns one. Adding a new error code means adding it here first.
         * @enum {string}
         */
        ErrorCode: "VALIDATION_FAILED" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "INTERNAL";
        /** @description The error envelope every non-2xx JSON response uses (ADR-013). */
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description Optional machine-readable context, shape depends on `code`. */
                details?: Record<string, never>;
            };
        };
        /**
         * Format: decimal
         * @description money and quantities as decimal strings (ADR-007)
         */
        Decimal: string;
    };
    responses: {
        /** @description The request has no valid session or bearer token. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The authenticated caller may not perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource does not exist (or is outside the caller's shop). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description An unexpected error occurred. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Maximum number of items to return. */
        Limit: number;
        /** @description Opaque cursor from a previous page's `nextCursor`. */
        Cursor: string;
        /** @description Preferred response locale. */
        AcceptLanguage: "uz" | "ru" | "en";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Healthz"];
                };
            };
        };
    };
}
